Bugfix/add new space
charmverse/app.charmverse.io pull request #1045
Opened 2022-10-04 19:14 UTC by msadura

Fix for blank page when creating workspace from sidebar.

Additional stuff:
- `useSpaces` will now return object instead of an array
- `createNewSpace` - moved to `useSpaces` to have it in a single place to reuse

2022-10-04 19:15 UTC, msadura commented on hooks/useSpaces.tsx
> +    setTimeout(() => {
lack of this timeout in one of the components caused the issue 😓

2022-10-05 20:31 UTC, mattcasey commented on package.json
> +    "debug:e2e": "dotenv -e .env.test.local -- npx playwright test **YOUR_TEST_PATH.spec.ts** --headed --timeout=0",
i think this makes the command useless? YOu can just add the file at the end. What i've been doing is:
```
npm run debug:e2e __e2e__/login.spec.ts
```
Should we add this to the README?

2022-10-05 20:33 UTC, mattcasey commented on hooks/useSpaces.tsx
> +type IContext = {
thanks for the cleanup of array => map

2022-10-05 20:37 UTC, mattcasey commented on __e2e__/sidebarAddNewSpace.spec.ts
> +    const nameInput = page.locator('data-test=workspace-name-input >> input');
For e2e, I want to be EXTREMELY minimal on what we are testing. Anything that can be done via Cypress or Jest should be done there instead, for example testing that the domain is updated when the name changes should be done in Cypress. I think we should remove all the logic around inputs in this test. Just open the modal and click 'create workspace' and make sure that we get to an actual page on the other side

2022-10-05 20:45 UTC, mattcasey requested changes
one request: reduce the scope of the e2e test

2022-10-05 20:57 UTC, msadura commented on package.json
> +    "debug:e2e": "dotenv -e .env.test.local -- npx playwright test **YOUR_TEST_PATH.spec.ts** --headed --timeout=0",
ah I though you need manually put you filename in there 😅 I will fix that

2022-10-05 21:09 UTC, msadura commented
@mattcasey  updates pushed - removed input tests, added readme info

2022-10-05 21:53 UTC, mattcasey approved these changes

2022-10-05 21:54 UTC, merged