Updated user sign/signup flow
charmverse/app.charmverse.io pull request #1055
Opened 2022-10-06 14:37 UTC by Devorein

2022-10-06 17:16 UTC, mattcasey commented on lib/spaces/getSpacesPublicInfo.ts
> +export async function getSpacesPublicInfo (spaceIdOrDomainOrPageId: string): Promise<Space[]> {
Also, it is never 'spaceId' so spaceIdOrDomainOrPageId is a bad variable name here

2022-10-06 17:18 UTC, mattcasey commented on charmClient/charmClient.ts
> +    return http.GET<Space[]>('/api/spaces/public', { search });
'public' doesnt make sense on its own, imo... it was like 'give me the public info of this space'. I think a better endpoint would be something like 'spaces/searchByTitle' and 'spaces/searchByDomain' or 'spaces/search?title=?domain=`?

2022-10-06 17:20 UTC, mattcasey commented on lib/spaces/getSpacesPublicInfo.ts
> +          contains: spaceIdOrDomainOrPageId
domain must be an exact match

2022-10-06 17:20 UTC, mattcasey commented on lib/spaces/getSpacesPublicInfo.ts
> +          contains: spaceIdOrDomainOrPageId
Please use Postgres text search, its much more powerful. You can just use `search: value`. see getAccessiblePages for an example.

2022-10-06 17:21 UTC, mattcasey commented on components/common/TokenGateForm/JoinDynamicSpaceForm.tsx
> +    return debounce((_spaceDomain: string) => {
theres no need to debounce search by domain. it should just be a one-time query

2022-10-06 17:27 UTC, mattcasey commented on components/common/TokenGateForm/JoinDynamicSpaceForm.tsx
> +  const popperFactoryMemoized = useMemo(() => {
replace w/a styled component

2022-10-06 17:28 UTC, mattcasey requested changes
i think it's worth changing os we have special requests on the frontend to search by title or domain

2022-10-07 05:06 UTC, Devorein commented on lib/spaces/getSpacesPublicInfo.ts
> +export async function getSpacesPublicInfo (spaceIdOrDomainOrPageId: string): Promise<Space[]> {
Yep created two separate functions for two different purposes. One returning either the space or null when searching for exact match with the domain, the other returning an array when searching by the space name

2022-10-07 05:14 UTC, Devorein commented on charmClient/charmClient.ts
> +    return http.GET<Space[]>('/api/spaces/public', { search });
Right I've updated the types and endpoints

2022-10-07 05:14 UTC, Devorein commented on lib/spaces/getSpacesPublicInfo.ts
> +          contains: spaceIdOrDomainOrPageId
Updated

2022-10-07 05:14 UTC, Devorein commented on lib/spaces/getSpacesPublicInfo.ts
> +          contains: spaceIdOrDomainOrPageId
Updated. Thank you.

2022-10-07 05:17 UTC, Devorein commented on components/common/TokenGateForm/JoinDynamicSpaceForm.tsx
> +    return debounce((_spaceDomain: string) => {
This was for searching by the space name, the argument name is a bit confusing since we supported both domain and title initially but fixed it now.

2022-10-07 05:22 UTC, Devorein commented on components/common/TokenGateForm/JoinDynamicSpaceForm.tsx
> +  useEffect(() => {
Updated.

2022-10-07 05:22 UTC, Devorein commented on components/common/TokenGateForm/JoinDynamicSpaceForm.tsx
> +  const popperFactoryMemoized = useMemo(() => {
Updated.

2022-10-07 09:43 UTC, Devorein commented
I've tested it out on our staging environment, and everything works great, except for discord login (which I think we still don't support automatically)

2022-10-07 11:02 UTC, merged