add checks for signup redirect
charmverse/app.charmverse.io pull request #1068
Opened 2022-10-09 19:59 UTC by mattcasey

2022-10-10 09:19 UTC, msadura requested changes
I would consider rethinking signup flow  check a bit (but probably a case for another card). Currently we will redirect you to token gate page after creating a new account, but if token gate url was incorrect user will may end up stuck and clueless?

2022-10-10 09:19 UTC, msadura commented on pages/index.tsx
> -    if (typeof router.query.returnUrl === 'string') {
you count use helper const like `const redirectTo = router.query.returnUrl;` (used 3 times)

2022-10-10 09:19 UTC, msadura commented on pages/index.tsx
> +    if (typeof router.query.returnUrl === 'string' && (!hasCompletedSignUp || isSpaceDomain(router.query.returnUrl))) {
hmm if I understand this logic correctly it should be `&& (hasCompletedSignUp || isSpaceDomain(router.query.returnUrl)` ?

2022-10-10 09:19 UTC, msadura commented on pages/index.tsx
>      else if (defaultWorkspace === '/nexus') {
not sure if it would be part of this tasks, but this `/nexus` redirect is also error prone. when you log out of space A and then create a new account (with another wallet on the same browser) you will be redirected directly to `/nexus` without any workspace

2022-10-10 21:00 UTC, mattcasey commented
> Currently we will redirect you to token gate page after creating a new account, but if token gate url was incorrect user will may end up stuck and clueless?

We do not, actually send you directly to the token gate from signup. What happens is users are being redirected to a content page inside a workspace, which does a 2nd redirect to the token gate. I am fine with that, it is a good separation of concerns IMO as you could already be logged in and we still need that logic. The only thing I'm going to be doing is skipping the redirect if it's to a non-workspace page

2022-10-10 21:17 UTC, mattcasey commented on pages/index.tsx
> +    if (typeof router.query.returnUrl === 'string' && (!hasCompletedSignUp || isSpaceDomain(router.query.returnUrl))) {
ya i hate how this is written... if the user is being redirected, and they have not completed signup OR if this redirect is to an existing workspace, then redirect them. I think maybe i can change the order of conditions to make it more readable

2022-10-10 21:23 UTC, mattcasey commented on pages/index.tsx
>      else if (defaultWorkspace === '/nexus') {
i'm going to address this in a separate PR, but @motechFR and I thought 'defaultWorkspace' should be namespaced to the user

2022-10-11 04:55 UTC, 0xepicode approved these changes
Thx for clarifications!

2022-10-11 07:34 UTC, msadura approved these changes

2022-10-11 13:23 UTC, merged