Show member directory onboarding form on joining workspace
charmverse/app.charmverse.io pull request #1117
Opened 2022-10-23 15:48 UTC by Devorein

2022-10-24 07:08 UTC, msadura reviewed
1) Onboarding modal appears only when I join workspace with existing user. When I create a new user and join it does not work
2) Product wise, I do not think that attacking user with some sort of modal form with any description what is this can be called "onboarding". I will bring this up on discord.

2022-10-24 14:27 UTC, mattcasey commented on components/members/MemberPropertiesOnBoardingModal.tsx
> +function MemberPropertiesOnBoardingForm ({ memberId, spaceId, onClose }: { onClose: () => void, spaceId: string, memberId: string }) {
I think it would be good to memoize this, since it appears on all pages. Or don't render it at all until the modal is open (you would check if isOpen is true before embedding the component)

2022-10-24 14:28 UTC, mattcasey commented on components/common/TokenGateForm/JoinDynamicSpaceForm.tsx
> +    router.push(`/${joinedSpace.domain}?onboarding=true`);
Can you avoid using URL to pass 'state'. ?onbarding=true is not really part of navigation, it's just saying 'show the user a modal'. It seems like this var could be handled inside of a hook or using localStorage even.

2022-10-25 10:52 UTC, Devorein commented on pages/_app.tsx
> +                                <MemberPropertiesOnBoardingModal />
Updated thnx.

2022-10-27 06:55 UTC, msadura requested changes

2022-10-27 06:55 UTC, msadura commented on components/_app/GlobalComponents.tsx
> +  const { onboarding } = useOnboarding();
please use proper naming for booleans. should be `isOnboardingOpen` or basically name that you can clearly understand it is a boolean value. `onboarding` is too broad.

2022-10-27 06:55 UTC, msadura commented on components/members/MemberPropertiesOnBoardingModal.tsx
> +function MemberPropertiesOnBoardingForm ({ user, spaceId, onClose }: { onClose: () => void, spaceId: string, user: LoggedInUser }) {
I am not sure what is the reason for splitting those 2 components `MemberPropertiesOnBoardingForm` and `MemberPropertiesOnBoardingModal` but if you need them separately please have them in 2 separate files. Having multiple components in 1 file is just getting too confusing

2022-10-27 06:55 UTC, msadura commented on components/members/MemberPropertiesOnBoardingModal.tsx
> +    <Modal size='large' open={true} onClose={onClose}>
This feels like a hack. MemberProperty form is based on modal already, but you wrap it in another modal instance. 
Maybe `MemberPropertiesPopupForm` should be refactored and `MemberPropertiesForm` (without popup) extracted to separate component and reused in both places

2022-10-27 06:55 UTC, msadura commented on components/profile/components/SpacesMemberDetails/components/MemberPropertiesPopupForm.tsx
> +        {showUserDetailsForm && user && (
This is just conceptually wrong. Since this is member properties form, why would you like more things to it and add more props and conditions. As I mentioned in previous comment - lets make properties form just a component to reuse, then you can reuse it in "onboarding modal" and user details will also belong to onboarding modal.

2022-10-27 06:55 UTC, msadura commented on components/members/MemberPropertiesOnBoardingModal.tsx
> +import { usePopupState } from 'material-ui-popup-state/hooks';
I believe onboarding is one word so file names should be `...OnboardingModal.tsx`, especially that useOnboardind uses this convention

2022-10-27 06:55 UTC, msadura commented on components/_app/GlobalComponents.tsx
> +      {onboarding && <MemberPropertiesOnBoardingModal />}
This is jut container component for other global components, so it should not have logic and checking if onboarding is opened should go to `MemberPropertiesOnBoardingModal` (just render null there if it is not opened)

`{onboarding && <MemberPropertiesOnBoardingModal />}`

2022-10-27 07:07 UTC, msadura commented on components/members/MemberPropertiesOnBoardingModal.tsx
> +import { usePopupState } from 'material-ui-popup-state/hooks';
ah and this is actually `MemberOnboardingModal` since it is not only related to properties

2022-10-27 14:51 UTC, Devorein commented on components/members/MemberPropertiesOnBoardingModal.tsx
> +function MemberPropertiesOnBoardingForm ({ user, spaceId, onClose }: { onClose: () => void, spaceId: string, user: LoggedInUser }) {
`MemberPropertiesOnBoardingForm` was separated from its parent component as inside we are using `useMemberPropertyValues` hook which requires `userId` to be present. I kept them in the same module since they are quite small at the moment, but I will move them to separate modules :D

2022-10-27 14:52 UTC, Devorein commented on components/members/MemberPropertiesOnBoardingModal.tsx
> +    <Modal size='large' open={true} onClose={onClose}>
Yep. This was updated. Thank you. It caused a ghost modal to appear behind the onboarding form, now its been removed.

2022-10-27 14:53 UTC, Devorein commented on components/_app/GlobalComponents.tsx
> +      {onboarding && <MemberPropertiesOnBoardingModal />}
Agreed. I will make the changes.

2022-10-27 14:59 UTC, Devorein commented on components/members/MemberPropertiesOnBoardingModal.tsx
> +import { usePopupState } from 'material-ui-popup-state/hooks';
Yes I agree `MemberOnboardingModal` is better

2022-10-27 15:03 UTC, Devorein commented on components/_app/GlobalComponents.tsx
> +  const { onboarding } = useOnboarding();
I had to change things a bit and updated it to be an object not just a `bool`. Now its containing the structure 

`onboarding-<userId>`: {
	[spaceId]: boolean
}

2022-10-27 15:44 UTC, Devorein commented on components/profile/components/SpacesMemberDetails/components/MemberPropertiesPopupForm.tsx
> +        {showUserDetailsForm && user && (
Its was slightly tricky to move them in separate components as everything had to be placed inside a Dialog. I've used `children` prop instead

2022-10-28 08:55 UTC, msadura requested changes

2022-10-28 08:55 UTC, msadura commented on components/profile/components/UserDetails/SocialIcons.tsx
> +      {social && (
I believe you do not need to check `social &&` on each item, but you can check it once and do not render any of them

2022-10-28 08:55 UTC, msadura commented on components/members/MemberPropertiesOnBoardingModal.tsx
> +export function MemberPropertiesOnBoardingModal () {
MemberPropertiesOnBoardingModal -> MemberPropertiesOnboardingModal + change filename

2022-10-28 08:55 UTC, msadura commented on components/members/MemberPropertiesOnBoardingModal.tsx
> +export function MemberPropertiesOnBoardingModal () {
ps. why not simply member onboarding modal?

2022-10-28 08:55 UTC, msadura commented on components/members/MemberPropertiesOnBoardingModal.tsx
> +  const memberDirectoryFormModal = usePopupState({ variant: 'popover', popupId: 'member-directory-onboarding' });
this is not used and can be removed

2022-10-28 08:55 UTC, msadura commented on components/members/MemberPropertiesOnBoardingModal.tsx
> +  if (!onboarding[space.id]) {
you can squeeze both conditions this into 1:

`!user || !onboarding[space?.id]`

2022-10-28 09:39 UTC, Devorein commented on components/profile/components/UserDetails/SocialIcons.tsx
> +      {social && (
Updated thank you. The reason I had to have them for each media was because Alex said to show those icons even when they are not connected. I replaced `social && social.twitterURL` with `social?.twitterURL`

2022-10-28 09:40 UTC, Devorein commented on components/members/MemberPropertiesOnBoardingModal.tsx
> +export function MemberPropertiesOnBoardingModal () {
Lets go with that

2022-10-28 09:43 UTC, Devorein commented on components/members/MemberPropertiesOnBoardingModal.tsx
> +  const memberDirectoryFormModal = usePopupState({ variant: 'popover', popupId: 'member-directory-onboarding' });
Nice catch. Thank you :D

2022-10-28 09:44 UTC, Devorein commented on components/members/MemberPropertiesOnBoardingModal.tsx
> +  if (!onboarding[space.id]) {
Updated

2022-10-28 12:21 UTC, merged