open wallet if user tries to create a tg without a wallet connect
charmverse/app.charmverse.io pull request #1130
Opened 2022-10-25 13:44 UTC by Devorein

2022-10-26 03:44 UTC, mattcasey requested changes
I tested and it connects, but the Lit token gate modal should pop up after I have connected my wallet, since the action I clicked on was "Add a token gate". I think you could add a new state variable:
```
Component () {
  ...
  const [clickedAddTokenGate, setClickedAddTokenGate] = useState(false);
  
  useEffect(() => {
    if (account && clickedAddTokenGate) {
      handleTokenGate();
      setClickedAddTokenGate(false);
    }
  , [account, clickedAddTokenGate]);

  return (...
        <MenuItem
          onClick={(e) => {
            if (account) {
                handleTokenGate(e);  
            }
            else {
              openWalletSelectorModal();
              setClickedAddTokenGate(true);
            }
          }}
        />
   ...);
}

```

2022-10-26 08:52 UTC, msadura commented
> I tested and it connects, but the Lit token gate modal should pop up after I have connected my wallet, since the action I clicked on was "Add a token gate". I think you could do something like this:
> 
> ```
> Component () {
>   ...
>   const [clickEvent, setClickEvent] = useState(null);
>   
>   useEffect(() => {
>     if (account && clickEvent) {
>       handleTokenGate(clickEvent);
>       setClickEvent(null);
>     }
>   , [account, clickEvent]);
> 
>   return (...
>         <MenuItem
>           onClick={(e) => {
>             if (account) {
>                 handleTokenGate(e);  
>             }
>             else {
>               openWalletSelectorModal();
>               setClickEvent(e);
>             }
>           }}
>         />
>    ...);
> }
> ```

this will work, but I am wondering - why handleTokenGate needs event itself? It is kinda weird to put DOM event in state and reuse it later on

2022-10-26 08:56 UTC, msadura commented on components/settings/invites/components/InviteLinks/components/InviteActions.tsx
> +          onClick={(e) => {
we should try to avoid creating functions with logic directly in JSX / handlers. Please move declaration to the top and just use declared function here

2022-10-26 13:59 UTC, Devorein commented
> I tested and it connects, but the Lit token gate modal should pop up after I have connected my wallet, since the action I clicked on was "Add a token gate". I think you could do something like this:
> 
> ```
> Component () {
>   ...
>   const [clickEvent, setClickEvent] = useState(null);
>   
>   useEffect(() => {
>     if (account && clickEvent) {
>       handleTokenGate(clickEvent);
>       setClickEvent(null);
>     }
>   , [account, clickEvent]);
> 
>   return (...
>         <MenuItem
>           onClick={(e) => {
>             if (account) {
>                 handleTokenGate(e);  
>             }
>             else {
>               openWalletSelectorModal();
>               setClickEvent(e);
>             }
>           }}
>         />
>    ...);
> }
> ```

Unfortunately that doesn't work as the whole react component is unmounted after switching the wallet and the state is thus lost. Maybe we use a query parameter or a value in the localstorage?

2022-11-03 08:29 UTC, msadura commented
Unfortunatelly connecting wallet causes remounting the whole app. Because of that I needed a way to tell if there is a pending action (modal to be opened) and save it in local storage. I ended up having a hook for it.

2022-11-08 16:27 UTC, mattcasey approved these changes

2022-11-08 16:27 UTC, mattcasey commented on hooks/usePendingLocalAction.ts
> +export function usePendingLocalAction (actionKey: string, validityTime = 5000) {
this might come in handy in other places

2022-11-08 16:30 UTC, mattcasey approved these changes

2022-11-08 17:48 UTC, merged