Add timezone for member directory
charmverse/app.charmverse.io pull request #1147
Opened 2022-10-27 10:08 UTC by Devorein

2022-10-27 10:50 UTC, msadura requested changes

2022-10-27 10:50 UTC, msadura commented on components/members/components/MemberDirectoryGalleryView.tsx
> +            <Typography variant='body2'>{member.profile?.timezone ? convertTZ(member.profile.timezone) : 'N/A'}</Typography>
this logic of displaying timezone is repeated in 3 places. I think It would be better to have `<TimezoneDisplay />` component that would pick timezone and default value and it would run `convertTZ` logic on its own

2022-10-27 10:50 UTC, msadura commented on components/profile/components/TimezoneModal.tsx
> +const getTimeZoneOptions = () => {
move it to separate util function

2022-10-27 10:50 UTC, msadura commented on package.json
> +    "moment-timezone": "^0.5.38",
This is a no-go for me. Moment is legacy and deprecated solution. From what I see we use something called luxon - TBH I would rather go with something widely used like date fns, but anyway luxon seem to have support for timezones as well https://github.com/moment/luxon/blob/master/docs/zones.md

2022-10-27 10:50 UTC, msadura commented on components/profile/components/TimezoneModal.tsx
> +      setTimezone({
this logic is called 3 times. You can create helper function like setInitialTimezone and reuse it

2022-10-27 10:50 UTC, msadura commented on components/profile/components/TimezoneModal.tsx
> +          <Autocomplete<Timezone>
I think this autocomplete deserves its own method

2022-10-27 14:17 UTC, mattcasey commented
![image](https://user-images.githubusercontent.com/305398/198310313-bcb4b86a-4871-4807-a736-adff88bcc844.png)

- Set up is two words
![image](https://user-images.githubusercontent.com/305398/198310563-b325d0e8-d29b-4c28-a3a0-3248fcfe62e2.png)
- this is the timezone display, i dont know what this means. we should just use America/Denver (the value of timezone) which the user selects from the dropdown

2022-10-27 14:18 UTC, mattcasey commented on lib/utilities/browser.ts
> +export function convertTZ (tzString: string) {
just show the timezone, I'm not sure what this is doing.. getting the current time?

2022-10-27 14:20 UTC, mattcasey commented on components/profile/components/TimezoneModal.tsx
> +export default function TimezoneModal ({
we're supposed to stop using default exports

2022-10-27 14:21 UTC, mattcasey commented on package.json
> +    "moment-timezone": "^0.5.38",
I agree, even if the timezone component uses it internally, we may not be using the same version always and we might want to just replace it in the future. Looks like we're just using it to calculate the offset

2022-10-27 14:22 UTC, mattcasey commented
It would be nice if, during onboarding, we selected your current timezone as default

2022-10-28 04:21 UTC, Devorein commented on package.json
> +    "moment-timezone": "^0.5.38",
Agreed. I will use `Intl.supportedValuesOf('timeZone')` as Matt suggested.

2022-10-28 04:25 UTC, Devorein commented on package.json
> +    "moment-timezone": "^0.5.38",
I will go with `luxon` as its only available in the latest versions of chrome and ff.
![image](https://user-images.githubusercontent.com/34683631/198502166-7921da7f-83b3-4f31-916a-81184206d12e.png)

2022-10-28 04:36 UTC, Devorein commented on package.json
> +    "moment-timezone": "^0.5.38",
Luxon doesn't provide the db of all the tz, I had to rely on another package to do so. https://github.com/moment/luxon/issues/353#issuecomment-514203601

2022-10-28 04:56 UTC, Devorein commented on components/profile/components/TimezoneModal.tsx
> +      setTimezone({
Updated thank you.

2022-10-28 05:01 UTC, Devorein commented on components/profile/components/TimezoneModal.tsx
> +          <Autocomplete<Timezone>
Agree. I've created a new component `TimezoneAutocomplete` for re-use purpose

2022-10-28 05:22 UTC, Devorein commented on components/profile/components/TimezoneModal.tsx
> +export default function TimezoneModal ({
It used default since we had to lazy load the component. I can remove it, now that we don't use `moment-timezone` anymore

2022-10-28 05:23 UTC, Devorein commented on lib/utilities/browser.ts
> +export function convertTZ (tzString: string) {
Removed this function and opted for an inline version with correct date formatting

2022-10-28 05:27 UTC, Devorein commented
1. Will tackle that one in the onboarding PR
2. It was too much hassle trying to get the styling correct, and it was using no specific class so the styling had to rely on position of children. And the code was extremely small, its just MUI autocomplete with moment-tz tz's.
3. That is only in the latest browsers. Opted for another [package](https://bundlephobia.com/package/tzdata@1.0.34)

2022-10-28 05:52 UTC, Devorein commented on components/profile/components/TimezoneModal.tsx
> +const getTimeZoneOptions = () => {
Updated

2022-10-28 09:08 UTC, msadura commented on components/members/components/TimezoneDisplay.tsx
> +    <>
it would be safer to wrap this into Stack rather than fragment - currently depending on parent it might endy up as a row or as a col

2022-10-28 09:11 UTC, msadura commented on components/profile/components/TimezoneAutocomplete.tsx
> +  const timezoneOptions = useMemo(() => getTimezonesWithOffset(), []);
getTimezonesWithOffset are not react-dependent so you can move timezoneOptions above component declaration and you will not need memoization

2022-10-28 09:39 UTC, msadura commented on lib/utilities/dates.ts
> +  return `${padToTwoDigits(hours)}:${padToTwoDigits(minutes, false)}`;
actually luxon support `Duration` object which you can use for formatting without introducing weird custom pad method:

```
const hours = Duration.fromObject({ hours: totalMinutes / 60 }).toFormat("hh");
const minutes = Duration.fromObject({ minutes: totalMinutes % 60 }).toFormat("mm");
return `${hours}:${minutes}`);
```

2022-10-28 09:47 UTC, msadura requested changes
just a few cosmetic changes

2022-10-28 10:57 UTC, Devorein commented on components/members/components/TimezoneDisplay.tsx
> +    <>
Good point. Updated.

2022-10-28 11:24 UTC, merged