Add sort to Member Directory views
charmverse/app.charmverse.io pull request #1153
Opened 2022-10-28 17:07 UTC by Devorein

2022-10-28 20:16 UTC, msadura requested changes

2022-10-28 20:16 UTC, msadura commented on components/members/components/MemberDirectorySort.tsx
> +          properties.filter(property => !property.type.match(/role|profile_pic/)).sort((propA, propB) => propA.name > propB.name ? -1 : 1)
Please do not use regexp matchers for types because you are basically loosing type checking. You should instead check `property.type !== 'role'  && property.type !== 'profile_pic' ` or `!['profile_pic', 'role'].includes(property.type)`

additionally please assign this computation above jsx to const for better readability.

2022-10-28 20:16 UTC, msadura commented on components/members/MemberDirectoryPage.tsx
> +function sortMembers (members: Member[], property: MemberProperty) {
please move it outside of this file

2022-10-28 20:22 UTC, msadura commented
Having empty sort select looks weird, don't we have some kind of default sort? Or there should be some placeholder.

<img width="166" alt="Screenshot 2022-10-28 at 22 20 36" src="https://user-images.githubusercontent.com/5198394/198725249-4343549c-a46c-4bd6-be28-635badefba78.png">

Additionally "sort" font is different than on proposal, it is tiny thing but we should keep ui consistent:
<img width="433" alt="Screenshot 2022-10-28 at 22 20 15" src="https://user-images.githubusercontent.com/5198394/198725616-b77d63b9-d307-495d-b6ec-76b743da016c.png">

2022-10-28 20:23 UTC, msadura commented
Extra additional point - it would be nice to have property type icons in this dropdown:
<img width="192" alt="Screenshot 2022-10-28 at 22 22 49" src="https://user-images.githubusercontent.com/5198394/198725789-59eeac36-3c05-48ee-962c-724664e5ea08.png">

2022-10-29 09:21 UTC, Devorein commented on components/members/components/MemberDirectorySort.tsx
> +          properties.filter(property => !property.type.match(/role|profile_pic/)).sort((propA, propB) => propA.name > propB.name ? -1 : 1)
Agree. Updated

2022-10-30 19:05 UTC, msadura commented on components/common/ViewOptions.tsx
> +export const StyledViewOptions = styled.div`
Styling MUI with classes like this is just a hack. I like the idea of exporting this component to be reusable but correct way would be to make it like this (pseudo-code like):

```
export function ViewOption({ children, label })
    <Stack display="row" gap={1} //any needed styling>
      <InputLabel>{label}</InputLabel> // with proper font styling
      <>
         {children}
      </>
   </Stack>
 ```

this way we will be able to reuse it in all the places we need

2022-10-31 14:22 UTC, Devorein commented on components/common/ViewOptions.tsx
> +export const StyledViewOptions = styled.div`
Nice one. Updating

2022-11-01 12:17 UTC, merged