Fixed resyncing gnosis safes
charmverse/app.charmverse.io pull request #1155
Opened 2022-10-30 17:13 UTC by Devorein

Fix for [this](https://discord.com/channels/894960387743698944/950861057398833212/1036220214964138004) bug reported by Alex

2022-10-30 19:21 UTC, msadura requested changes

2022-10-30 19:21 UTC, msadura commented on lib/gnosis/gnosis.ts
> +  const safes = await Promise.all(Object.values(RPC).filter(network => network.chainId !== 4).map(network => {
Please avoid using this sort of magic numbers in code. I can understand it only because I was and issue on discord, otherwise it would be just confusing.

1) create `getGnosisConnectors` method
2) It should have an array of keys from `RPC` const supported by gnosis. 
3) Based on that return proper array of connectors for gnosis. If you want to just filter RPC view chainId at east explain that in comment.
4) Ps. There is `RPCList` in connectors which provides array of connectors

2022-10-31 08:23 UTC, mattcasey commented on lib/gnosis/gnosis.ts
> +  const safes = await Promise.all(Object.values(RPC).filter(network => network.chainId !== 4).map(network => {
Actually, let's just remove rinkeby

2022-10-31 14:05 UTC, Devorein commented on lib/gnosis/gnosis.ts
> +  const safes = await Promise.all(Object.values(RPC).filter(network => network.chainId !== 4).map(network => {
Updating

2022-10-31 14:30 UTC, mattcasey approved these changes

2022-11-01 13:27 UTC, merged