Member directory properties reorder
charmverse/app.charmverse.io pull request #1158
Opened 2022-10-31 14:06 UTC by Devorein

2022-11-01 20:32 UTC, mattcasey commented on components/members/components/MemberDirectoryProperties/MemberPropertiesSidebar.tsx
> +      let _isAdjacent = true;
Looks like you copied a bunch of code from TreeNode but you're not using it. You can instead just add `isOver: monitor.isOver()` to the collection in useDrag().

The background of 'isAdjacent': in the sidebar, we give the appearance that you are dragging between items, so we want to ignore the hover unless you are within 5px of the top of the row (and we show a little blue div over the top edge). One thing we don't support yet is dragging to the bottom of the last item. I am fine if we just do what you have now but I think you should take out all the logic related to 'isAdjacent'.

2022-11-01 20:32 UTC, mattcasey commented on components/members/components/MemberDirectoryProperties/MemberPropertiesSidebar.tsx
> +      let _isAdjacent = true;
There's a lot of good examples here https://react-dnd.github.io/react-dnd/examples btw

2022-11-01 20:32 UTC, mattcasey requested changes
see comments

2022-11-03 10:11 UTC, msadura commented
1) When I try to drag something it looks like dragging 3items:
<img width="277" alt="Screenshot 2022-11-03 at 10 57 39" src="https://user-images.githubusercontent.com/5198394/199694746-18815e92-a80e-4299-8c13-ee20a4e62d37.png">

2) Currently discovering drag&drop is rather a matter of coincidence by the user. I think we should follow notion and display draggable icon on hover:
<img width="517" alt="Screenshot 2022-11-03 at 11 08 56" src="https://user-images.githubusercontent.com/5198394/199694911-7eaa3f6f-f777-47ce-8797-87c9371f3f52.png">

2022-11-05 13:53 UTC, Devorein commented on components/common/PageLayout/components/PageNavigation/components/TreeNode.tsx
> +export function mergeRefs (refs: any) {
Updated

2022-11-05 14:59 UTC, Devorein commented on components/members/components/MemberDirectoryProperties/MemberPropertiesSidebar.tsx
> +        await updateProperty({
Fixed logic to update index of all affected properties

2022-11-05 18:05 UTC, mattcasey requested changes
Please make sure properties are being sorted on the gallery cards. Doesn't seem to change at the moment, but they do get sorted on the table view!

2022-11-05 18:07 UTC, mattcasey commented on lib/members/generateDefaultPropertiesInput.ts
> +  return defaultPropertiesInput.sort((propA, propB) => propA.name > propB.name ? 1 : -1).map((property, index) => ({ ...property, index }));
we shouldn't sort by name if we are sorting by index

2022-11-05 18:11 UTC, mattcasey commented on lib/members/updateMemberProperty.ts
> +    }) as MemberProperty;
It's dangerous to use a type assertion to hide a possible null value. You can use findUniqueOrThrow, then we would get a useful error and no type assertion necessary

2022-11-05 18:14 UTC, mattcasey commented on lib/members/updateMemberProperty.ts
> +    transactions.push(prisma.memberProperty.updateMany({
the new indexing logic should be handled on the frontend. There's no guarantee that the current state of indexes matches what's in the frontend, especially if multiple users happen to be trying to change order the same time, or if someone has a bad network connection.
I think it deserves its own API route.. just send back a list of indexes for all member properties, like we do for the page tree?

2022-11-05 18:25 UTC, mattcasey commented on lib/members/updateMemberProperty.ts
> +          lte: newIndex as number
please try to avoid using type assertions

2022-11-05 18:32 UTC, mattcasey commented on lib/members/updateMemberProperty.ts
>      data: { ...data, updatedBy: userId, id }
we should be setting updatedAt as well

2022-11-07 10:27 UTC, Devorein commented on lib/members/generateDefaultPropertiesInput.ts
> +  return defaultPropertiesInput.sort((propA, propB) => propA.name > propB.name ? 1 : -1).map((property, index) => ({ ...property, index }));
The default properties are sorted by their name first and that alphabetical sort order also becomes their index. This line was necessary as there were two properties with the same index, but I've updated it

2022-11-07 10:29 UTC, Devorein commented on lib/members/updateMemberProperty.ts
> +    }) as MemberProperty;
Updated

2022-11-07 10:41 UTC, Devorein commented on lib/members/updateMemberProperty.ts
>      data: { ...data, updatedBy: userId, id }
`@updatedAt` attribute in `schema.prisma` should take care of that, its been added for the `MemberProperty` model

2022-11-07 10:41 UTC, Devorein commented on lib/members/updateMemberProperty.ts
> +          lte: newIndex as number
Updated

2022-11-08 16:29 UTC, Devorein commented on lib/members/updateMemberProperty.ts
> +    transactions.push(prisma.memberProperty.updateMany({
Added a few unit tests to make sure its working as expected.

2022-11-08 16:49 UTC, mattcasey commented on jest.config.ts
> +    path.join(__dirname, '**/lib/**/*.spec.ts')
why is this needed

2022-11-11 06:22 UTC, merged