Marketing analytics
charmverse/app.charmverse.io pull request #1161
Opened 2022-10-31 19:37 UTC by motechFR

Final todo: Send track page from public page in a way that it doesn't create duplicates

Need to test bounty and proposals, to see if they send this.

Main issue is we don't use the same CharmEditor in public and internal mode

2022-11-01 21:32 UTC, mattcasey commented on pages/api/profile/index.ts
> +  await req.session.save();
can you avoid this call if anonymouseUserId was not set? this call is called all the time, we should avoid extra async ops that are unecesssary

2022-11-01 21:33 UTC, mattcasey commented on marketing-site/analytics.html
> +<!--
please add a README to this folder explaining what the folder is for

2022-11-01 21:35 UTC, mattcasey commented on hooks/useUserAcquisition.ts
> +      setCookie('appCampaign' as SignupCookieType, currentCampaign, {
please use setCookie/getCOokie from our utils in lib/utilities/browser - no need to add a new npm dependency

2022-11-01 21:38 UTC, mattcasey commented on lib/metrics/mixpanel/utils-signup.ts
> +
all files should use camelCase

2022-11-01 21:39 UTC, mattcasey commented on charmClient/apis/trackApi.ts
> +    return http.POST<{ success: 'ok' | 'ignored' }>(`/api/events?event=${event}`, payload);
the backend never returns 'ignored'?

2022-11-01 21:44 UTC, mattcasey commented on pages/api/profile/index.ts
> +    deleteCookie(cookie, {
we have a pattern for handling cookies already on the backend
```
import Cookies from 'cookies';
....
const cookies = new Cookies(req, res);
...
cookies.set(cookie, null);
````

2022-11-01 21:47 UTC, mattcasey commented on hooks/useUserAcquisition.ts
> +    if (currentPage) {
when would currentPage be undefined? seems impossible

2022-11-01 21:48 UTC, mattcasey commented on pages/index.tsx
> +  useEffect(() => {
this function needs to run on ever page, not just if users hit the domain w/no path (pages/index.tsx). I believe you just have to put this in app.tsx instead

2022-11-01 21:50 UTC, mattcasey requested changes
see comments

2022-11-02 13:58 UTC, motechFR commented on marketing-site/analytics.html
> +<!--
yep, done

2022-11-02 14:03 UTC, motechFR commented on hooks/useUserAcquisition.ts
> +      setCookie('appCampaign' as SignupCookieType, currentCampaign, {
Gotcha, will know for future!

2022-11-02 14:07 UTC, motechFR commented on charmClient/apis/trackApi.ts
> +    return http.POST<{ success: 'ok' | 'ignored' }>(`/api/events?event=${event}`, payload);
Yep! Fair point

2022-11-02 14:09 UTC, motechFR commented on pages/api/profile/index.ts
> +    deleteCookie(cookie, {
Gotcha, will know in future

2022-11-02 14:13 UTC, motechFR commented on hooks/useUserAcquisition.ts
> +    if (currentPage) {
I was going along with patter for other setters here, but you're right. Removed this :)

2022-11-02 14:13 UTC, motechFR commented on pages/index.tsx
> +  useEffect(() => {
Done!

2022-11-02 17:36 UTC, mattcasey approved these changes

2022-11-02 18:13 UTC, merged