Member directory property visibility
charmverse/app.charmverse.io pull request #1170
Opened 2022-11-02 11:01 UTC by Devorein

2022-11-02 18:12 UTC, mattcasey commented on prisma/schema.prisma
> +  @@unique([view, memberPropertyId])
(in case we keep this table) Looks like you need to add a migration for this constraint. When i test locally and run `prisma migrate dev`, prisma is asking me to generate a migration file.

2022-11-02 18:12 UTC, mattcasey commented on components/common/BoardEditor/focalboard/src/widgets/icons/table.tsx
> +  const theme = useTheme();
Suggestion: 'currentColor' means the color can be defined by the parent element. There's no need to set it manually here, and you'll be able to use this pattern with any icon. For example, using the Typography component "should work" this way:
```
  <Typography component='span' color={disabled ? 'secondary' : 'inherit'}>
    <GalleryIcon />
  </Typography>
```
Theoretically you shouldn't have to change anything inside this icon component, and the solution would work for any svg icon we use.

2022-11-02 18:12 UTC, mattcasey commented on components/members/components/MemberDirectoryGalleryView.tsx
> +  const isNameHidden = nameProperty?.memberPropertyVisibilities.find(pv => pv.view === 'gallery');
.some() is a bit better than .find() when you just want a boolean return

2022-11-02 18:12 UTC, mattcasey commented on components/members/components/MemberDirectoryGalleryView.tsx
> +            const hiddenInGallery = property.memberPropertyVisibilities.find(propertyVisibility => propertyVisibility.view === 'gallery');
if this was just a list, the logic would be simplified:
```

2022-11-02 18:23 UTC, mattcasey commented on prisma/schema.prisma
> +  table
we should also include and support 'profile'

2022-11-02 18:25 UTC, mattcasey commented on components/members/components/MemberDirectoryProperties/MemberPropertiesSidebar.tsx
> +            <Tooltip title={`Property is ${disabledInGalleryView ? 'invisible' : 'visible'} in gallery view`}>
The menu has gotten really crowded, I think this should go on its own row, at the top of the collapsible section. On the left it could say "View visibility?" We also need a 3rd icon for 'profile' view.

![image](https://user-images.githubusercontent.com/305398/199571710-d2116301-a800-45c9-a188-ee3c3fad02e6.png)

2022-11-02 18:26 UTC, mattcasey requested changes
Functionally, it's working well. I left some comments and think we should just have a column of strings rather than a whole new table

2022-11-04 11:14 UTC, Devorein commented on prisma/schema.prisma
> +  memberPropertyVisibilities MemberPropertyVisibility[]
I've replaced the table with `enabledViews` property in `MemberProperty`

2022-11-04 11:14 UTC, Devorein commented on prisma/schema.prisma
> +  @@unique([view, memberPropertyId])
Not required, since the table was removed

2022-11-04 11:19 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/widgets/icons/table.tsx
> +  const theme = useTheme();
Thanks, tried and it works. I will keep that in mind from now on

2022-11-04 11:20 UTC, Devorein commented on components/members/components/MemberDirectoryGalleryView.tsx
> +  const isNameHidden = nameProperty?.memberPropertyVisibilities.find(pv => pv.view === 'gallery');
Its a lot easier now since the table has been removed its been replaced with the following
`const isNameHidden = !nameProperty?.enabledViews.includes('gallery')`

2022-11-04 11:21 UTC, Devorein commented on components/members/components/MemberDirectoryGalleryView.tsx
> +            const hiddenInGallery = property.memberPropertyVisibilities.find(propertyVisibility => propertyVisibility.view === 'gallery');
Updated thnx for the suggestion :D

2022-11-04 11:21 UTC, Devorein commented on prisma/schema.prisma
> +  table
Yes added to the enum and also made sure its functionally working

2022-11-04 11:57 UTC, Devorein commented on components/members/components/MemberDirectoryProperties/MemberPropertiesSidebar.tsx
> +            <Tooltip title={`Property is ${disabledInGalleryView ? 'invisible' : 'visible'} in gallery view`}>
Updated

2022-11-04 13:33 UTC, merged