Remove padding for embedded boards
charmverse/app.charmverse.io pull request #1209
Opened 2022-11-11 14:13 UTC by valentinludu

Padding was added for all boards and we don't need it for boards embedded in pages or other places.

2022-11-13 12:58 UTC, Devorein approved these changes

2022-11-13 12:59 UTC, Devorein commented
Probably a bit more padding would be helpful
![image](https://user-images.githubusercontent.com/34683631/201522859-ce6706c5-7864-4c2c-8247-5db386c99def.png)

2022-11-13 16:08 UTC, mattcasey commented on components/common/BoardEditor/focalboard/src/components/centerPanel.scss
> +        padding-bottom: 5px;
instead of adding a new rule, please just fix the original CSS to be more specific. Less is always more :)

For example, you can use "full-page" class to specify padding-bottom only on full page databases in centerPanel.scss.

2022-11-13 16:13 UTC, mattcasey commented
> Probably a bit more padding would be helpful
No component should add extra whitespace around itself. This breaks the vertical rhythm of components, and is really dependent on the content you are using.

2022-11-13 16:16 UTC, mattcasey requested changes
please fix the specificity of the original CSS rule, rather than adding an override

2022-11-14 10:00 UTC, valentinludu commented
> Probably a bit more padding would be helpful ![image](https://user-images.githubusercontent.com/34683631/201522859-ce6706c5-7864-4c2c-8247-5db386c99def.png)

Following Matt's comment I will remove padding and leave the user to add empty lines as spaces if he/she wishes to.

2022-11-14 10:31 UTC, valentinludu commented on components/common/BoardEditor/focalboard/src/components/centerPanel.scss
> +        padding-bottom: 5px;
Done.

2022-11-14 17:03 UTC, msadura approved these changes

2022-11-14 17:13 UTC, mattcasey approved these changes

2022-11-14 17:14 UTC, Devorein approved these changes

2022-11-14 17:15 UTC, merged