Member directory immutable join date property
charmverse/app.charmverse.io pull request #1215
Opened 2022-11-13 10:27 UTC by Devorein

2022-11-13 10:58 UTC, msadura requested changes

2022-11-13 10:58 UTC, msadura commented on components/members/components/MemberDirectoryGalleryView.tsx
> +                case 'join_date': {
why type of data is called "join_date" ? I believe data type should be just `date` and in case of "join_date" field it should be just filled with a join date on the backed side. This way we can have universal data type we can reuse in the future.

2022-11-13 10:58 UTC, msadura commented on lib/members/getSpacesPropertyValues.ts
> +    const joinDatesMap = await getSpaceMemberJoinDates({ spaceIds, memberId });
This logic adds new db query, which opersates on the same data as `getSpaceMemberRoles` above. I think it would be betters to make a common way on adding roles and join dates when needed, but based on 1 query which would fetch data once and jusrt reuse that data to add roles and (or) join dates

2022-11-13 14:26 UTC, Devorein commented on lib/members/getSpacesPropertyValues.ts
> +    const joinDatesMap = await getSpaceMemberJoinDates({ spaceIds, memberId });
Agree. I've updated the code so that its all done in a single query. Also made sure all the tests pass.

2022-11-13 14:29 UTC, Devorein commented on components/members/components/MemberDirectoryGalleryView.tsx
> +                case 'join_date': {
Most of the read only properties are actually joined on the frontend, for example, `name, discord, twitter, timezone` etc🤔

2022-11-13 16:20 UTC, mattcasey commented on lib/members/constants.ts
> +  'timezone',
@Devorein this "DEFAULT_MEMBER_PROPERTIES_ORDER" is unecessary, why can't we just use the order that's in the map?

2022-11-13 16:22 UTC, Devorein commented on lib/members/constants.ts
> +  'timezone',
The order in the map is not guaranteed to be in the same order they are defined right? That was the only reason.

2022-11-13 16:25 UTC, mattcasey commented on lib/members/getSpaceMemberJoinDates.ts
> +   {} as Record<string, Date>
Using generics is the correct way to type reduce:
```
const result = array.reduce<Record<string, Date>>(reduceFunction, {});

```

2022-11-13 16:26 UTC, mattcasey commented on scripts/addJoinDateMemberDirectoryProperty.ts
> +      createdBy: space.createdBy,
what will the sort order of this be? won't it suddenly appear at the top since it will be -1?

2022-11-15 06:04 UTC, msadura approved these changes

2022-11-16 15:16 UTC, Devorein commented on scripts/addJoinDateMemberDirectoryProperty.ts
> +      createdBy: space.createdBy,
Thnx for catching that. I will add the index when creating the join_date property

2022-11-16 18:15 UTC, mattcasey approved these changes

2022-11-16 19:59 UTC, merged