Feat/select options editable by members
charmverse/app.charmverse.io pull request #1231
Opened 2022-11-16 13:23 UTC by msadura

https://app.charmverse.io/charmverse/page-3557311048353411

2022-11-16 13:35 UTC, Devorein requested changes

2022-11-16 13:35 UTC, Devorein commented on jest.config-server.ts
> +    // '**/lib/**/*.spec.ts'
Yikes we need to uncomment this 👀

2022-11-16 13:35 UTC, Devorein commented on lib/members/updateMemberProperty.ts
> +    throw new InvalidInputError('Invalid workspace data.');
If the user is not a member of the workspace its better to throw `UserIsNotSpaceMemberError`
![image](https://user-images.githubusercontent.com/34683631/202194410-e21771d1-64ba-4d9f-b06b-811af5b33e4f.png)

2022-11-16 13:36 UTC, msadura commented on jest.config-server.ts
> +    // '**/lib/**/*.spec.ts'
actually it was commented all the time, I just uncommented this in my previous pr by mistake

2022-11-16 13:44 UTC, Devorein approved these changes

2022-11-16 15:25 UTC, mattcasey commented on jest.config-server.ts
> +    // '**/lib/**/*.spec.ts'
I think I asked this once before, can we just remove this line?

2022-11-17 07:04 UTC, msadura commented on jest.config-server.ts
> +    // '**/lib/**/*.spec.ts'
We can probably remove it, but I do not see other way to run `libs/...` tests via vscode jest runner extension. Maybe I am just missing some piece of the puzzle.

2022-11-17 07:04 UTC, merged