Adding/editing categories for forum
charmverse/app.charmverse.io pull request #1298
Opened 2022-12-01 15:26 UTC by Devorein

2022-12-02 12:17 UTC, msadura commented
I tried to test this, but when I visit forum as an admin I get:
<img width="996" alt="Screenshot 2022-12-02 at 13 15 56" src="https://user-images.githubusercontent.com/5198394/205291254-846e8137-3809-415b-9db2-57c8df2caf46.png">

2022-12-02 12:18 UTC, msadura commented
<img width="1000" alt="Screenshot 2022-12-02 at 13 18 05" src="https://user-images.githubusercontent.com/5198394/205291327-3ac2b001-166f-4df2-ac7b-08267db1debe.png">

2022-12-03 08:27 UTC, Devorein commented
Both the above occurred due to color type mismatch. I've disabled colors for categories for now so it should be working as expected.

2022-12-05 09:51 UTC, msadura commented
> Both the above occurred due to color type mismatch. I've disabled colors for categories for now so it should be working as expected.

does it mean colors are not in a scope of post category? Or it was not discussed

2022-12-05 10:24 UTC, msadura requested changes
2 small UI improvements:
1) When you edit category it would be nice to close popover on enter
2) There should be some sort of "ellipsis" in category name:
<img width="233" alt="Screenshot 2022-12-05 at 11 11 25" src="https://user-images.githubusercontent.com/5198394/205613942-9bba7b33-db02-4bde-a607-e533247bfb47.png">

2022-12-05 10:24 UTC, msadura commented on hooks/useForumFilters.ts
> +        ...(isValidCategory && {
I don't quite get what this does? Won't 1st query get override by the 2nd spread?

2022-12-05 10:24 UTC, msadura commented on hooks/useForumFilters.ts
> +  const handleClick = (value: string) => {
"handleClick" is quite misleading here. It should be "applyFilters" or something like that

2022-12-05 10:24 UTC, msadura commented on components/forum/components/Filters/FilterList.tsx
> +  async function createForumCategory() {
those helper methods like "createForumCategory" fits more into `useForumFilters` than component

2022-12-05 10:24 UTC, msadura commented on components/forum/components/Filters/FilterList.tsx
> +      refetchForumCategories();
is there a reason to blindly refetch all the categories from the server rather than mutate cache locally?

2022-12-05 15:18 UTC, Devorein commented on hooks/useForumFilters.ts
> +        ...(isValidCategory && {
Right. Don't remember touching that file up until now but will fix it 💯

2022-12-05 15:28 UTC, Devorein commented on components/forum/components/Filters/FilterList.tsx
> +  async function createForumCategory() {
I think having a hook link `useForumCategories` would be better. `useForumFilters` shouldn't need to deal with categories imo🤔

2022-12-05 16:01 UTC, Devorein commented on components/forum/components/Filters/FilterList.tsx
> +      refetchForumCategories();
Normally for smaller data we refetch the data, but I agree we should always try to update the cache when possible. I've made the changes required 🥳

2022-12-07 10:26 UTC, msadura commented on components/forum/components/Filters/FilterList.tsx
> +  async function createForumCategory() {
yeah that is true, additional `useForumCategories` would be the best. As far as I understand posts are "filtered" by categories and this is why they landed in this hook in the first place, but it will be getting more and more confusing

2022-12-08 21:49 UTC, mattcasey commented on components/common/Icons/hoverIconsStyle.ts
> +    marginForIcons = true
this should be false by default (see the other prop is false by default).. but it also seems like something that could be handled by the parent component instead. This style mixin should just handle hover effects and not layout

2022-12-08 22:04 UTC, mattcasey commented on components/common/Link.tsx
> +    <StyledMuiLink href={href as string} color={color} rel='noreferrer' underline='none' {...restProps}>
this type assertion is not necessary. it should throw an error instead

2022-12-08 22:14 UTC, mattcasey commented on components/forum/ForumPage.tsx
> +  }, [router.query.categoryIds]);
This code is confusing... it's just using categoryId to set categoryId?

2022-12-08 22:15 UTC, mattcasey commented on components/forum/components/Filters/FilterCategory.tsx
> +import DeleteOutlinedIcon from '@mui/icons-material/DeleteOutlined';
there is no "Filters" component, please put these all inside components

2022-12-08 22:21 UTC, mattcasey commented on components/forum/components/Filters/FilterList.tsx
> +  if (!currentSpace) {
doesn't look like currentSpace is a requirement to show the UI. But also, I think you could use router.query.domain instead which is immediately available.

2022-12-08 22:22 UTC, mattcasey commented on components/forum/components/Filters/FilterList.tsx
> +        sx={{
`px` is a prop of `CardContent`.. no need to use `sx` which is slightly slower to render

2022-12-08 22:25 UTC, mattcasey commented on components/forum/components/Filters/FilterList.tsx
> +          sx={{
add 'size=small'?

2022-12-08 22:26 UTC, mattcasey commented on components/forum/components/Filters/FilterList.tsx
> +              <MenuItem
add 'dense'

2022-12-08 22:26 UTC, mattcasey commented on components/forum/components/Filters/FilterList.tsx
> +          sx={{
add autoFocus={true}

2022-12-08 22:30 UTC, mattcasey commented on hooks/useForumCategories.ts
> +  const { mutateForumCategories } = useForumFilters();
these methods are only used in one place, and 'useForumCategories' doesnt actually supply the categories. I think we should either:
A) move the methods into useForumFilters()
B) move the methods into the hook component

2022-12-08 22:33 UTC, mattcasey commented on hooks/useForumFilters.ts
> +        ...(isValidCategory && {
instead of having 'applyFilters' check category and sort list, just make the query the input:
`applyFilters({ sort: value })`

2022-12-08 22:34 UTC, mattcasey commented on hooks/useForumFilters.ts
> +        ...(isValidCategory && {
Hm it doesn't look like  we are using applyFilters anywhere?

2022-12-08 22:36 UTC, mattcasey commented on lib/forums/categories/createPostCategory.ts
> +      color: categoryColor
please completely remove color from categories - that's not part of the product design

2022-12-08 22:36 UTC, mattcasey requested changes
see comments

2022-12-09 09:53 UTC, Devorein commented on components/forum/ForumPage.tsx
> +  }, [router.query.categoryIds]);
Thanks. I overlooked that one. We can already get `categoryIds` from the router state, there was no need to store it in a separate state.

2022-12-09 10:45 UTC, Devorein commented on hooks/useForumCategories.ts
> +  const { mutateForumCategories } = useForumFilters();
I went with B since `useForumFilters` depends on `useForumCategories` for the `categories`. Refrained from C as we might need to use those api methods later on

2022-12-09 11:11 UTC, Devorein commented on components/common/Icons/hoverIconsStyle.ts
> +    marginForIcons = true
I've created a [Task Card](https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=1d9b3860-9345-4ad1-9780-54e6f4a0795a) and assigned myself. Will take care of it as part of quick followup

2022-12-09 11:54 UTC, merged