Add voting UI and endpoints for posts
charmverse/app.charmverse.io pull request #1312
Opened 2022-12-04 16:16 UTC by Devorein

2022-12-05 13:52 UTC, msadura requested changes

2022-12-05 13:52 UTC, msadura commented on components/forum/components/ForumPost/PostVote.tsx
> +    setPosts((postPages) => {
This logis feels to be in wrong place. This is component for single post so it should not do any operations using `setPosts`.  It should rather receive `updatePost` method, or `upvotePostVote` method and it should do all of the logic in a higher component.

2022-12-05 13:52 UTC, msadura commented on lib/forums/posts/voteForumPost.ts
> +    await prisma.pageUpDownVote.delete({
`pageUpDownVote` - upDown vote? 😅  Why not just `PageVote`

2022-12-05 13:52 UTC, msadura commented on lib/forums/posts/interfaces.ts
> +export type ForumPostPageVote = { upvotes: number; downvotes: number; upvoted?: boolean };
I do not understand this logic - you store upvodtes, downvotes and `upvoted` - what about `downvoted` ?

2022-12-05 13:52 UTC, msadura commented on pages/api/forums/posts/[postId]/vote.ts
> +  const post = await prisma.post.findUnique({
plase move logic from controller to  functoin in `lib/` dir

2022-12-05 13:52 UTC, msadura commented on lib/forums/posts/interfaces.ts
> +export type ForumPostPageVote = { upvotes: number; downvotes: number; upvoted?: boolean };
maybe something like action: 'upvote' | 'downvote' would be more clear

2022-12-06 14:09 UTC, Devorein commented on .vscode/settings.json
> +    "downvotes",
Its from an extension that checks whether the spelling of a word is correct or not 😛 
I will remove this one as well as the other one I added by accident

2022-12-06 14:21 UTC, Devorein commented on lib/forums/posts/voteForumPost.ts
> +    await prisma.pageUpDownVote.delete({
Yeah I was a bit confused about that as well (P.S I didn't create the prisma schema 😛)
Probably `PostVote` would've been best, but since its already in prod, I think we have to keep it as is

2022-12-07 10:23 UTC, msadura commented on lib/forums/posts/interfaces.ts
> +export type ForumPostPageVote = { upvotes: number; downvotes: number; upvoted?: boolean };
so you can cast a vote without casing a vote? It does not make sense. Additionally logic above is clear because you described it to me but it is not intuitive at all.

2022-12-07 13:53 UTC, Devorein commented on lib/forums/posts/interfaces.ts
> +export type ForumPostPageVote = { upvotes: number; downvotes: number; upvoted?: boolean };
Yeah I agree with that, but not sure how else I could've wrote it. Also this is not for casting a vote, its to show whether you've voted on a post or not. We delete the vote on be if `upvoted === undefined`

2022-12-08 22:52 UTC, mattcasey commented on lib/forums/posts/voteForumPost.ts
> +  postId: string;
** always use pageId, not postId **

2022-12-08 22:54 UTC, mattcasey commented on lib/forums/posts/voteForumPost.ts
> +    await prisma.pageUpDownVote.delete({
> since its already in prod, I think we have to keep it as is
Definitely not. we have not released this to customers yet

2022-12-08 22:59 UTC, mattcasey commented on lib/forums/posts/voteForumPost.ts
> +  const page = await prisma.page.findUnique({
i don't think this method should query the vote state. Can't the UI figure it out on its own?

2022-12-08 23:07 UTC, mattcasey commented on lib/forums/posts/listForumPosts.ts
> +          downvotes: upDownVotes.filter((vote) => !vote.upvoted).length,
instead of returning downvotes and upvotes to the frontend, i think it would be better to just do the math here and return 'voteCount' or something

2022-12-08 23:09 UTC, mattcasey commented on components/forum/components/ForumPost/ForumPost.tsx
> +                    ...forumPostPageVote,
so here, just add or subtract 1 based on `upvoted`

2022-12-08 23:10 UTC, mattcasey commented on components/forum/components/ForumPost/ForumPost.tsx
> +            cursor: postPages.cursor,
its probably better to do `...postPages` in case we add something else to the interface in the future, instead of setting cursor and hasNext, etc..

2022-12-08 23:13 UTC, mattcasey requested changes
see comments

2022-12-09 11:50 UTC, Devorein commented on lib/forums/posts/voteForumPost.ts
> +  const page = await prisma.page.findUnique({
Thats a very good point. I totally overlook that part but it was getting quite difficult to update it on the frontend. In most of the cases we update the cache based on the mutation response but this is definitely a rare case and needs a different approach

2022-12-09 12:29 UTC, merged