Notify users in realtime for a new post
charmverse/app.charmverse.io pull request #1315
Opened 2022-12-05 13:21 UTC by Devorein

[Task Card](https://app.charmverse.io/charmverse/page-49366552253645923?viewId=d15c9b90-8918-44da-bbd8-db8712faa723&cardId=fffaec65-404b-4848-9395-4a1ecce7cdcb)

![image](https://user-images.githubusercontent.com/34683631/205647426-59b408bc-70af-4057-b432-36d2fd82498a.png)

2022-12-08 22:38 UTC, mattcasey commented on components/forum/components/ForumPosts/ForumPosts.tsx
> +      <Box ref={createPostBoxRef}>
you could just use 'div' here

2022-12-08 22:39 UTC, mattcasey requested changes
needs to not use snackbar

2022-12-08 22:43 UTC, mattcasey commented on hooks/useSnackbar.tsx
> +    setOrigin({
what happens when snackbar is used again? won't the origin be incorrect?
I think this feature is better off not using snackbar.. the utility is intended for quick messages in the bottom-left, which we use in a lot of places. whereas the 'new posts' option is very specific

2022-12-08 22:44 UTC, mattcasey requested changes
I think this feature is better off not using the global snackbar.. the utility is intended for quick messages in the bottom-left, which we use in a lot of places. whereas the 'new posts' option is a very specific UI component. (once you start adding lots of configuration props, overrides, etc. to a component it's a sign that it may be better to just build a custom one)

Also... looks like we were not creating posts originally until this PR? That needs to be fixed, and we need a "Publish" button too

2022-12-08 22:45 UTC, mattcasey commented on lib/websockets/interfaces.ts
> +  payload: Post & { page: Page | null };
i don't think this event needs any payload, definitely not all the page content, etc.

2022-12-08 22:48 UTC, mattcasey commented on pages/api/pages/index.ts
> +        relay.broadcast(
this event should only be triggered when a post is published

2022-12-09 12:32 UTC, Devorein commented on hooks/useSnackbar.tsx
> +    setOrigin({
Not if its the origin is updated beforehand. But I agree this is not the safest approach.

2022-12-13 15:48 UTC, mattcasey approved these changes

2022-12-13 16:03 UTC, merged