Sshrayber group nft
charmverse/app.charmverse.io pull request #1334
Opened 2022-12-12 04:08 UTC by HagiaSofiya

2022-12-12 04:11 UTC, HagiaSofiya commented
<img width="1116" alt="Screenshot 2022-12-11 at 11 09 51 PM" src="https://user-images.githubusercontent.com/5186937/206958980-76902047-feab-4414-bf80-80bbeb94e48d.png">

2022-12-12 08:59 UTC, msadura requested changes

2022-12-12 08:59 UTC, msadura commented on components/profile/PublicProfile.tsx
> +      return { ...prev, [groupKey]: group };
please always avoid using spreading obejcts in reduce https://prateeksurana.me/blog/why-using-object-spread-with-reduce-bad-idea/

```
acc[groupKey] = group;
return acc;
```

should do the job here

2022-12-12 09:16 UTC, msadura commented
UI-wise I would make less verical sapcing between groups

2022-12-12 18:20 UTC, mattcasey approved these changes
Approved but agree with Marek's request - can you remove the spread inside reduce? Thanks!

2022-12-12 18:22 UTC, HagiaSofiya commented on components/profile/PublicProfile.tsx
> +      return { ...prev, [groupKey]: group };
@msadura Thank you for the article! I am not following the change you are asking for.  Would you mind sending me a sample?

2022-12-13 06:53 UTC, msadura commented on components/profile/PublicProfile.tsx
> +      return { ...prev, [groupKey]: group };
sure:

```
  function groupBy<T>(arr: T[], fn: (item: T) => any) {
    return arr.reduce<Record<string, T[]>>((acc, curr) => {
      const groupKey = fn(curr);
      const group = prev[groupKey] || [];
      group.push(curr);
      
      acc[groupKey] = group;
      return acc;
    }, {});
 ```

2022-12-13 06:54 UTC, msadura approved these changes

2023-01-02 15:22 UTC, mattcasey commented
we decided to nix this design for now, and the dev working on it has disappeared

2023-01-02 15:22 UTC, closed without merging