Add category title to the main forum page if category is selected
charmverse/app.charmverse.io pull request #1382
Opened 2022-12-22 14:05 UTC by valentinludu

https://app.charmverse.io/charmverse/page-8704528490535499

2022-12-22 19:52 UTC, mattcasey commented on hooks/useForumCategories.ts
> +  const router = useRouter();
This has bit us in the past (putting state into a data source hook) I think we should use a different hook if you want to capture the 'current category'.

2022-12-22 19:59 UTC, mattcasey requested changes
remove the logic to determine current category from the useForumCategories hook. it won't always be defined by the URL, i think its safer to just let components maintain that logic

2022-12-23 07:58 UTC, valentinludu commented on hooks/useForumCategories.ts
> +  const router = useRouter();
OK. Then I will keep it as before. Outside, each component will determine how it gets the id.

2022-12-23 07:58 UTC, valentinludu commented
> remove the logic to determine current category from the useForumCategories hook. it won't always be defined by the URL, i think its safer to just let components maintain that logic

Done

2023-01-02 15:38 UTC, mattcasey approved these changes

2023-01-02 16:28 UTC, merged