Feat/sort forum posts
charmverse/app.charmverse.io pull request #1388
Opened 2022-12-23 16:42 UTC by valentinludu

2023-01-02 18:32 UTC, mattcasey commented on components/forum/components/PostList/PostList.tsx
> +  if (item === 'newest' || item === 'most_voted' || item === 'most_commented') {
Wouldn't this logic be better on the backend? I think it's better to blow up than try to coerce/fake the value. This code looks like it will hide bugs. This should be simple enough:
```
if (!SORT_TYPES.includes(sortType)) {
  throw new Error('Invalid sort type')
  }

```
And we should use a type union anywhere we set the sort so that there will be less bugs (`type SortType = 'newest' | 'most_voted' | 'most_commented')

2023-01-02 18:40 UTC, mattcasey commented on lib/forums/posts/listForumPosts.ts
> +export type SortPosts = 'newest' | 'most_commented' | 'most_voted';
a better way to write this:
```
export const PostOrderOptions = ['newest', 'most_commented', 'most_voted'] as const;
export type PostOrder = typeof PostOrderOptions[number];
```
I'm not sure if you still need `as const`, but this allows us to have the best of both worlds: an array you can check at runtime and a type union for compile time

2023-01-02 18:41 UTC, mattcasey requested changes
Nothing blocking really, but I think the type/list of sorts could be written in a more robust way, and I suggest throw an error on invalid input instead of coercing the sort to a proper value

2023-01-02 18:42 UTC, mattcasey commented on components/forum/ForumPage.tsx
> +  const sort = router.query.sort as string | undefined;
could use the type 'SortPosts' here

2023-01-03 11:03 UTC, valentinludu commented on components/forum/components/PostList/PostList.tsx
> +  if (item === 'newest' || item === 'most_voted' || item === 'most_commented') {
I added the default newest just in listForumPosts()

2023-01-03 11:05 UTC, valentinludu commented on components/forum/components/PostList/PostList.tsx
> +  if (item === 'newest' || item === 'most_voted' || item === 'most_commented') {
If I throw an error that means the user will see that error message and an empty list.
I think it's a better user experience if we show latest posts(default) without the error.

The categoryId behaves the same. If you enter an invalid categoryId, it's like you didn't entered anything.

2023-01-03 11:08 UTC, valentinludu commented on components/forum/components/PostList/PostList.tsx
> +  if (item === 'newest' || item === 'most_voted' || item === 'most_commented') {
<img width="812" alt="Screenshot 2023-01-03 at 13 07 39" src="https://user-images.githubusercontent.com/25636858/210345803-9ee8f8b4-b69c-4df6-88d6-85f9302d4483.png">

2023-01-03 16:59 UTC, mattcasey approved these changes

2023-01-03 17:01 UTC, valentinludu commented on components/forum/components/PostList/PostList.tsx
> +  if (item === 'newest' || item === 'most_voted' || item === 'most_commented') {
Decided to show the error!

2023-01-03 17:02 UTC, merged