fixed workspace onboarding modal appearing multiple times
charmverse/app.charmverse.io pull request #1399
Opened 2022-12-27 11:01 UTC by Devorein

2022-12-27 11:46 UTC, msadura commented on prisma/schema.prisma
> +  workspaceOnboard WorkspaceOnboard[]
any reason for creating separate table and relation instead of simply storing `onboarded` boolean column directly in `SpaceRole` ? Feels like having separate table for single property is a bit overkill

2022-12-27 11:56 UTC, msadura requested changes

2022-12-27 11:56 UTC, msadura commented on charmClient/apis/workspaceOnboardingApi.ts
> +    return http.GET<boolean>(`/api/spaces/${spaceId}/get-onboarding`);
``/api/spaces/${spaceId}/onboarding``

2022-12-27 11:56 UTC, msadura commented on hooks/useOnboarding.tsx
> +    user && currentSpace ? `onboarding-${user.id}-${currentSpace.id}` : null,
I believe we namespace keys using `/` everythere else like `onboarding/${user.id}/${currentSpace.id}`

2022-12-27 11:56 UTC, msadura commented on hooks/useOnboarding.tsx
> +          if (_onboarding) {
I htink simple `(_onboarding) => _onboarding` will do the same

2022-12-27 11:56 UTC, msadura commented on lib/token-gates/applyTokenGates.ts
> +    await prisma.workspaceOnboard.create({
after seeing this logic copy-pasted all over the place I would suggest having this as spaceRole column instead of overcomplicating thing this much.

2022-12-27 11:57 UTC, msadura commented on pages/api/spaces/[id]/get-onboarding.ts
> +import type { NextApiRequest, NextApiResponse } from 'next';
We agreed some time ago to avoid using filenames-like-this. Additionally we never use `get` suffix for `GET` endpoints, so simply `onboarding.ts` will be enough

2022-12-27 13:19 UTC, motechFR commented on lib/token-gates/applyTokenGates.ts
> +    await prisma.workspaceOnboard.create({
I agree with this, especially since the only relevant data in this model is onboarded: true

2022-12-27 13:20 UTC, motechFR commented on charmClient/apis/workspaceOnboardingApi.ts
> +    return http.GET<boolean>(`/api/spaces/${spaceId}/get-onboarding`);
If we move workspaceOnboard to a spaceRole prop, we can skip the API lookup and look directly at the spaceroles of the LoggedInUser interface

2022-12-27 13:23 UTC, msadura commented on charmClient/apis/workspaceOnboardingApi.ts
> +    return http.GET<boolean>(`/api/spaces/${spaceId}/get-onboarding`);
oh loving that even more!

2022-12-27 15:26 UTC, mattcasey commented on prisma/schema.prisma
> +model WorkspaceOnboard {
I think this might be able to have other data in the future, maybe just "UserSpaceInfo"

2022-12-27 15:26 UTC, mattcasey commented on prisma/schema.prisma
> +model WorkspaceOnboard {
@Devorein and everyone: we should just use "space" in our names, not "workspace". product has actually determined to stop using 'workspace' as well

2022-12-27 15:27 UTC, mattcasey commented on prisma/schema.prisma
> +  workspaceOnboard WorkspaceOnboard[]
the thought was that this is unrelated to permissioning, and we might have more fields int he future. permissions need to be fast - and possibly stored in the permissions api eventually - so it seemed better to keep it separate

2022-12-27 15:29 UTC, mattcasey requested changes
rename 'workspaceonboarding' to 'userspaceinfo' or something a little more generic

2022-12-27 15:30 UTC, mattcasey commented on hooks/useOnboarding.tsx
> +          if (_onboarding) {
or even `Boolean`

2022-12-28 14:30 UTC, Devorein commented on prisma/schema.prisma
> +  workspaceOnboard WorkspaceOnboard[]
After discussion we've decided to keep the property inside `SpaceRole` table

2022-12-28 14:34 UTC, Devorein commented on hooks/useOnboarding.tsx
> +    user && currentSpace ? `onboarding-${user.id}-${currentSpace.id}` : null,
Since we are moving to use spaceRole we won't need this anymore

2022-12-28 14:37 UTC, Devorein commented on prisma/schema.prisma
> +model WorkspaceOnboard {
Sheesh I totally forgot. Thanks!!!

2022-12-28 18:47 UTC, mattcasey approved these changes

2022-12-28 21:32 UTC, merged