Integrate iframely into embeds and create /bookmark
charmverse/app.charmverse.io pull request #1437
Opened 2023-01-08 11:25 UTC by Devorein

2023-01-08 17:11 UTC, mattcasey commented on components/common/CharmEditor/components/iframe/config.ts
> +  airtable: {
this is duplicated from above?

2023-01-08 17:12 UTC, mattcasey commented on components/common/CharmEditor/components/bookmark/bookmarkNodeView.tsx
> +import BookmarkIcon from '@mui/icons-material/Bookmark';
capitalize the filename plz

2023-01-08 17:12 UTC, mattcasey commented on components/common/CharmEditor/components/bookmark/bookmarkNodeView.tsx
> +import fetch from 'adapters/http/fetch.server';
should not be importing server-side fetch

2023-01-08 17:12 UTC, mattcasey commented on components/common/CharmEditor/components/bookmark/bookmarkNodeView.tsx
> +      const iframelyResponse = await fetch<{ html: string; error?: string }>(
this should probably just be added to charmClient

2023-01-08 17:14 UTC, mattcasey commented on components/common/CharmEditor/components/bookmark/bookmarkNodeView.tsx
> +      <MediaSelectionPopup
thanks for using this component this time :)

2023-01-08 17:15 UTC, mattcasey commented on components/common/CharmEditor/components/bookmark/bookmarkNodeView.tsx
> +    } catch (err) {
if we arent doing anything w/catch, then don't use try/catch. that way we can see the errors

2023-01-08 17:16 UTC, mattcasey commented on components/common/CharmEditor/components/bookmark/bookmarkNodeView.tsx
> +          <MediaUrlInput onSubmit={updateNode} placeholder='https://dune.com/skateordao/Gnars' />
please use a placeholder that is fake

2023-01-08 17:18 UTC, mattcasey commented on components/common/CharmEditor/components/bookmark/bookmarkNodeView.tsx
> +      const iframelyResponse = await fetch<{ html: string; error?: string }>(
it also seems like you should just watch the bookmarkUrl attribute and call the API?

2023-01-08 17:21 UTC, mattcasey commented on components/common/CharmEditor/components/bookmark/bookmarkSpec.ts
> +        return ['div.charm-bookmark'];
make sure to include all node attributes when creating the DOM. it's required so that copy/paste works properly

2023-01-08 17:22 UTC, mattcasey commented on components/common/CharmEditor/components/bookmark/bookmarkSpec.ts
> +      toMarkdown: () => null
we should at least include the url that was embedded

2023-01-08 17:22 UTC, mattcasey commented on components/common/CharmEditor/components/bookmark/index.ts
> +export * from './bookmarkPlugins';
let's not use index.ts files for components anymore. That was something our team agreed on

2023-01-08 17:25 UTC, mattcasey commented on components/common/CharmEditor/components/bookmark/bookmarkNodeView.tsx
> +  const { url, html } = node.attrs as BookmarkViewerProps;
component needs to look for the 'tooltip-marker' mark so that the input opens automatically

2023-01-08 17:55 UTC, mattcasey requested changes
left a bunch of comments... please delpoy to staging to test the env var is set correctly. and whose api key are we using? do i have access?

2023-01-09 13:16 UTC, Devorein commented on components/common/CharmEditor/components/iframe/config.ts
> +  airtable: {
I don't even know how it got here 🤦🏼‍♂️

2023-01-09 13:34 UTC, Devorein commented on components/common/CharmEditor/components/bookmark/bookmarkNodeView.tsx
> +import fetch from 'adapters/http/fetch.server';
Thank you. I had to omit the credentials as otherwise iframely threw CORS error

2023-01-09 13:35 UTC, Devorein commented on components/common/CharmEditor/components/bookmark/bookmarkNodeView.tsx
> +      const iframelyResponse = await fetch<{ html: string; error?: string }>(
Lets do that 🚀

2023-01-09 13:54 UTC, Devorein commented on components/common/CharmEditor/components/bookmark/bookmarkNodeView.tsx
> +    } catch (err) {
Since I've moved everything to charmClient its not going to throw an error anymore

2023-01-09 13:55 UTC, Devorein commented on components/common/CharmEditor/components/bookmark/bookmarkSpec.ts
> +        return ['div.charm-bookmark'];
right I added a todo for it but forgot to complete it. Thanks.

2023-01-09 14:20 UTC, Devorein commented on components/common/CharmEditor/components/bookmark/bookmarkNodeView.tsx
> +  const { url, html } = node.attrs as BookmarkViewerProps;
Actually `MediaSelectionPopup` automatically does that for you

2023-01-09 15:21 UTC, mattcasey commented on components/common/CharmEditor/components/bookmark/bookmarkNodeView.tsx
> +import fetch from 'adapters/http/fetch.server';
I forgot about the CORS thing, but thanks for making that work

2023-01-09 17:09 UTC, mattcasey approved these changes

2023-01-09 18:33 UTC, merged