Create nested page from palette
charmverse/app.charmverse.io pull request #144
Opened 2022-02-27 17:41 UTC by Devorein

2022-02-28 13:53 UTC, motechFR approved these changes

2022-02-28 19:55 UTC, mattcasey commented on hooks/useNestedPage.ts
> +import { Fragment } from '@bangle.dev/pm';
this file does not look like a react hook to me - it doesn't import or export any state. i think it's another good reason to create a new folder in lib/pages where you could just export `addNestedPage`

2022-02-28 19:58 UTC, mattcasey commented on hooks/useMenu.ts
> +  const [anchorEl, setAnchorEl] = React.useState<null | HTMLElement>(null);
This hook is already provided by material-ui-popup-state. There's a `bindMenu` prop you should check out: https://www.npmjs.com/package/material-ui-popup-state#usepopupstate. I prefer we use a single way to do things, and I really have been liking this package which you introduced. I don't think we need a second wrapper

2022-02-28 20:09 UTC, mattcasey commented on hooks/usePages.tsx
> +type AddPageFn = (space?: Space, page?: Partial<Page>, shouldRoute?: boolean) => Promise<Page>;
Couple comments about this function interface:
1) we should prefer named arguments, a la: `({ space, page, shouldRoute })`. My most basic reason is that from the callsite its impossible to know what this means: `addPage(undefined, undefined, true);` without inspecting the types with an IDE. But it's also more work to add and remove properties without doing large refactors, especially for a utility method
2) 'spaceId' is already an attribute allowed on Page, so it seems unecessary to even offer passing in a 'space' except that this method also lets you redirect to the page. I'd be fine if that was handled elsewhere, and then this method can literally just accept one required input: `page`. How about adding a 2nd method to wrap this one: `addPageAndRedirect(page);` That method could import both `useRouter` and `useSpace` so i dont even have to pass in the space.

2022-02-28 20:17 UTC, mattcasey commented on components/editor/Editor.tsx
> +                <Emoji sx={{ fontSize: 60 }}>{page.icon}</Emoji>
78 is intentional and based on Notion's UI. Please revert it back?

2022-02-28 20:18 UTC, mattcasey commented on components/editor/@bangle.io/js-lib/inline-palette/hooks.ts
> +        return await (item.editorExecuteCommand({
i'm not sure why adding async and await is needed here, when editorExecuteCommand already returns a promise?

2022-02-28 20:21 UTC, mattcasey commented on components/editor/@bangle.io/extensions/inline-command-palette/use-editor-items.tsx
> +      icon: <svg viewBox="0 0 32 32" height="1em" width="1em" className="page" style={{ transform: "scale(1.25)", fill: 'currentColor', flexShrink: 0, backfaceVisibility: 'hidden'}}><g> <path d="M16,
1) SVGs should not be pasted inline, they should be kept with other assets and media in the public folder
2) if you are going to use a new page icon, please update the one we use in the sidebar. right now they look different (i'm also fine if u just use mui's icon for now):
![image](https://user-images.githubusercontent.com/305398/156053082-1666178b-e663-4a8d-ae09-2a85fad80c05.png)

2022-02-28 20:22 UTC, mattcasey commented on components/editor/@bangle.io/extensions/inline-command-palette/InlineCommandPalette.tsx
> +    // editorItems,
why is this commented out? should we just delete it?

2022-02-28 20:23 UTC, mattcasey commented on components/editor/NestedPage.tsx
> +        onClick={() => {
can't we just use a Nextjs link here and not import router?

2022-02-28 20:24 UTC, mattcasey commented on components/editor/NestedPage.tsx
> +        <svg viewBox='0 0 32 32' height='1em' width='1em' className='page' style={{ transform: 'scale(1.25)', fill: 'currentColor', flexShrink: 0, backfaceVisibility: 'hidden' }}>
please put svg where in the public folder... looks like this may be duplicated from the other line

2022-02-28 20:27 UTC, mattcasey commented on components/editor/NestedPage.tsx
> +        {nestedPage?.title ? nestedPage.title : 'Untitled'}
On Firefox, it looks like title is being squished for some reason: 
![image](https://user-images.githubusercontent.com/305398/156053842-cb898ae8-1e20-40c1-afa0-02abd0723125.png)

2022-02-28 20:28 UTC, mattcasey requested changes
left comments

2022-02-28 20:29 UTC, mattcasey commented on components/editor/NestedPage.tsx
> +      <Box
just another note.. you can just use a div span if you want. The reason to use Box is to have access to all the custom MUI properties like `sx`, but for the most part i don't see you using those. Having less CSS/MUI stuff should help rendering be faster, and make it easier to copy and paste from our editor to someplace else

2022-02-28 21:03 UTC, mattcasey commented on components/editor/NestedPage.tsx
> +          <ListItemIcon><DeleteIcon fontSize='small' /></ListItemIcon>
for some reason this doesn't actually do anything for me

2022-02-28 21:04 UTC, mattcasey commented on components/editor/NestedPage.tsx
> +            console.log(view, getPos());
console.log.. did you forget to add an action?

2022-03-01 14:05 UTC, Devorein commented on hooks/usePages.tsx
> +    const pageProperties: Prisma.PageCreateInput = {
Yeah, sure that works. But let's do that in a separate PR if possible.

2022-03-01 14:07 UTC, Devorein commented on hooks/useNestedPage.ts
> +import { Fragment } from '@bangle.dev/pm';
Agreed. I will create a new PR with all the refactorings

2022-03-01 14:10 UTC, Devorein commented on components/editor/NestedPage.tsx
> +            console.log(view, getPos());
My bad I was about to complete the delete action but forgot to remove the console logs. I will remove it once I'm done adding the delete functionality

2022-03-01 14:16 UTC, Devorein commented on hooks/usePages.tsx
> +type AddPageFn = (space?: Space, page?: Partial<Page>, shouldRoute?: boolean) => Promise<Page>;
1. Agreed. I was honestly confused when I used `addPage(undefined` in one instance. I will switch to named arguments asap.
2. That's a great idea. My only concern is that what if we want to create a page in a separate space. It might not have that good of a use case, but could be important under certain circumstances. Regarding the `addpageAndRedirect` function I can do that. I will place it under `usePages` hook as all the other hooks (`useCurrentSpace`, `useRouter`) are already used there.

2022-03-01 14:18 UTC, Devorein commented on components/editor/Editor.tsx
> +                <Emoji sx={{ fontSize: 60 }}>{page.icon}</Emoji>
But it actually overflows the icon. Let me show you a sample.
This is with 78 size
![image](https://user-images.githubusercontent.com/34683631/156185604-647386c3-faca-487b-b600-47223ebba1f3.png)
This is with 60 size
![image](https://user-images.githubusercontent.com/34683631/156185666-d95bf3c7-64d0-4860-b3bd-475a4ee15810.png)

2022-03-01 14:27 UTC, Devorein commented on components/editor/@bangle.io/extensions/inline-command-palette/InlineCommandPalette.tsx
> +    // editorItems,
Hmm, this caused an infinite loop as the editor items rather than being static object, is being dynamically calculated inside a hook. So the `useEffect` was being called recursively. I actually tried to fix it but couldn't go far. But I think it's best to fix it to avoid rerenders, I will need to check it out again. Adding a TODO comment on top to fix it after completing all the required tasks.

2022-03-01 14:29 UTC, Devorein commented on components/editor/NestedPage.tsx
> +        onClick={() => {
Good point. It will help out on SEO. I will see where else I've referenced useRouter and replace those with `next/link`

2022-03-01 14:29 UTC, Devorein commented on components/editor/NestedPage.tsx
> +        <svg viewBox='0 0 32 32' height='1em' width='1em' className='page' style={{ transform: 'scale(1.25)', fill: 'currentColor', flexShrink: 0, backfaceVisibility: 'hidden' }}>
Yep you're right I will replace it will Mui/Icon's appropriate icon component

2022-03-01 14:31 UTC, Devorein commented on components/editor/NestedPage.tsx
> +      <Box
Good point. I will see where I can replace Box with regular span or divs

2022-03-01 14:34 UTC, Devorein commented on hooks/useMenu.ts
> +  const [anchorEl, setAnchorEl] = React.useState<null | HTMLElement>(null);
I totally forgot about that package. I guess its becoming a bit hard to keep track of our dependencies as the codebase grows larger

2022-03-01 15:52 UTC, mattcasey commented on components/editor/Editor.tsx
> +                <Emoji sx={{ fontSize: 60 }}>{page.icon}</Emoji>
remove overflow: hidden and add a z-index to page-controls

2022-03-02 08:22 UTC, merged