User friendly forum links
charmverse/app.charmverse.io pull request #1481
Opened 2023-01-12 13:24 UTC by motechFR

PR for user friendly forum links

2023-01-12 13:54 UTC, Devorein approved these changes

2023-01-16 16:49 UTC, Devorein approved these changes
Looks great. Maybe if a user is in a specific category and deletes that category we could update the url to remove the category as the category itself is switched to `All categories`

2023-01-16 16:49 UTC, Devorein commented on components/forum/components/CategoryMenu.tsx
> +          disabled={categories.find((category) => category.name === newForumCategoryName)}
We should disable empty categories from being created

2023-01-16 18:11 UTC, mattcasey requested changes
Looks good, but one thing: we should sanitize category names so that the path is all lowercase, spaces are replaced with hyphens, and special characters stripped out. For example "category / subcategory" as category results in a 404.

2023-01-17 09:30 UTC, Devorein commented
It will be quite difficult to serialize and de-serialize them. Maybe this [npm package](https://www.npmjs.com/package/friendly-url) can help.

2023-01-18 15:49 UTC, merged