Make forum breadcrumb clickable
charmverse/app.charmverse.io pull request #1525
Opened 2023-01-18 17:00 UTC by valentinludu

2023-01-19 15:30 UTC, msadura commented on components/common/PageLayout/components/Header/components/PageTitleWithBreadcrumbs.tsx
> +  const title = pageTitle === 'Forum' ? 'All Categories' : pageTitle;
is there any other way to recognize this than comparing page title? Feels a bit fragile.

2023-01-19 21:34 UTC, mattcasey commented on components/common/PageLayout/components/Header/components/PageTitleWithBreadcrumbs.tsx
> +  const title = pageTitle === 'Forum' ? 'All Categories' : pageTitle;
i think you can just leave it called "Forum" as well. It's a breadcrumb, so the title shouldn't change

2023-01-19 21:39 UTC, mattcasey requested changes
Not sure about "All categories" where the page title should go. But the more I think about it, the more it makes sense! I kind of like it on top of the feed but not where breadcrumbs appear. Was this a request by Chris/Alex or can you pass it by them?

2023-01-20 12:50 UTC, valentinludu commented
> Not sure about "All categories" where the page title should go. But the more I think about it, the more it makes sense! I kind of like it on top of the feed but not where breadcrumbs appear. Was this a request by Chris/Alex or can you pass it by them?

Chris said he is ok with: Forum/ All Categories 

<img width="917" alt="Screenshot 2023-01-20 at 10 30 13" src="https://user-images.githubusercontent.com/25636858/213698902-8d8e3e67-6a13-4dbe-9495-e36a5ca34970.png">

2023-01-20 14:35 UTC, valentinludu commented on components/common/PageLayout/components/Header/components/PageTitleWithBreadcrumbs.tsx
> +  const title = pageTitle === 'Forum' ? 'All Categories' : pageTitle;
> is there any other way to recognise this than comparing page title? Feels a bit fragile.

I improved a bit so now I am checking for the path like this: pathName === '/[domain]/forum'

2023-01-20 14:41 UTC, valentinludu commented on components/common/PageLayout/components/Header/components/PageTitleWithBreadcrumbs.tsx
> +  const title = pageTitle === 'Forum' ? 'All Categories' : pageTitle;
> This should still just say "Forum" anyway. We don't need to give the page two different titles

If I let pageTitle it will say Forum / Forum. That is why I added the All Categories string.

2023-01-20 16:19 UTC, mattcasey approved these changes

2023-01-20 16:53 UTC, merged