Forum post actions
charmverse/app.charmverse.io pull request #1604
Opened 2023-01-29 11:51 UTC by Devorein

![image](https://user-images.githubusercontent.com/34683631/215324182-17a8d4f9-a5c1-4716-8f68-8d3a3a69baca.png)

2023-01-30 15:30 UTC, mattcasey commented on pages/api/forums/posts/[postId]/convert-to-proposal.ts
> +      type: 'pages_meta_updated',
should be pages_created

2023-01-30 16:26 UTC, mattcasey commented on components/common/PageLayout/components/Header/Header.tsx
> +      const bangleEditorCoreElement = document.querySelector(`.bangle-editor-core[data-page-id="${targetPage.id}"]`);
we shouldnt have to pick a specific editor for events. i just realized we're adding listeners on every instance of charmeditor, which is really unecssary

2023-01-30 16:28 UTC, mattcasey commented on components/common/PageLayout/components/Header/Header.tsx
> +      const bangleEditorCoreElement = document.querySelector(`.bangle-editor-core[data-page-id="${targetPage.id}"]`);
we shouldn't need to add event listerens on every ReactEditor component, i would have put the listener in the EditorPage component and it could just listen to the document for events

2023-01-30 16:35 UTC, mattcasey commented on components/common/PageLayout/components/Header/Header.tsx
> +        {forumPost && postCreator && (
this is all duplicated code, please DRY it up with a standard component/function

2023-01-30 16:39 UTC, mattcasey commented on lib/pages/generateMarkdown.ts
> +    content: PageContent;
i would have just marked content as type 'any'. this change is requiring you to add type assertions on every call site which is not much better, but more boilerplate

2023-01-30 16:40 UTC, mattcasey commented on pages/api/forums/posts/[postId]/convert-to-proposal.ts
> +  if (!post) {
use findUniqueOrThrow instead of adding your own condition

2023-01-30 16:47 UTC, mattcasey commented on components/common/PageLayout/components/Header/Header.tsx
> +  const isForumPost = router.route === '/[domain]/forum/post/[pagePath]';
this feels very brittle to me, but its no less brittle than what we're doing with pages right now

2023-01-30 16:49 UTC, mattcasey requested changes
Blockers:
- use the correct websocket event
Nice-to-have:
- it would be really nice to DRY the menu and not duplicate everything
- update createProposal to do handle event tracking-related logic since it's already doing some of it
- left some other minor comments

2023-01-31 16:10 UTC, Devorein commented on pages/api/forums/posts/[postId]/convert-to-proposal.ts
> +  updateTrackPageProfile(updatedPage.id);
Skipping convert-to-proposal for forum post to reduce scope

2023-01-31 16:11 UTC, Devorein commented on pages/api/forums/posts/[postId]/convert-to-proposal.ts
> +      type: 'pages_meta_updated',
Skipping convert-to-proposal for forum post to reduce scope

2023-01-31 16:23 UTC, Devorein commented on components/common/PageLayout/components/Header/Header.tsx
> +    const isPostCreator = postCreator?.id === user?.id;
`postCreator` variable is used later on for displaying the last edited by information

2023-01-31 16:47 UTC, Devorein commented on pages/api/forums/posts/[postId]/convert-to-proposal.ts
> +  if (!post) {
We are throwing a custom error if I'm not mistaken, but skipping convert-to-proposal for forum post to reduce scope

2023-02-01 10:54 UTC, merged