Settings modal
charmverse/app.charmverse.io pull request #1627
Opened 2023-02-02 16:19 UTC by valentinludu

- [x] desktop
- [x] mobile
- [x] e2e tests

With the update of material-ui-popup-state, now we ca use `bindDialog` on MUI Dialogs and `variant: 'dialog' `on usepopupState.
This will ensure we do not pass the wrong props to a dialog. In the past we were using bindPopper on modal/dialogs.

2023-02-08 06:19 UTC, mattcasey commented on package.json
> +    "@mui/material": "^5.11.7",
was it necessary to update these libs at the same time?

2023-02-08 07:30 UTC, mattcasey requested changes
Left some comments

2023-02-08 07:30 UTC, mattcasey commented on hooks/useSettingsDialog.tsx
> +  mobileView: 'sidebar',
I would move the `mobileView` state into the SettingsDialog component where the logic is, since it's not used anywhere else. SettingsDialog can watch the 'open' attribute of the dialog to reset it back to 'sidebar'.

2023-02-08 07:30 UTC, mattcasey commented on hooks/useSettingsDialog.tsx
> +  'aria-haspopup': undefined,
these props are not used, afaict

2023-02-08 07:30 UTC, mattcasey commented on components/settings/workspace/Space.tsx
> -    charmClient.track.trackAction('page_view', { spaceId: space?.id, type: 'settings' });
We should still track page views for settings (maybe inside the hook?)

2023-02-08 07:30 UTC, mattcasey commented on components/settings/roles/RoleSettings.tsx
> +      <Legend display='flex' justifyContent='space-between' mt={4}>
+1 using props when we can :)

2023-02-08 07:30 UTC, mattcasey commented on components/settings/invites/components/TokenGates/components/TestConnectionModal.tsx
> +    <Modal size='fluid' {...props} title='xxx'>
remove the weird title

2023-02-08 07:30 UTC, mattcasey commented on components/settings/Legend.tsx
> +  shouldForwardProp: (prop) => prop !== 'noBorder'
thanks for adding this!

2023-02-08 07:30 UTC, mattcasey commented on components/profile/components/UserDetails/UserDetails.tsx
> +export const isPublicUser = (user: PublicUser | LoggedInUser | undefined): user is PublicUser =>
where are we calling isPublicUser() that user is undefined?  Seems like an unnecessary check

2023-02-08 07:30 UTC, mattcasey commented on components/nexus/components/NexusSidebar.tsx
>  import { Box, IconButton } from '@mui/material';
looks like we can just delete this file now

2023-02-08 07:30 UTC, mattcasey commented on components/nexus/components/NexusPageTitle.tsx
> -import { Box, Typography } from '@mui/material';
looks like u can just delete this file

2023-02-08 07:30 UTC, mattcasey commented on components/nexus/TasksPage.tsx
> +import Badge from '@mui/material/Badge';
` import { Badge, Box, Divider, Grid, Tab, Tabs, Typography } from '@mui/material';` was a better way to import these components, imports end up taking way too many lines

2023-02-08 07:30 UTC, mattcasey commented on components/common/Modal/SettingsDialog.tsx
> +import { StyledTreeItem } from 'components/common/PageLayout/components/PageNavigation//components/PageTreeItem';
there's a double slash here, not sure how it's not breaking!
`...PageNavigation//components..`

2023-02-08 07:30 UTC, mattcasey commented on components/common/Modal/SettingsDialog.tsx
> +          </Box>
On desktop, this Box creates a dark corner in the top-right of the modal just above the close button, because it's empty:

<img width="759" alt="image" src="https://user-images.githubusercontent.com/305398/217461933-d5486777-61e7-4835-a736-6c094623acb8.png">

2023-02-08 07:30 UTC, mattcasey commented on pages/profile.tsx
> -import type { ReactElement } from 'react';
We need to add a redirect for /profile.. for some reason it just gives me a blank page

2023-02-08 07:30 UTC, mattcasey commented on pages/nexus.tsx
> -import type { ReactElement } from 'react';
Need a redirect for /nexus

2023-02-08 07:30 UTC, mattcasey commented on pages/u/[userPath].tsx
> +    <PageLayout>
i don't know what happened here, but the sidebar is wrong (it currently is the narrow list of space avatars in prod):
<img width="737" alt="image" src="https://user-images.githubusercontent.com/305398/217462903-01c9eccd-d35e-4a36-bdb0-0f278b207e4c.png">

Safwan changed this, but I had to revert it because it broke the mobile sidebar.

2023-02-08 10:57 UTC, valentinludu commented on package.json
> +    "@mui/material": "^5.11.7",
The only necessary update is material-ui-popup-state.

I updated the MUI ones because I had some trouble with using Tabs and Trees. Saw some bugs related to tabs and I figured that maybe I will fix the issues. Turns out that those 2 can't be combined so I dropped the idea.
I left the updated because I figured that it would be nice to keep up to date the mui libs.

2023-02-08 11:00 UTC, valentinludu commented on components/settings/invites/components/TokenGates/components/TestConnectionModal.tsx
> +    <Modal size='fluid' {...props} title='xxx'>
Done

2023-02-08 11:01 UTC, valentinludu commented on components/settings/Legend.tsx
> +  shouldForwardProp: (prop) => prop !== 'noBorder'
I am trying to fix all warnings/errors related to pages I've been doing. Some of them appear also in datadog.

2023-02-08 11:11 UTC, valentinludu commented on pages/profile.tsx
> -import type { ReactElement } from 'react';
Done

2023-02-08 11:12 UTC, valentinludu commented on pages/nexus.tsx
> -import type { ReactElement } from 'react';
Done
Also added a redirect for /integrations


Also removed them from DOMAIN_BLACKLIST since there aren't valid url's anymore.

2023-02-08 11:13 UTC, valentinludu commented on components/nexus/components/NexusPageTitle.tsx
> -import { Box, Typography } from '@mui/material';
Forgot about that one.

Deleted!

2023-02-08 11:15 UTC, valentinludu commented on components/nexus/components/NexusSidebar.tsx
>  import { Box, IconButton } from '@mui/material';
I think I deleted this one and NexusTitle, but I had 3-4 related PR's merged in main and when I fixed conflicts I think those 2 were added again and I didn't see.

Good catch.
I deleted them!

2023-02-08 11:17 UTC, valentinludu commented on components/nexus/TasksPage.tsx
> +import Badge from '@mui/material/Badge';
Reverted back to one liner!

2023-02-08 11:21 UTC, valentinludu commented on components/common/Modal/SettingsDialog.tsx
> +          </Box>
Resolved!

2023-02-08 11:28 UTC, valentinludu commented on components/profile/components/UserDetails/UserDetails.tsx
> +export const isPublicUser = (user: PublicUser | LoggedInUser | undefined): user is PublicUser =>
Correct. I think I had a case and then was not needed anymore.

I reverted the change.

2023-02-08 11:39 UTC, valentinludu commented on hooks/useSettingsDialog.tsx
> +    [triggerDialogState, settingsDialogState, activePath]
Done

2023-02-08 11:53 UTC, valentinludu commented on package.json
> +    "material-ui-popup-state": "^5.0.4",
I needed this for adding bindDialog on my dialog.
We did not have it before and that is why we had and have some errors in the console when we open certain modals.
Instead of bindDialog we were doing bindPopper that has unnecessary props.

Looked at the breaking changes before and the impact is 0 because we we're not using some stuff that changed
- imports like material-ui-popup-state/es - not using anywhere
- new addition, bindDialog - necessary for this PR and for the future
- bindContextMenu changed behaviour - we don't use it anywhere
- improved types - better for us
- drop support for React < 16.8.0 - good for us we don't use that version
- bug fixes - no impact & good for us

2023-02-08 11:54 UTC, valentinludu commented on hooks/useSettingsDialog.tsx
> +  'aria-haspopup': undefined,
removed!

2023-02-08 12:30 UTC, valentinludu commented on hooks/useSettingsDialog.tsx
> +  onClick: () => undefined,
Done

2023-02-08 12:48 UTC, valentinludu commented on hooks/useSettingsDialog.tsx
> +      ...triggerDialogState,
Deleted binMethods.
exported only open, close, click

2023-02-08 14:55 UTC, valentinludu commented on pages/u/[userPath].tsx
> +    <PageLayout>
Just discussed with Safwan and I will add his changes here.

2023-02-08 20:38 UTC, valentinludu commented on pages/u/[userPath].tsx
> +    <PageLayout>
My last commit added what Safwan was doing, but with minimal changes.

2023-02-09 06:08 UTC, mattcasey commented on package.json
> +    "@mui/material": "^5.11.7",
Sounds good, thanks.

2023-02-09 06:11 UTC, mattcasey commented on hooks/useSettingsDialog.tsx
> +      onClick,
nice

2023-02-09 06:12 UTC, mattcasey approved these changes

2023-02-09 09:22 UTC, merged