Support og meta data for profiles
charmverse/app.charmverse.io pull request #1637
Opened 2023-02-05 06:30 UTC by Devorein

2023-02-05 17:06 UTC, mattcasey commented on pages/u/[userPath].tsx
> +  const origin = process.env.NODE_ENV === 'development' ? 'http://localhost:3000' : 'https://app.charmverse.io';
Please use `baseUrl` from config/constants

2023-02-05 17:06 UTC, mattcasey commented on pages/u/[userPath].tsx
> +      const user = await fetch<PublicUser>(`${origin}/api/public/profile/${params.userPath}`);
the server should not be querying itself

2023-02-05 17:20 UTC, mattcasey commented on pages/u/[userPath].tsx
> +      const user = await fetch<PublicUser>(`${origin}/api/public/profile/${params.userPath}`);
This is also an extremely expensive query - please don't call any 3rd party APIs when we're just rendering on the server. Information in the DB is enoguh for metadata

2023-02-05 17:20 UTC, mattcasey commented on pages/u/[userPath].tsx
> +      props: {
this should do a redirect, not pass 'null' to the frontend

2023-02-05 17:21 UTC, mattcasey commented on pages/u/[userPath].tsx
> +      props: {
this should send user to an error page and log the error

2023-02-05 17:21 UTC, mattcasey requested changes
see comments

2023-02-10 09:54 UTC, Devorein commented on pages/u/[userPath].tsx
> +  const origin = process.env.NODE_ENV === 'development' ? 'http://localhost:3000' : 'https://app.charmverse.io';
Thanx I totally forgot that env variable exists 🤦🏼‍♂️

2023-02-10 10:04 UTC, Devorein commented on pages/u/[userPath].tsx
> +      const user = await fetch<PublicUser>(`${origin}/api/public/profile/${params.userPath}`);
Got it. Thanks.

2023-02-10 16:10 UTC, mattcasey commented on pages/u/[userPath].tsx
> +        }
We should filter out only the fields we want because this is a public api... right now you're returning the user's notification email which lives in the user table

2023-02-10 16:11 UTC, mattcasey commented on pages/u/[userPath].tsx
> +  }, [publicUser]);
publicUser never changes, i don't think u need to use useEffect here?

2023-02-10 16:12 UTC, mattcasey commented on pages/u/[userPath].tsx
> +      <PublicProfile readOnly={true} user={user ?? publicUser} />
it looks like you could actually do the api call for user profile _inside_ public profile now, you're not even using `user` in this component anymore

2023-02-10 16:12 UTC, mattcasey requested changes
make sure we dont send private fields from user table

2023-02-12 10:46 UTC, Devorein commented on pages/u/[userPath].tsx
> +        }
Correct, thank you. Learned a lot about next.js pre-fetching mechanism through this PR.

2023-02-12 10:50 UTC, Devorein commented on pages/u/[userPath].tsx
> +  }, [publicUser]);
`setPageTitle` is a state setter, if we don't put it inside an `useEffect` then it would cause an infinite re-render. But more importantly, it could be null if the user doesn't exist. `publicUser: PublicUser | null`

2023-02-12 10:55 UTC, Devorein commented on pages/u/[userPath].tsx
> +      <PublicProfile readOnly={true} user={user ?? publicUser} />
The reason we have a separate user prop is for passing current user when looking at you profile.

We use the current user when looking at your profile
![image](https://user-images.githubusercontent.com/34683631/218306705-e16a10c4-5cd4-4b29-8ded-c861a73f7343.png)

We fetch the user based on query `userPath` here
![image](https://user-images.githubusercontent.com/34683631/218306760-b2bea991-b10d-4ce4-b6eb-876e426d7954.png)

![image](https://user-images.githubusercontent.com/34683631/218306786-5f3117a2-e8e0-4975-a0f4-9e079da17af8.png)

I can move the user fetching api call inside but that would also make a request when viewing your own profile. Plus it wont have the necessary fields required to distinguish between public and current user profile so you wont even be able to edit it. Maybe I can completely remove using `useSWR` inside `[userPath]` since it will be pre-fetched.

2023-02-12 17:12 UTC, merged