Block quote
charmverse/app.charmverse.io pull request #165
Opened 2022-03-03 18:16 UTC by motechFR

New block quote element

![image](https://user-images.githubusercontent.com/18669748/156626444-72547e17-827e-4557-9a39-250ce6c71e01.png)
![image](https://user-images.githubusercontent.com/18669748/156626696-ec551ca1-6d8d-4964-821a-a0f400361fc2.png)

2022-03-03 20:22 UTC, mattcasey requested changes
style changes

2022-03-03 20:22 UTC, mattcasey commented on components/editor/@bangle.io/extensions/inline-command-palette/use-editor-items.tsx
> +      icon: <ChatBubbleIcon sx={{
can we use a different icon from callout? How about "Chat" for blockquote: 
<img width="86" alt="image" src="https://user-images.githubusercontent.com/305398/156645593-38e1bd5b-e751-40bd-a5c8-be0b7ea97d1d.png">


Or "CalltoAction" for callout:
<img width="79" alt="image" src="https://user-images.githubusercontent.com/305398/156645654-c35a4b0b-52de-4409-9f51-0a2f955b78ba.png">

(I think the Chat icon would be my preference)

2022-03-03 20:22 UTC, mattcasey commented on components/editor/@bangle.io/extensions/inline-command-palette/use-editor-items.tsx
> +                  state.schema.text("Add a quote")
I think it's better to leave it empty if we can't have a placeholder, it felt weird having to delete this text

2022-03-03 20:22 UTC, mattcasey commented on components/editor/Quote.tsx
> +  border-radius: ${({ theme }) => theme.spacing(0.5)};
Not sure if this was intentional, but I think the left border look better as a long rectangle. Right now, only the left corners are rounded:
<img width="107" alt="image" src="https://user-images.githubusercontent.com/305398/156645967-8bd668c4-7bed-416f-ba38-c51382829f61.png">

2022-03-03 20:22 UTC, mattcasey commented on theme/index.ts
> +        main: mode === 'dark' ? '#F3EFF5' : '#111111'
The dark mode bar is very hard to see. I don't think we need new colors here.. we could use 'text.secondary' or 'text.primary'? Looking at Notion, they just use the text color but also add a bit more margin which I think helps

2022-03-04 10:57 UTC, Devorein commented on components/editor/@bangle.io/extensions/inline-command-palette/use-editor-items.tsx
> +      icon: <ChatBubbleIcon sx={{
I agree those looks much more suitable

2022-03-04 10:59 UTC, Devorein commented on components/editor/@bangle.io/extensions/inline-command-palette/use-editor-items.tsx
> +                  state.schema.text("Add a quote")
One thing I would like to point out is that we also show a default text for callout if we remove it for quote we need to remove it for callout as well

2022-03-04 11:00 UTC, Devorein commented on components/editor/Quote.tsx
> +  border-radius: ${({ theme }) => theme.spacing(0.5)};
I feel like the width could be decreased a bit, right now takes too much of the attention. Notion uses a lot less wide border.
![image](https://user-images.githubusercontent.com/34683631/156751539-cf2829ee-89cb-48ca-92c5-3e761fdaa206.png)

2022-03-04 11:30 UTC, motechFR commented on components/editor/@bangle.io/extensions/inline-command-palette/use-editor-items.tsx
> +      icon: <ChatBubbleIcon sx={{
Handled as of this [change](https://github.com/charmverse/app.charmverse.io/pull/165/commits/34a85ca08c4c18da821548b1a89e6f8d8dbddc6f)

2022-03-04 11:37 UTC, motechFR commented on components/editor/@bangle.io/extensions/inline-command-palette/use-editor-items.tsx
> +                  state.schema.text("Add a quote")
I've deleted the default text for quote and callout in this [change.](https://github.com/charmverse/app.charmverse.io/pull/165/commits/61b4da157de69b83f102502151950513f7be0c14)

Good to know, we need to provide at least an empty paragraph node, otherwise the quote cannot be modified. See the picture below.

![image](https://user-images.githubusercontent.com/18669748/156756540-7688a3b6-f0ea-4750-b06b-173d2c6c1625.png)

2022-03-04 11:40 UTC, motechFR commented on components/editor/Quote.tsx
> +  border-radius: ${({ theme }) => theme.spacing(0.5)};
I've halved the width of blockquote left border (8 => 4px) and removed radius

![image](https://user-images.githubusercontent.com/18669748/156757048-54a524e6-c81c-4d07-b7cf-13241eae1f7b.png)

2022-03-04 11:51 UTC, motechFR commented on theme/index.ts
> +        main: mode === 'dark' ? '#F3EFF5' : '#111111'
Was looking for best contrast, text is indeed the best one! I've updating that and expanded inner padding 

![image](https://user-images.githubusercontent.com/18669748/156758665-6f9dc391-06eb-4b29-a954-f6aceb0cb3be.png)

2022-03-04 15:32 UTC, merged