Convert Forum Post to Proposal
charmverse/app.charmverse.io pull request #1676
Opened 2023-02-08 17:28 UTC by Devorein

2023-02-09 06:00 UTC, mattcasey commented on components/common/PageLayout/components/Header/Header.tsx
> +      setPages((_pages) => ({
just let web sockets create the page... this is an over-optimization

2023-02-09 06:02 UTC, mattcasey commented on pages/api/forums/posts/[postId]/convert-to-proposal.ts
> +  relay.broadcast(
you're broadcasting new page here so no need to call setPages() on the frontend

2023-02-09 06:04 UTC, mattcasey requested changes
I think it is better to have a single method for the page to be updated. We really shouldn't need to call setPages() anywhere outside the usePages hook

2023-02-09 06:05 UTC, mattcasey approved these changes

2023-02-09 06:07 UTC, mattcasey commented on pages/api/forums/posts/[postId]/convert-to-proposal.ts
> +async function convertToProposal(req: NextApiRequest, res: NextApiResponse<PageMeta>) {
we should add a test on new endpoints

2023-02-09 11:01 UTC, motechFR commented on components/common/PageLayout/components/Header/Header.tsx
> +          title={!canCreateProposal || !isPostCreator ? 'You do not have the permission to convert to proposal' : ''}
This should only depend on canCreateProposal

2 reasons
- Someone might be a post author but not be able to create proposals
- Someone might be able to create proposals, and find this post worthy of being a proposal, but not be the author of the post

2023-02-09 11:02 UTC, motechFR commented on components/common/PageLayout/components/Header/Header.tsx
> +        <Tooltip title={!isPostCreator ? "You don't have permission to delete this post" : ''}>
Make sure to pull in latest main as this now consumes forum permissions.

Overall, you should never manually compute permissions on the UI, and only use the permissions from the hook

2023-02-10 13:33 UTC, motechFR commented on lib/permissions/forum/computePostPermissions.ts
> +
This won't work as we're not computing if the user might be a moderator.

This is a case where we can write the same logic in 2 places without abstraction.

// First branch: isAdmin
if (isAdmin) {
  if (post.proposald) {
  const proposalPermissions = new AvailablePostPermissions()
  proposalPermissions.addPermissions(['view_post', 'delete_post'])
  return proposal permissions
 } else {
  // Return current admin value
}
}

2023-02-10 13:42 UTC, motechFR commented on lib/permissions/forum/computePostPermissions.ts
> +
Then, around line 97;
// Move the permissions search up to here.

// Computing user level based on actual permissions, but we just want a subset
if (proposalId) {
 const hasModerator = hasModeratorSpaceWidePermissions || permissions.some(p => (p.permissionLevel === 'moderator' || p.permissionLevel === 'category_admin))

const convertedToProposalPermissions = new AvailablePostPermissions()
 if (hasModerator) {
 convertedToProposalPermissions.addPermissions(['delete_post]);


} 

convertedToProposalPermissions.addPermissions(['view_post'])

return convertedToProposalPermissions.operationFlags
}


Actually I'll handle this one

2023-02-10 13:45 UTC, motechFR commented on lib/permissions/forum/computePostPermissions.ts
> +  if (post.proposalId) {
Please add these 5 test cases when there is a proposal, I'll get them to pass:

// Add these below existing unit tests

- Returns only the delete_post and view_post permission for admins
- Returns delete_post and view_post for authors
- Returns delete_post and view_post for moderators with space-wide moderate
- Returns delete_post and view_post for moderators with category_level moderate
- Returns only view_post for normal space members, even if they have a full access permission for this categoru

2023-02-10 13:47 UTC, motechFR commented on pages/api/forums/posts/[postId]/convert-to-proposal.ts
> +import { convertPostToProposal } from '../../../../../lib/forums/posts/convertPostToProposal';
You can delete the extra ../../../ I think ;)

2023-02-10 13:47 UTC, motechFR commented on lib/proposal/createProposal.ts
> +          permissions: true
let's not include these permissions based on your feedback since the UI will handle refresh

2023-02-10 13:48 UTC, motechFR commented on __integration-tests__/server/pages/api/posts/[postId]/convert-to-proposal.spec.ts
> +  it('should succeed if the user has permission, and respond 200', async () => {
Can you also add a 401 test? These are super short to write

2023-02-10 13:52 UTC, motechFR commented on lib/forums/posts/convertPostToProposal.ts
> +export async function convertPostToProposal({ postId, proposalId }: { postId: string; proposalId: string }) {
Can you move the logic inside convert post to proposal?

Let this function automagically handle the conversion. You already have the code in the API.

Then, just add a unit test that checks that the return type is a PageWithProposal and that the content is the same as the post content

2023-02-10 13:54 UTC, motechFR requested changes
Please make requested changes.

Moving the createProposal logic inside convertProposal optional for now.

We do need to make sure permissions are clean before merging this

2023-02-14 15:19 UTC, motechFR commented on __integration-tests__/server/pages/api/forums/posts/[postId]/comments/index.spec.ts
> +  const { user: _user2 } = await generateUserAndSpace({ isAdmin: false });
Can you please replace this by generateSpaceUser method? It creates the user as a space member

2023-02-15 08:52 UTC, merged