Format focalboard dates based on user preference locale
charmverse/app.charmverse.io pull request #1713
Opened 2023-02-12 15:43 UTC by Devorein

2023-02-13 08:19 UTC, msadura commented on components/common/BoardEditor/focalboard/src/components/properties/dateRange/dateRange.tsx
> +      displayDate = formatDate(date);
Check lines 174 and 183 in this file - they are still using some custom date format instead of this function

2023-02-13 08:21 UTC, msadura commented on components/common/BoardEditor/focalboard/src/components/properties/dateRange/dateRange.tsx
> +      displayDate = formatDate(date);
If you update that code you should not even need `locale` variable - overall you want to use our formatted to avoid creating custom date formats and keep app consistent

2023-02-13 08:34 UTC, msadura requested changes

2023-02-13 08:34 UTC, msadura commented on components/common/BoardEditor/focalboard/src/widgets/editableDayPicker.tsx
> +  const { formatDate: formatLocaleDate } = useDateFormatter();
I dont understand why you have `formatLocaleDate ` here and below there is custom `formatDate` - this custom formatDate should be just removed, as we do not want to have random formats

2023-02-13 08:34 UTC, msadura commented on pages/_app.tsx
> +function LocaleProvider({ children }: { children: ReactNode }) {
I believe we agreed to try not to mess _app.tsx when not needed. Please move this provider to `components/_app` dir

2023-02-13 08:34 UTC, msadura commented on pages/_app.tsx
> +    <LocalizationProvider dateAdapter={AdapterLuxon as any} adapterLocale={userPreferences.locale ?? undefined}>
I believe `as any` is not needed

2023-02-13 08:34 UTC, msadura commented on pages/_app.tsx
> +    <LocalizationProvider dateAdapter={AdapterLuxon as any} adapterLocale={userPreferences.locale ?? undefined}>
Honestly I somehow do not like this solution as it will bind luxon to mui and it will stay with us forever :D I think we might want to create out own adapter which will use our formatting functions. Anyway it is not in a scope of this task, but we might consider adding this to our long-term backlog. cc: @mattcasey

2023-02-13 15:23 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/components/properties/dateRange/dateRange.tsx
> +      displayDate = formatDate(date);
Got it. Thank you.

2023-02-13 15:26 UTC, mattcasey commented on components/common/BoardEditor/focalboard/csvExporter/csvExporter.ts
> +          (date) => Utils.displayDateTime(new Date(date), intl)
these are the wrong methods, right?

2023-02-13 15:28 UTC, mattcasey commented on components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
> +  const displayValue = propertyDisplayValue(card, propertyValue, propertyTemplate);
I think usePropertyDisplayValue wraps propertyDisplayValue...  are we calling it twice here?

2023-02-13 15:29 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/widgets/editableDayPicker.tsx
> +  const { formatDate: formatLocaleDate } = useDateFormatter();
Thanks. Ended up deleting this whole component as its not used anywhere 🥳

2023-02-13 15:29 UTC, mattcasey commented on components/common/BoardEditor/focalboard/src/octoUtils.tsx
> +  const { formatDateTime, formatDate } = useDateFormatter();
this seems like an unecessary abstraction, couldnt you hace just passed formatDateTime into the original method instead of `intl`

2023-02-13 15:32 UTC, mattcasey commented on pages/_app.tsx
> -          <LocalizationProvider dateAdapter={AdapterLuxon as any}>
have you tested all the places this would be used?

2023-02-13 15:37 UTC, Devorein commented on pages/_app.tsx
> +    <LocalizationProvider dateAdapter={AdapterLuxon as any} adapterLocale={userPreferences.locale ?? undefined}>
yep its not throwing any error 🥳

2023-02-14 09:08 UTC, Devorein commented on pages/_app.tsx
> -          <LocalizationProvider dateAdapter={AdapterLuxon as any}>
Yes we are using the `DateTimePicker` in three places and I've tested all of them out.

2023-02-14 09:17 UTC, Devorein commented on components/common/BoardEditor/focalboard/csvExporter/csvExporter.ts
> +          (date) => Utils.displayDateTime(new Date(date), intl)
They were wrong, I've fixed it now. exported csv will now format dates based on user preference locale.

2023-02-14 09:51 UTC, merged

2023-02-14 11:15 UTC, msadura commented on components/common/BoardEditor/focalboard/src/components/properties/dateRange/dateRange.tsx
> +                  const newDate = new Date(formatDate(fromInput, { withYear: true }));
I don't get why you first format date to string and then create a date object from it?