New UI for Profile view
charmverse/app.charmverse.io pull request #1736
Opened 2023-02-16 10:33 UTC by valentinludu

https://app.charmverse.io/charmverse/page-5367853706449786?viewId=2c9d8701-33ff-4c3a-942a-6d403a638565&cardId=

2023-02-16 18:06 UTC, valentinludu commented on pages/api/spaces/[id]/members/index.ts
> +  if (!currentSpaceRole?.onboarded && userId) {
@devs 
I need your opinions on this one.
I think this is the best place to populate user avatar and pinned nfts.

2023-02-21 09:23 UTC, mattcasey commented on pages/api/spaces/[id]/members/index.ts
> +  if (!currentSpaceRole?.onboarded && userId) {
@valentinludu This route is a GET endpoints to return list of members in a space. It makes no sense to me that it would update the user profile... 1) it's a GET, we should never mutate on GET requests and 2) its to retrieve members of the space, and it is already being used in too many places. We really should have one route to retrieve list of users for general display in docs and focalboard properties, one for member directory (with all the member properties) and one for user profile. So I would not anything else to this endpoint

2023-02-21 09:24 UTC, mattcasey commented on pages/api/spaces/[id]/members/index.ts
> +  if (!currentSpaceRole?.onboarded && userId) {
What are you trying to do? Is this something that should be done during onboarding, or in a migration?

2023-02-21 09:27 UTC, mattcasey commented on components/common/Modal/SettingsDialog.tsx
> +              {shortWalletAddress(user?.username)}
we should never have to do this in the frontend . usernames should already be 'shortened' when we assign a wallet address  to them in the backend.

2023-02-21 09:28 UTC, mattcasey commented on components/common/Modal/SettingsDialog.tsx
> +              '&:hover': { backgroundColor: 'transparent' }
Not sure why you want to use a hover effect on mobile, but if you do, you _must_ use the media query `@media (pointer: fine)` to disable it on iOS or else it will require double-clicking.

2023-02-21 09:32 UTC, mattcasey commented on components/common/form/interfaces.ts
> +  customOnChange?: (value: any) => Promise<void>;
feels like `customOnChange` should have the same signature as `onChange` and i would probably just use `onChange`. "custom" makes me think I am overriding a default handler, but it's just being called in addition.

2023-02-21 09:40 UTC, mattcasey commented on components/profile/components/SpacesMemberDetails/components/MemberPropertiesPopup.tsx
> -            <DialogActions>
we should add some padding at the bottom of the modal now that the buttons are gone

2023-02-21 09:42 UTC, mattcasey commented on components/profile/components/SpacesMemberDetails/components/MemberPropertiesPopup.tsx
> +                const fieldRendererConfig = getFieldRendererConfig({
this is a weird pattern, but i know we were using it before so doesn't need to be fixed here. I think it should just be a single React component, i don't kno why we need to have a method that returns some properties that passed to another React component

2023-02-21 09:47 UTC, mattcasey commented on components/common/form/fields/FieldWrapper.tsx
>          <Box maxWidth={150} width={150} alignItems='center' display='flex' gap={1}>
i don't think we need this max width anymore. a long label looks very squished in the member properties modal?

2023-02-21 09:53 UTC, mattcasey commented on components/common/form/fields/NumberInputField.tsx
> +      customOnChange?.(event.target.value);
I'm not really sure why we needed customOnChange, but i find it extremely confusing to have a component that takes onChange as well as customOnChange.. i tihnk a better pattern could be to wrap the original 'onChange' handler in one of the parents?

```
function parentInput (props: { onChange }) {
 
  function customOnChange(event) {
     // do stuff
     onChange(event)
  }
   return <NumberInput onChange={customOnChange} />
}


```

2023-02-21 10:09 UTC, mattcasey commented on lib/blockchain/getNFTs.ts
> +import { getNFTs } from 'lib/blockchain/nfts';
this is confusing: 'getNFTs' imports another method 'getNFTs' from a sibling folder called 'nfts'. This method just belongs inside 'nfts' or inside a folder with them grouped together.

2023-02-21 10:12 UTC, mattcasey commented on lib/blockchain/getNFTs.ts
> +import { getNFTs } from 'lib/blockchain/nfts';
On second though, this probably belongs in lib/profile since it's based on the user profile, and u could rename it "getUserNFTs.ts"

2023-02-21 10:16 UTC, mattcasey requested changes
Left some comments...

design-wise, maybe for another iteration, I think the member properties should just be editable and not inside a popup when editing in settings:

![image](https://user-images.githubusercontent.com/305398/220316688-3adc6629-10b3-4afe-a277-cdfd66823afd.png)

2023-02-21 13:47 UTC, valentinludu commented on components/common/Modal/SettingsDialog.tsx
> +              {shortWalletAddress(user?.username)}
There were some cases where I saw the whole address. Will bring it up in today's meeting.

2023-02-21 13:54 UTC, valentinludu commented on components/profile/components/SpacesMemberDetails/components/MemberPropertiesPopup.tsx
> -            <DialogActions>
Done!

2023-02-21 14:04 UTC, valentinludu commented on components/common/form/fields/FieldWrapper.tsx
>          <Box maxWidth={150} width={150} alignItems='center' display='flex' gap={1}>
Removed.
Checked on mobile and desktop and looks fine without the width and maxWidth.

2023-02-21 14:44 UTC, valentinludu commented on components/profile/components/SpacesMemberDetails/components/MemberPropertiesPopup.tsx
> +                const fieldRendererConfig = getFieldRendererConfig({
yes, it would be easy.
It took me some time to get my head around it.

Now that you mention it, I removed this pattern and kept only what we needed in a more readable form.

2023-02-21 14:45 UTC, valentinludu commented on components/common/form/interfaces.ts
> +  customOnChange?: (value: any) => Promise<void>;
Removed customOnChange and kept only onChange

2023-02-21 14:46 UTC, valentinludu commented on components/common/form/fields/NumberInputField.tsx
> +      customOnChange?.(event.target.value);
Added onChange logic outside the Controller. When I send the onChange to the controller I also await for the change

2023-02-21 15:21 UTC, valentinludu commented on lib/blockchain/getNFTs.ts
> +import { getNFTs } from 'lib/blockchain/nfts';
Moved to lib/profile/getUserNFTs.ts

2023-02-22 13:31 UTC, valentinludu commented on components/profile/components/UserDetails/utils.ts
> +export const isPublicUser = (user: PublicUser | LoggedInUser, currentUser: null | LoggedInUser): user is PublicUser =>
I agree that this function is not the best solution and name. Also this function was here before and I just moved it to a separate location because it was used in multiple places.

I added the verification to be sure the object structure is indeed a public profile.

If I return a boolean without a type this will make PublicProfile and UserDetails full of ts errors because they are relying on that type (Public or not). 

The problem is that PublicProfile is used from /u/ public page (Public user) or in profile settings (LoggedIn user). 
The solution is to decouple these 2 and make separate flows and reuse components that they have in common. But I think I will leave this for another PR.

2023-02-22 14:44 UTC, valentinludu commented on pages/api/spaces/[id]/members/index.ts
> +  if (!currentSpaceRole?.onboarded && userId) {
Right. It was more of a proof of concept.

Moved this login inside the user creation.
Now, if a user is created with a wallet and has nfts, then I will populate his profile.

2023-02-23 15:47 UTC, mattcasey approved these changes

2023-02-23 19:35 UTC, merged