Proposal permissions
charmverse/app.charmverse.io pull request #1745
Opened 2023-02-17 01:28 UTC by motechFR

Provide proposal permissions engine

2023-02-17 03:06 UTC, mattcasey commented on lib/permissions/proposals/deleteProposalCategoryPermission.ts
> +  if (!permission) {
should log a warning at least or use findUniqueOrThrow so it thorws an error if the user is expecting a successful change

2023-02-17 03:07 UTC, mattcasey commented on lib/permissions/proposals/computeProposalPermissions/pfpStatusDiscussionEditableCommentable.ts
> +import type { ProposalOperation } from '@prisma/client';
Please don't use acronyms in the file names... I don't know what 'pfp' means, so you might as well leave it out or put them in a folder

2023-02-17 03:09 UTC, mattcasey commented on lib/proposal/errors.ts
> +import { SystemError } from 'lib/utilities/errors';
lib/proposals should be plural

2023-02-17 03:14 UTC, mattcasey commented on lib/permissions/buildComputePermissionsWithPermissionFilteringPolicies.ts
> +      // Perform an early return if a PFP results in fully empty permissions
we don't want to use acronyms to refer to parts of our system. it makes onboarding new devs hard and confusing for non-tech people when we talk about it in Discord

2023-02-17 03:22 UTC, mattcasey commented on lib/permissions/proposals/hasSpaceWideProposalReviewerPermission.ts
> +      forSpaceId: spaceId,
what's the difference between forSpaceId and spaceId in this schema?

2023-02-17 03:25 UTC, mattcasey commented on lib/permissions/proposals/listProposalCategoryPermissions.ts
> +    return [];
we should probably throw an error here instead

2023-02-17 03:28 UTC, mattcasey commented on lib/permissions/proposals/__tests__/listProposalCategoryPermissions.spec.ts
> +  it('should return an empty list for non-space members', async () => {
since these are lib methods, i think they should throw an error if they are given garbage, just as you are throwing an error if the id is invalid.

2023-02-17 03:32 UTC, mattcasey commented on lib/permissions/proposals/listProposalCategoryPermissions.ts
> +  if (!userId) {
i think this is a bad pattern, where a function silently handles some edge case. Why not make userId required?

2023-02-17 03:35 UTC, mattcasey commented on lib/permissions/proposals/listProposalCategoryPermissions.ts
> +  resourceId,
suggestion: just call this 'categoryId'. it's much easier to know what this function is asking for. 'resourceId' is a vague variable name, its' like using "data" for the return of a page or block model.

2023-02-17 03:38 UTC, mattcasey commented on lib/permissions/proposals/upsertProposalCategoryPermission.ts
> +    throw new DataNotFoundError(`Proposal category with id ${proposalCategoryId} not found`);
should this be ProposalCategoryNotFoundError?

2023-02-17 03:41 UTC, mattcasey commented on lib/permissions/proposals/computeProposalPermissions/pfpStatusPrivateDraftVisibleOnlyByAuthor.ts
> +export async function pfpStatusPrivateDraftVisibleOnlyByAuthor({
i dont know how these policy functions will be used but seems pretty easy to follow :)

2023-02-17 03:43 UTC, mattcasey commented on lib/proposal/errors.ts
> +import { SystemError } from 'lib/utilities/errors';
ah nvm i see thats how it's been for a while.. probably do it in a separate PR

2023-02-17 03:54 UTC, mattcasey requested changes
Lots of code, but looks good... I assume you know what all these methods will be used for :P

One request is please find a better prefix than "pfp" for function and file names, or maybe use a folder as a namespace so the filenames don't get too long. Just removing pfp would be fine too, imo since all this code is already inside a folder called /permissions/proposals

2023-02-17 19:33 UTC, motechFR commented on lib/permissions/proposals/deleteProposalCategoryPermission.ts
> +  if (!permission) {
Added log.warn

2023-02-17 19:34 UTC, motechFR commented on lib/permissions/proposals/computeProposalPermissions/pfpStatusDiscussionEditableCommentable.ts
> +import type { ProposalOperation } from '@prisma/client';
Suggestion: I can move these to permissionFilteringPolicies subfolder

2023-02-17 19:35 UTC, motechFR commented on lib/permissions/buildComputePermissionsWithPermissionFilteringPolicies.ts
> +      // Perform an early return if a PFP results in fully empty permissions
Noted, will use the long form

2023-02-17 19:36 UTC, motechFR commented on lib/permissions/proposals/hasSpaceWideProposalReviewerPermission.ts
> +      forSpaceId: spaceId,
Potential idea; space-wide: true

2023-02-17 19:40 UTC, motechFR commented on lib/permissions/proposals/__tests__/listProposalCategoryPermissions.spec.ts
> +  it('should return an empty list for non-space members', async () => {
We'll need to change this test :)

2023-02-17 19:42 UTC, motechFR commented on lib/permissions/proposals/listProposalCategoryPermissions.ts
> +  resourceId,
We're using resourceId for cross-permissions subsystem compatibility

2023-02-17 19:53 UTC, motechFR commented
Note on PFP builder
- Don't throw an error if PFP grants extra permissions, just refuse to assign the new true permissions instad

2023-02-24 07:45 UTC, mattcasey commented on prisma/migrations/20230223203450_proposal_permissions/migration.sql
> +-- CreateIndex
@motechFR make sure to uncomment this before deploying to production

2023-02-24 08:08 UTC, mattcasey commented on scripts/migrations/2023_02_23_migrateProposals.ts
> +        title: 'General'
It looks like we need a "defaultForSpace" property here? If we have a default category, I think users would expect it to behave the same as forum default category

2023-02-24 08:35 UTC, mattcasey commented on scripts/migrations/2023_02_23_migrateProposals.ts
> +  disconnectProposalsFromChildren();
The only migration that seems necessary right now is assignSpaceDefaultPermissions(). disconnectProposalsFromChildren() is not necessary after we confirmed proposals always have type === 'proposal' and hence their children would not be visible in the sidebar anyway. This might actually surprise someone with pages they didn't know existed :P

2023-02-24 08:42 UTC, mattcasey commented on scripts/migrations/2023_02_23_migrateProposals.ts
> +  assignSpaceDefaultPermissions();
make sure to await on these methods too!

2023-02-24 08:54 UTC, mattcasey approved these changes

2023-02-24 23:03 UTC, merged