Invalid token error on discord oauth
charmverse/app.charmverse.io pull request #1756
Opened 2023-02-20 15:34 UTC by Devorein

2023-02-21 11:24 UTC, msadura requested changes

2023-02-21 11:24 UTC, msadura commented on components/login/WalletConnect.tsx
> +    updateUser({ ...currentUser, ...updatedUser });
if you check `updateUser` method, it does internally the same logic you added, so I do not see a point in adding that.

```
  const updateUser = useCallback((updatedUser: Partial<LoggedInUser>) => {
    setUser((u) => (u ? { ...u, ...updatedUser } : null));
  }, []);
```

2023-02-21 11:24 UTC, msadura commented on pages/_app.tsx
> +        <DiscordProvider>
can you please explain this? I do not see using `useDiscordConnection` anywhere outside `IdentityProviders.tsx` file so I miss the point of moving it to be global provider

2023-02-21 13:53 UTC, Devorein commented on components/login/WalletConnect.tsx
> +    updateUser({ ...currentUser, ...updatedUser });
Thank you for catching that. It was a mistake on my end.

2023-02-21 13:57 UTC, Devorein commented on pages/_app.tsx
> +        <DiscordProvider>
Yes absolutely. After connecting discord we attach the auth token in the cookie. All the logic for connecting your discord account with charmverse was located inside `IdentityProvider` thus unless that component gets mounted discord connection wasn't triggered. Thats why it was relocated outside and moved inside `_app`.

2023-02-22 04:26 UTC, mattcasey approved these changes

2023-02-22 09:39 UTC, msadura commented on pages/_app.tsx
> +        <DiscordProvider>
thx, now it makes sense :D

2023-02-22 09:39 UTC, msadura approved these changes

2023-02-22 12:26 UTC, merged