Proposal comments
charmverse/app.charmverse.io pull request #1763
Opened 2023-02-22 09:37 UTC by msadura

WIP

2023-02-23 09:05 UTC, msadura commented on components/common/comments/Comment.tsx
> +import { useTheme } from '@emotion/react';
This is just copied old `PostComment` component with removed "Post" context - it will just work with any sort of comment, and it does need to know about comment type.

2023-02-23 09:07 UTC, msadura commented on components/common/comments/CommentForm.tsx
> +import { Stack, Box } from '@mui/material';
This is copy of `CreatePostForm` component with generic method to create comment

2023-02-23 09:09 UTC, msadura commented on components/common/comments/utils.ts
> +export function processComments<T>(postComments: GenericCommentWithVote<T>[]): CommentWithChildren<T>[] {
Moved some common comment methods from `PostComment` and made types to be generic.

2023-03-02 16:06 UTC, mattcasey commented on lib/pages/comments/__tests__/deletePostComment.spec.ts
> +import type { Space, User } from '@prisma/client';
is this file supposed to be 'deletePageComment.spec.ts'?

2023-03-02 16:07 UTC, mattcasey commented on lib/pages/comments/__tests__/updatePostComment.spec.ts
> +import type { Space, User } from '@prisma/client';
updatePageComment.spec.ts

2023-03-02 16:08 UTC, mattcasey requested changes
looks good.. one request: can we hide the comment input when creating a proposal? Or perhaps just hide it when it's in 'draft' state, because i don't know if we have a way to check if it was just created in the modal

2023-03-02 19:57 UTC, msadura commented
> looks good.. one request: can we hide the comment input when creating a proposal? Or perhaps just hide it when it's in 'draft' state, because i don't know if we have a way to check if it was just created in the modal

yeah there is no clear way to tell if it was "just created". I will do it for draft state. Thx for the idea!

2023-03-02 23:26 UTC, motechFR commented on components/common/comments/Comment.tsx
> +  const canDeleteComment = (permissions?.delete_comments || isCommentAuthor) && !deletingDisabled;
Looks good, this is our pattern for comments

2023-03-02 23:29 UTC, motechFR commented on components/common/comments/Comment.tsx
> +              disabled={!canDeleteComment}
Can we split this logic to also have canEditComment ?

Only the author should be able to edit their own comment

2023-03-02 23:29 UTC, motechFR commented on components/forum/components/PostPage/components/PostComment.tsx
> +    />
Cool refactor, I like this!

2023-03-02 23:30 UTC, motechFR commented on pages/api/pages/[id]/comments/[commentId]/index.ts
> +    throw new UserIsNotSpaceMemberError();
We can delete these checks, and just use the comment.createdBy === userId staement below

2023-03-02 23:33 UTC, motechFR commented on pages/api/pages/[id]/comments/[commentId]/index.ts
> +  if (pageComment.createdBy === userId) {
For deleting pattern, we can use isAdmin or comment === createdBy (make sure this is reflected in the UI)

2023-03-02 23:37 UTC, motechFR commented on lib/pages/comments/createPageComment.ts
> +    where: { id: pageId }
Performance improvement; you can use the select prop in prisma to only return page.id and reduce database and memory load (since we won't need the page comtent for example

where: { id: pageId },
select: {
 id: true
}

2023-03-03 09:47 UTC, merged