Private application discussions
charmverse/app.charmverse.io pull request #1829
Opened 2023-03-09 05:28 UTC by Devorein

2023-03-10 08:12 UTC, msadura requested changes

2023-03-10 08:12 UTC, msadura commented on components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/ApplicationCommentForm.tsx
> +  $key?: string | number;
why do you need such thing?

2023-03-10 08:12 UTC, msadura commented on components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/ApplicationCommentForm.tsx
> +    <StyleContainer>
Instead of using all of that custom jsx you can use `CommentForm` component which will look consistent within the whole app

2023-03-10 08:12 UTC, msadura commented on components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/ApplicationComments.tsx
> +export function getContentWithMention({ myUserId, targetUserId }: { myUserId: string; targetUserId: string }) {
this is exact copy of function from `getContentWithMention` - can you please try to avoid such duplications and move common logic to some shared utils file?

2023-03-10 08:12 UTC, msadura commented on components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/ApplicationComments.tsx
> +        {applicationComments.map((applicationComment) => {
there is `components/common/comments/Comment.tsx` component which we use for forums and proposals and it would be the best to re-use it here as well. Aa far as I see you will only need customise it with a props to hide reply button and votes. This way we will have consistent comments across the app

2023-03-10 08:12 UTC, msadura commented on pages/api/applications/[id]/comments/[commentId].ts
> +  const pageComment = await prisma.pageComment.findUnique({
This is a copy of logic from page comments - can you please move shared part to common util in libs?

2023-03-13 13:07 UTC, Devorein commented on components/[pageId]/DocumentPage/components/BountyProperties/components/BountyApplicantsTable/ApplicationComments.tsx
> +        {applicationComments.map((applicationComment) => {
Thank you. That was indeed a lot easier, just need to make sure typescript isn't complaning

2023-03-13 13:10 UTC, Devorein commented on pages/api/applications/[id]/comments/[commentId].ts
> +  const pageComment = await prisma.pageComment.findUnique({
Thank you. Updated

2023-03-14 17:21 UTC, mattcasey approved these changes

2023-03-14 17:44 UTC, merged