Added static links to Page
charmverse/app.charmverse.io pull request #1896
Opened 2023-03-22 10:46 UTC by valentinludu

2023-03-22 11:55 UTC, valentinludu commented on components/common/PageLayout/components/Sidebar/Sidebar.tsx
> +                      data-test={`sidebar-link-${page.path}`}
I have no idea how did the e2e test pass before, because this button did not have a data-test attr.

2023-03-22 14:11 UTC, motechFR commented on components/common/PageLayout/components/Sidebar/utils/staticPages.tsx
> +export type StaticPagesType = `${StaticPagesPath}`;
An alternative syntax we often use: type X = keyof typeof Y

2023-03-22 14:14 UTC, motechFR commented
UX issue: Downwards scrolling only applies to page, not the static pages

2023-03-22 14:23 UTC, motechFR commented on components/common/PageLayout/components/Sidebar/utils/staticPages.tsx
> +export type StaticPagesList = {
One small suggestion, since we are using this in interoperable fashion with pages for the nested page feature, we could define this interface as

Pick<Page, 'title' | 'path'> & {feature: Feature} to make this coupling a bit more explicit

2023-03-22 14:25 UTC, motechFR commented on components/common/PageLayout/components/Sidebar/Sidebar.tsx
> +                      data-test={`sidebar-link-${page.path}`}
If you wanted, we could wrap the e2e test body from l:27 (checking link is visible) till the end in a for loop and test all 4 of these menu options to make sure they work

2023-03-22 14:26 UTC, motechFR approved these changes
Approving PR as it works, double check with product team if we want to scroll between page types, but sounds like desirable behaviour

2023-03-22 15:37 UTC, valentinludu commented on components/common/PageLayout/components/Sidebar/utils/staticPages.tsx
> +export type StaticPagesType = `${StaticPagesPath}`;
Niceeeee. I did not know that it's the same thing with what I did. Thanks.

2023-03-22 16:43 UTC, valentinludu commented on components/common/PageLayout/components/Sidebar/Sidebar.tsx
> +                      data-test={`sidebar-link-${page.path}`}
Good idea. Just pushed the improved e2e test

2023-03-22 17:25 UTC, valentinludu commented
> UX issue: Downwards selection with keyboard only applies to page, not the static pages (I return to the top option after)
> 
> <img alt="Screenshot 2023-03-22 at 16 15 40" width="396" src="https://user-images.githubusercontent.com/18669748/226932205-b8bff1be-393e-435e-a83a-6185f0cf2447.png">

Fixed!

Thanks for finding that.

2023-03-23 21:27 UTC, mattcasey commented on __e2e__/settings/hideFeatures.spec.ts
> +  await spaceSettings.page.waitForTimeout(2000);
2000 is too long for a timeout. Instead, it is better to use waitForFunction and declare what you are waiting for.

2023-03-23 21:35 UTC, mattcasey commented on components/common/PageLayout/components/Sidebar/utils/staticPages.tsx
this file could just go in lib/pages or something

2023-03-23 21:43 UTC, mattcasey commented on components/common/CharmEditor/components/PageList.tsx
> +      title: page.name,
I think we should say `Forum > {page.name}` ? otherwise it's hard to find all your forum categories, and not obvious that this isn't just a regular page

2023-03-23 21:47 UTC, mattcasey requested changes
Works well, using 'id' for everything feels pretty hacky but I can't come up with any real issue. It works well only because we happen to have all the categories and pages in memory, but if you were trying to read this someplace else you would have no way to know if it was a category or a page, and you'd have to guard against non-uuid values before running a query. Maybe add a 'type' attribute, even if we aren't reading it?

Please fix the test - increasing timeouts is not really addressing the issue, it could always take longer than 2 seconds.

2023-03-24 10:54 UTC, valentinludu commented on __e2e__/settings/hideFeatures.spec.ts
> +  await spaceSettings.page.waitForTimeout(2000);
Instead of that complicated check of classes and waiting for classes to change I simplified the logic and I am just waiting for the input to be checked or not.
e.g: `await expect(spaceSettings.proposalsVisibilityToggle).toBeChecked();`

2023-03-24 11:01 UTC, valentinludu commented on components/common/CharmEditor/components/PageList.tsx
> +      title: page.name,
Yep. It will be a better UX for the user.

Thanks for that. I added it.

2023-03-24 11:05 UTC, valentinludu commented on __e2e__/settings/hideFeatures.spec.ts
> +  await spaceSettings.page.waitForTimeout(2000);
I deleted all the waitFor stuff.

2023-03-24 13:42 UTC, merged