Fix the large popup for editing forum categories
charmverse/app.charmverse.io pull request #1919
Opened 2023-03-24 20:22 UTC by motechFR

2023-03-24 21:45 UTC, mattcasey requested changes
this looks like a bug introduced by @msadura in this PR: https://github.com/charmverse/app.charmverse.io/pull/1909/files#diff-e45bfc88466d6c960d04e86d6b9efe64492813c7309aa2ec681ee2838cb16621. Rather than add more customization on this component, I wonder why not just use MUI's component directly. This seems to just be adding a bunch of defaults, but they don't fit every case so we're making our jobs even harder. The bug also exists on the proposal category popups, for example

2023-03-24 22:32 UTC, motechFR commented
> https://github.com/charmverse/app.charmverse.io/pull/1909/files#diff-e45bfc88466d6c960d04e86d6b9efe64492813c7309aa2ec681ee2838cb16621

I'm counting 7 locations where we use this component, so i think it would be good to continue using it.

I did some checking, and this issue pops up in the member directory menu where you update the options (see with / without) screenshots below.

Went for the solution of making the popper simpler, and passing the style props from the outside.

I created a common setting for CharmEditor components that we can pass down.

Replicated intent of @msadura PR by passing these props down to the PDF, Media and Image selectors


<img width="325" alt="Screenshot 2023-03-25 at 00 23 10" src="https://user-images.githubusercontent.com/18669748/227654150-80993738-fb59-4b4b-9349-842b9cc67495.png">

<img width="790" alt="Screenshot 2023-03-25 at 00 23 42" src="https://user-images.githubusercontent.com/18669748/227654233-10e19fe1-c751-4bc1-a1fd-0b18f024a872.png">

2023-03-25 20:46 UTC, msadura commented on components/common/CharmEditor/components/common/selectorPopupSizeConfig.ts
> +export const selectorPopupSizeConfig: SxProps<Theme> = {
I would move this directly  to `[MediaSelectionPopup.tsx]` - later on (not in a scope of this issue)we should refactor PDF and Image selector components to use this one as well, and this style will only be needed there.

2023-03-25 20:46 UTC, msadura commented on components/common/PopperPopup.tsx
> +  sx?: SxProps<Theme>;
tiny stuff - lets call it `paperSx` to explicitly tell where those styles will be applied

2023-03-25 20:46 UTC, msadura approved these changes

2023-03-25 22:57 UTC, motechFR commented on components/common/PopperPopup.tsx
> +  sx?: SxProps<Theme>;
Sounds good, made the update

2023-03-27 14:21 UTC, mattcasey approved these changes

2023-03-27 14:22 UTC, mattcasey commented on components/common/PdfSelector/PdfSelector.tsx
> +import { selectorPopupSizeConfig } from '../CharmEditor/components/common/selectorPopupSizeConfig';
looks like PDFSelector should be inside CharmeDitor actually :P

2023-03-27 15:37 UTC, merged