Person property mention notification
charmverse/app.charmverse.io pull request #1972
Opened 2023-04-04 15:54 UTC by Devorein

[Card](https://app.charmverse.io/charmverse/page-49366552253645923?viewId=2c9d8701-33ff-4c3a-942a-6d403a638565&cardId=02c71c8a-7b1c-4429-9011-1594aae097ec)

2023-04-04 19:54 UTC, mattcasey commented on lib/discussion/getDiscussionTasks.ts
> +      deletedAt: null
we should probably add a 'greater than' filter on createdAt here, so that i dont get notifications for all past blocks?

2023-04-04 20:10 UTC, mattcasey requested changes
see comments

2023-04-06 14:22 UTC, Devorein commented on lib/discussion/getDiscussionTasks.ts
> +        text: `${card.user.username} mentioned you in the card ${card.page.title || 'Untitled'}`,
Notion uses mentioned but `assigned` works much better

2023-04-06 14:25 UTC, Devorein commented on lib/discussion/getDiscussionTasks.ts
> +      deletedAt: null
Ideally you shouldn't get any new notifications as after sending notifications we track them as sent so that we don't send them again, Secondly, what if a page was created 10 days ago but the person property was changed 10 mins ago, filter by `createdAt` greater than yesterday wouldn't work.

2023-04-06 16:47 UTC, Devorein commented on lib/discussion/getDiscussionTasks.ts
> +      deletedAt: null
We have decided to go with `updatedAt` filter

2023-04-06 17:00 UTC, merged