Track wallet address for profile item
charmverse/app.charmverse.io pull request #1980
Opened 2023-04-05 12:52 UTC by Devorein

- [x] remove them when a user no longer has that wallet
- [x] Keep track of wallet address used to gather profile items

2023-04-05 16:41 UTC, mattcasey commented on prisma/schema.prisma
> +  address    String?
change this to "walletAddress"? 'address' might be confused with 'contractAddress' too

2023-04-05 16:42 UTC, mattcasey commented on prisma/schema.prisma
> +  address    String?
rename this to 'walletAddress'? 'address' could be confused with 'contractAddress'

2023-04-05 16:43 UTC, mattcasey commented on scripts/migrations/2023_03_30_add_default_path.ts
this migration should not be deleted

2023-04-05 16:46 UTC, mattcasey commented on scripts/migrations/2023_04_05_add_profile_item_wallet.ts
> +        address: profileItem.user.wallets[0].address,
we should check if a user has more than one wallet. i know of at least one user besides myself with multiple wallets. if they have more than one, i think it's safe to just skip them and not tie the profile items to a wallet

2023-04-05 16:46 UTC, mattcasey commented on pages/api/profile/items.ts
> +  const firstWalletAddress = userWallets?.wallets[0].address;
the wallet address needs to be passed in, let's not assume which address it is. that defeats the purpose of tracking wallet address :P

2023-04-05 16:47 UTC, mattcasey commented on pages/api/profile/items.ts
> +            address: firstWalletAddress
I guess this should actually just be profileItem.address

2023-04-05 16:49 UTC, mattcasey requested changes
It looks like we send profileItems to the frontend for users that don't own the profile items. To be safe, we should add a new unique key to wallets that we can link the profile items to, instead of using wallet addresss as the foreign key

2023-04-05 19:27 UTC, Devorein commented on scripts/migrations/2023_03_30_add_default_path.ts
> -  // const users = await prisma.user.findMany({
As far as I remember ts was complaining, but I will remove the comments and see if it still does the same or not.

2023-04-06 17:49 UTC, mattcasey commented on lib/users/prepopulateUserProfile.ts
> +  user: User & { wallets: Pick<UserWallet, 'address' | 'ensname' | 'id'>[] },
it looks like we only need the 'id' of wallet

2023-04-06 17:51 UTC, mattcasey commented on pages/api/profile/items.ts
> +  if (profileItems.some((profileItem) => !profileItem.walletId || !userWalletIds.includes(profileItem.walletId))) {
i'm not sure this logic is correct... shouldn't it be "profileItem.walletId && !userWallets.includes(profileItem.walletId)"?

2023-04-06 20:44 UTC, mattcasey approved these changes

2023-04-06 21:14 UTC, merged