Custom crypto price
charmverse/app.charmverse.io pull request #236
Opened 2022-03-17 13:39 UTC by motechFR

Display the price of custom cryptos added to payment methods

![image](https://user-images.githubusercontent.com/18669748/158820636-a8a974c5-ff04-412a-90bd-c5b58bedd8e0.png)

2022-03-17 21:27 UTC, mattcasey requested changes

2022-03-17 21:27 UTC, mattcasey commented on components/editor/CryptoPrice.tsx
> +  const [cryptoList, setCryptoList] = useState<string []>([]);
please no space between an interface and `[]`

2022-03-17 21:27 UTC, mattcasey commented on components/editor/CryptoPrice.tsx
> +      Object.entries(paymentMethods)
paymentMethods is now a list, not a map.. i suppose this would not compile once merged to main?

2022-03-17 21:27 UTC, mattcasey commented on components/editor/CryptoPrice.tsx
> +    const symbol = getTokenInfo(paymentMethods, baseCurrency).tokenSymbol as CryptoCurrency;
please use caution when asserting types. Really I think it should only be used if it is 100% true, otherwise we're just covering over what TS is trying to protect us from. In this case,  baseCurrency is passed into the component so there's no guarantee it is valid. It's better to just throw an error in this case, since it's probably not likely but the sooner we can alert to incorrect input the easier it will be to fix

2022-03-17 21:27 UTC, mattcasey commented on components/editor/CryptoPrice.tsx
> +      Object.entries(paymentMethods)
I think this whole block of code can just be written as:
```
import { isTruthy } from 'lib/utilities/types';
...
const [paymentMethods] = usePaymentMethods();
const cryptoList = CryptoCurrencies.concat(
  paymentMethods.map(method => method.contractAddress).filter(isTruthy)
);
```
I also think it's fine to include testnets.. Are they not supported?

2022-03-17 21:27 UTC, mattcasey commented on lib/crypto-price/dataSources/coinMarketCap.ts
> +    fetch(`https://pro-api.coinmarketcap.com/v2/cryptocurrency/quotes/latest?id=${cmcCryptoCurrencyId}&convert=${quote}`, {
Sent you that article this week about organization, and I think this file could go into 'adapters' folder, which captures the code to talk to external layers. Thoughts? I'm not sure i am in love with the idea, but i guess it's nice to know what the external layers are. I'm fine if u wanna leave this here until we have time to discuss general principles

2022-03-18 18:29 UTC, motechFR commented on components/editor/CryptoPrice.tsx
> +  const [cryptoList, setCryptoList] = useState<string []>([]);
Handled in this [change](https://github.com/charmverse/app.charmverse.io/pull/236/commits/09b6af07707e659c3b590b53546b0c82c2b5a360)

2022-03-18 18:47 UTC, motechFR commented on components/editor/CryptoPrice.tsx
> +      Object.entries(paymentMethods)
I have simplified as per your suggestion in this [commit](https://github.com/charmverse/app.charmverse.io/pull/236/commits/c73da265b5c3d7c249a8c17ffc03e395ff5ebe3f)

Testnets ignored as these tokens don't have an inherent market value

2022-03-18 18:55 UTC, motechFR commented on components/editor/CryptoPrice.tsx
> +    const symbol = getTokenInfo(paymentMethods, baseCurrency).tokenSymbol as CryptoCurrency;
I've changed the signature of getPricing to a string in this [commit](https://github.com/charmverse/app.charmverse.io/pull/236/commits/5aba60edad6e50131e1cc32c1fadd8dfe0d2d260)

As we now are passing an undetermined range of crypto symbols to the pricing API, it makes more sense to use this Crypto | string type. See here for changes across the [stack](https://github.com/charmverse/app.charmverse.io/pull/236/commits/5c9c5449d7b7a1f1cea8f64b4f29005f7efdae96)

2022-03-18 19:08 UTC, merged