Discord integration
charmverse/app.charmverse.io pull request #251
Opened 2022-03-21 17:37 UTC by Devorein

1. Click on the account modal on the top right
2. Click on discord `Connect` button
3. After successful Login you'll be redirected to previous url
4. Check the account modal (If you don't have an ENS name the discord username will be shown)
5. Since we don't support custom avatar yet its taken from discord if you have one otherwise the first letter of your address

Places where discord account is being used
1. Bounty reviewer list
2. Bounty assignee and reviewer card
3. `@` inside CharmEditor
4. Account card modal
5.  Current Contributors under `/settings/contributors`

2022-03-21 18:10 UTC, mattcasey requested changes

2022-03-21 18:10 UTC, mattcasey commented on lib/users/getDisplayName.ts
> +  return (<LoggedInUser> user).ensName || discordData ? `${discordData.username}${showDiscriminator ? `#${discordData.discriminator}` : ''}` : shortenHex(user.addresses[0]);
I don't see us using showDiscriminator=true anywhere. Let's just not include discriminator in the username and get rid of the option. make our lives easier.. it's in the JSON if we decide we need to use it one day

2022-03-21 18:18 UTC, mattcasey commented
My requests for the data
- add a new prisma table "DiscordUser" with 'userId' and 'account' columns, userId points to the user table and 'account' is a JSON blob we get from discord.  This is *not* to be read from except on an account settings page. Keeps our payload sizes down and we don't liter our codebase with the data structure from Discord
- add 'username' and 'avatar' to the user profile. these get updated when you connect discord. In the future we'll let you set 'avatar' by uploading an image to S3. This keeps the logic simple everywhere we look at users, since a user should only have one avatar and one username anyway.
- i think you could pull in the 'discordUser' when we call /api/profile, that way you can tell if they've connected discord or not.

2022-03-22 05:24 UTC, Devorein commented on lib/users/getDisplayName.ts
> +  return (<LoggedInUser> user).ensName || discordData ? `${discordData.username}${showDiscriminator ? `#${discordData.discriminator}` : ''}` : shortenHex(user.addresses[0]);
Got it. I will make the necessary changes asap

2022-03-22 05:47 UTC, Devorein commented on adapters/http/index.ts
> +  { headers = {}, noHeaders, skipStringifying }: { headers?: any, noHeaders?: boolean, skipStringifying?: boolean } = {}
Discord's api accepts `application/x-www-form-urlencoded` post body, so I had to use the `URLSearchParams` to construct the body as per [this](https://stackoverflow.com/questions/67365624/discord-ouath2-access-token-grant-type-none-is-not-supported#fromHistory) StackOverflow thread. Also we had to add the skipStringifying option for the same reason

2022-03-22 05:47 UTC, Devorein commented on components/common/page-layout/Account/components/AccountModal/AccountModal.tsx
> +          onClick={async () => {
Got it

2022-03-22 14:12 UTC, mattcasey commented on prisma/schema.prisma
> +  username        String?
perfect!

2022-03-22 17:10 UTC, mattcasey approved these changes

2022-03-22 17:39 UTC, merged