Allow creating and editing workspaces
charmverse/app.charmverse.io pull request #31
Opened 2022-01-28 22:43 UTC by mattcasey

2022-01-28 22:44 UTC, mattcasey commented on pages/[domain]/settings/account.tsx
> +const schema = yup.object({
this is pretty cool... react-hook-form integrates with yup, which offers a lot of nice validation handling and error messages

2022-01-28 22:58 UTC, mattcasey commented on hooks/useSpace.ts
> +  function setSpace (_space: Space | null, silent?: boolean) {
i'm not particularly happy with this method, its talking to localStorage directly.. but it should be much simpler in the future. it is handling side-effects like updating the 'spaces' key in local storage so it doesn't trigger a redraw until we reload

2022-01-29 03:09 UTC, Devorein commented
Right now we allow spaces inside a domain name. I think this would pose a problem for us. What do you think about it?
![image](https://user-images.githubusercontent.com/34683631/151645070-e9abb46d-056e-4d52-a535-69197a8799b3.png)

2022-01-29 03:12 UTC, Devorein commented on pages/[domain]/settings/account.tsx
> +const schema = yup.object({
I agree. Yup is my go-to library both for server-side and client-side validation

2022-01-29 03:19 UTC, Devorein commented on hooks/useSpace.ts
> +  function setSpace (_space: Space | null, silent?: boolean) {
Agreed

2022-01-29 03:25 UTC, Devorein requested changes

2022-01-29 03:25 UTC, Devorein commented on pages/[domain]/settings/workspace.tsx
> +  function deleteWorkspace () {
Shouldn't we remove the data related to space and its pages from localstorage after deleting it?

2022-01-29 04:43 UTC, mattcasey commented on pages/[domain]/settings/workspace.tsx
> +  function deleteWorkspace () {
that is actually happening if you look at useSpace, it's inside of that method right now.

2022-01-29 05:00 UTC, Devorein approved these changes

2022-01-29 05:02 UTC, merged