"Open page in" option for database views
charmverse/app.charmverse.io pull request #3122
Opened 2023-11-17 06:15 UTC by Devorein

### WHAT

### WHY

![image](https://github.com/charmverse/app.charmverse.io/assets/34683631/2c8bf88e-e19b-41f1-83a2-c6aa637359d7)

2023-11-17 17:47 UTC, mattcasey commented on components/[pageId]/DatabasePage/DatabasePage.tsx
> +      updateURLQuery({ viewId: router.query.viewId as string, cardId });
happy to see we're trying to use the normal query for updating state

2023-11-17 17:48 UTC, mattcasey commented on components/[pageId]/DatabasePage/DatabasePage.tsx
> +  const showView = (viewId: string) => {
why did you remove useCallback? I added this to try and avoid the database re-rendering too often. i think it was worth keeping in

2023-11-17 17:52 UTC, mattcasey commented on components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
> +                    addCard={(show) =>
we should memoize all the methods passed to this component

2023-11-17 17:54 UTC, mattcasey commented on components/common/BoardEditor/focalboard/src/components/viewSidebar/viewLayoutOptions.tsx
> +  hideLayoutSelectOptions?: boolean;
this should be "showLayoutOptions".

2023-11-17 18:02 UTC, mattcasey commented on components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx
> +  const { pages, refreshPage } = usePages();
lets just update the serverside query in /pages/[domain]/[pageId]. we are already querying the db whenever u visit, so we could check if the pageId is a UUID and query by page id

2023-11-17 18:04 UTC, mattcasey requested changes
- add back useCallbacks
- instead of looking up page path, because usePages() has performance cost, i'd like to just do lookup by pageId in the server-side lookup in pages/domain/pageId.ts

2023-11-18 09:04 UTC, Devorein commented on components/[pageId]/DatabasePage/DatabasePage.tsx
> +  const showView = (viewId: string) => {
Updated. Initially, I was trying to debug a bug that was due to a stale state, and removed the `useCallbacks`, to check whether that's the issue or not. That came out negative, but I forgot to reinstate those back.

2023-11-18 09:04 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
> +                    addCard={(show) =>
Good point. Updated.

2023-11-18 09:15 UTC, Devorein commented on components/common/CharmEditor/components/inlineDatabase/components/InlineDatabase.tsx
> +  const { pages, refreshPage } = usePages();
That makes sense. Updated.

2023-11-19 05:31 UTC, merged