Blacklist and block user from creating space
charmverse/app.charmverse.io pull request #3126
Opened 2023-11-18 10:48 UTC by Devorein

### WHAT

### WHY
[Card](https://app.charmverse.io/charmverse/blacklist-users-from-creating-spaces-in-charmverse-38505691901904315)

2023-11-20 18:42 UTC, mattcasey commented on components/common/CreateSpaceForm/CreateSpaceForm.tsx
> +  useEffect(() => {
this does'nt need to be an effect, just do:
```
const isBanned = typeof saveError === 'string' && saveError.includes('blocked');

```

2023-11-20 18:44 UTC, mattcasey commented on lib/members/checkUserSpaceBanStatus.ts
> +  spaceIds?: string[];
looks like this should still be required. why would someone call checkUserSpaceBanStatus() without any space Id?

2023-11-20 18:44 UTC, mattcasey commented on lib/users/blacklistUser.ts
> +  if (!user) {
using findUniqueOrThrow() is better

2023-11-20 18:46 UTC, mattcasey commented on lib/users/checkUserBlacklistStatus.ts
> +          discordId: userDiscordId
i think this will always return a user with discordId === null? thats probably why the original method used 'in'

2023-11-20 18:46 UTC, mattcasey requested changes
see comments

2023-11-21 10:23 UTC, Devorein commented on lib/members/checkUserSpaceBanStatus.ts
> +  spaceIds?: string[];
Yikes, nice catch. This was for sure a mistake. Thank you.

2023-11-21 10:24 UTC, Devorein commented on lib/users/blacklistUser.ts
> +  if (!user) {
Updated. Thanks.

2023-11-21 10:32 UTC, Devorein commented on components/common/CreateSpaceForm/CreateSpaceForm.tsx
> +  useEffect(() => {
Good one, removed the state as well.

2023-11-21 10:35 UTC, Devorein commented on lib/users/checkUserBlacklistStatus.ts
> +          discordId: userDiscordId
The original one was an array, but you're right. Updated with the fix.

2023-11-21 11:15 UTC, merged