Disable updating expired invite link
charmverse/app.charmverse.io pull request #3127
Opened 2023-11-18 11:34 UTC by Devorein

### WHAT

### WHY

![image](https://github.com/charmverse/app.charmverse.io/assets/34683631/807ec6ae-5764-40b8-9bb6-b042adbbcbcd)

2023-11-20 18:35 UTC, mattcasey commented on components/settings/invites/components/InviteLinks/components/InviteLinksTable.tsx
> +            const hasExpired =
looks like you can call isOutOfDate() from lib/invites instead of re-writing this logic inline.

2023-11-20 18:36 UTC, mattcasey commented on lib/invites/updateInviteLinkRoles.ts
> +  const hasExpired =
for the future i dont see why this rule needs to be added to the backend. it doesnt really matter to anyone if someone updates a link that is expired.

2023-11-20 18:41 UTC, mattcasey requested changes
M (must): - re-use the logic from our lib to determine expiration. This is a good practice we should always follow when it comes to doing math or translating dates
S (should): - remove restrictions on the backend that dont really matter, as its duplicate work to maintain

2023-11-21 10:11 UTC, Devorein commented on lib/invites/updateInviteLinkRoles.ts
> +  const hasExpired =
Fair point. I will remove this part and the corresponding tests as well.

2023-11-21 10:51 UTC, merged