Fix zora chain nft error and title display
charmverse/app.charmverse.io pull request #3129
Opened 2023-11-18 13:23 UTC by valentinludu

Fix:
- zora was not on the LIT_CHAINS list
- zora tokenId was sent as a number instead of a string. The ZDK was throwing an error.
- nft titles

2023-11-18 13:54 UTC, Devorein approved these changes

2023-11-18 16:50 UTC, mattcasey commented on lib/blockchain/provider/zora/getNFT.ts
> +      tokenId: String(tokenId)
why do we do this? looks like a hack

2023-11-18 16:52 UTC, mattcasey commented on lib/blockchain/provider/zora/getNFT.ts
> +      tokenId: String(tokenId)
i guess we're doing it for ankr too 🤷

2023-11-18 16:56 UTC, mattcasey commented on lib/tokenGates/utils.ts
> +const zoraChain = {
please import from connectors/chains instead. we may replace a lot of it with wagmi eventually but at least for now we are consistent where all the details are coming from. they're not 100% wagmi right now

2023-11-18 16:57 UTC, mattcasey requested changes
- always import chain config from connections/chains. this makes sure we're using the same config everywhere

2023-11-18 16:57 UTC, mattcasey commented on lib/tokenGates/utils.ts
> +const baseChain = {
this is a config file, it doesnt really belong in a "utils" file. please put it in a constants.ts or config.ts

2023-11-19 21:45 UTC, valentinludu commented on lib/blockchain/provider/zora/getNFT.ts
> +      tokenId: String(tokenId)
Condition parameters can be number | string and I did not know because the type was 'any'. Now I am inforcing the String() where I search for the parameters, instead of here.

2023-11-20 16:03 UTC, mattcasey approved these changes
talked about it and its fine to import wagmi config directly

2023-11-20 16:20 UTC, merged