Fixed text filter for title property
charmverse/app.charmverse.io pull request #3136
Opened 2023-11-19 15:02 UTC by Devorein

### WHAT

### WHY

[Card](https://app.charmverse.io/charmverse/db-title-text-filter-does-not-work-as-expected-5834628543749347)

2023-11-20 19:06 UTC, mattcasey requested changes
i'd like to avoid adding pages into the selectors - pretty sure this will have negative effects on performance. if we are going to use page context, it should probably be added to Redux as a new store and not passed in as a prop.

But we already add the page titles to cards in the CetnerPanel compoentn - isn't this enough? https://github.com/charmverse/app.charmverse.io/blob/main/components/common/BoardEditor/focalboard/src/components/centerPanel.tsx#L148

If not, i'd like to take a step back and do it properly by adding pages to redux instead of adding another workaround. this would help performance of db's too i think

2023-11-21 13:48 UTC, Devorein commented
`[main/components/common/BoardEditor/focalboard/src/components/centerPanel.tsx#L148](https://github.com/charmverse/app.charmverse.io/blob/main/components/common/BoardEditor/focalboard/src/components/centerPanel.tsx?rgh-link-date=2023-11-20T19%3A06%3A46Z#L148)`

This adds the title property after the filter is done, so if the filter contains a title-based clause then the card won't even reach to that stage

2023-11-22 09:58 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/svg/dashboard-onboarding.tsx
This component was unused

2023-11-22 09:58 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/svg/search-illustration.tsx
This component was also unused

2023-11-22 11:49 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/components/viewHeader/filterComponent.tsx
> +      <Button
Removed redundant margin-top for filter
![image](https://github.com/charmverse/app.charmverse.io/assets/34683631/81a56e48-93ac-49cc-955b-9c1649a7b16d)

2023-11-22 13:58 UTC, Devorein commented on pages/_app.tsx
> +                                  </FocalBoardProvider>
FocalboardProvider needs to wrap PagesProvider, otherwise `useAppDispatch` is not available inside `usePages`

2023-11-22 14:03 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/store/cards.ts
> +    });
This is a bit of a hack. Stored another pagesMap in the slice of cards, the reason being its not possible to know which will thunk will be fulfilled first, `pagesLoad` or `initialDatabaseLoad`. So state.cards might be empty when pages are loaded in redux state, which means no cards will have its title property overriden and vice versa. We can remove this if we don't plan to keep the card title updated with the page title on initial load, or there could be a much more efficient way.

2023-11-24 07:12 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/components/centerPanel.tsx
> +import { useSWRConfig } from 'swr';
Updated. Thnx.

2023-11-24 07:12 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/store/cards.ts
> +          if (cardPages) {
Removed this part of code after our discussion tmrw.

2023-11-24 11:44 UTC, merged