Handle exporting empty database pages without throwing error
charmverse/app.charmverse.io pull request #3170
Opened 2023-11-25 13:13 UTC by Devorein

### WHAT

### WHY

1. Fix the exported zip name. Previously it was `.zip.zip`
2. Pass an empty prosemirror document to `BangleEditorState` if there is no content, rather than passing an empty string, as otherwise it would try use dom methods (which are not present in node env) and throw error.

2023-11-25 17:53 UTC, mattcasey commented on components/common/CharmEditor/components/@bangle.dev/core/bangle-editor-state.ts
> +  if (typeof content === 'string' && typeof window !== 'undefined') {
in what situation are we using the bangle editor state outside of a browser?

2023-11-25 17:54 UTC, mattcasey commented on lib/prosemirror/plugins/markdown/generateMarkdown.ts
> +    initialValue: content ? Node.fromJSON(specRegistry.schema, content) : emptyDocument,
bangle editor state seems to already include emptyDocument. i want to avoid needing this in as many places as possible, if it's needed at all...

2023-11-25 17:55 UTC, mattcasey requested changes
left some questions

2023-11-25 18:13 UTC, motechFR commented on components/common/CharmEditor/components/@bangle.dev/core/bangle-editor-state.ts
> +  if (typeof content === 'string' && typeof window !== 'undefined') {
We are using the editor state here in 

lib/prosemirror/plugins/markdown/generateMarkdown.ts

So we can generateMarkdown on the server side. Agree it would be nice not to import from a /components folder to the server

2023-11-25 18:15 UTC, motechFR commented on lib/prosemirror/plugins/markdown/generateMarkdown.ts
> +    initialValue: content ? Node.fromJSON(specRegistry.schema, content) : emptyDocument,
Reverted this to undefined, doesn't seem to generate error anymore

2023-11-26 09:58 UTC, Devorein commented on components/common/CharmEditor/components/@bangle.dev/core/bangle-editor-state.ts
> +  if (typeof content === 'string' && typeof window !== 'undefined') {
When we export a full database, we make an api call to our backend to provide the csv + .md files in a zip format.

2023-11-27 17:24 UTC, mattcasey approved these changes

2023-11-29 13:58 UTC, merged