Show breadcrumb of pages on header
charmverse/app.charmverse.io pull request #319
Opened 2022-04-04 16:21 UTC by Devorein

1. Each link is separated by a / (backslash)
2. If there are more than 3 links, just show the first, the one before the last and the last one (current page), the rest are shown via an ... (ellipsis)
3. Otherwise show all of them (for 1, 2, and 3 levels of nesting)
4. Each of the previous links can be navigated by clicking on them
5. We show the icon and title of each link and it kept up to date with the state

2022-04-04 17:09 UTC, mattcasey requested changes
- use the existing breadcrumb components to maintain style consistency
- simplify linked pages logic and put into Header file
- bug: when I create a new page, the new page doesn't appear in the list (i think this will be solved if you replace the linked pages logic)

2022-04-04 17:09 UTC, mattcasey commented on components/common/PageLayout/components/Header.tsx
> +  const trailsInfo = (trimTrails ? [pages[0], {
cleaner way to write this:
```
const splitCrumb = {
  title: '...',
  path: null,
  icon: null,
  id: '123'
}
const displayedPages = trimTrails ? [pages[0], splitCrumb, pages[pages.length - 2], pages[pages.length - 1]] : pages;
return ( ... );
```

2022-04-04 17:09 UTC, mattcasey commented on components/common/PageLayout/components/Header.tsx
> +    title: page.title,
this map looks unecessary ( all the properties are the same?)

2022-04-04 17:09 UTC, mattcasey commented on components/common/PageLayout/components/Header.tsx
> +          <Fragment key={trailInfo.id}>
this should be the Breadcrumb component

2022-04-04 17:09 UTC, mattcasey commented on components/common/PageLayout/components/Header.tsx
> +        const pageDeco = (
i wasn't sure what pageDeco meant. A better name for this could be "currentPageCrumb" or something like that?

2022-04-05 13:04 UTC, Devorein commented on components/common/PageLayout/components/Header.tsx
> +        return trailInfoIndex !== trailsInfo.length - 1 ? (
You are right. I've fixed it in the latest commits

2022-04-05 13:07 UTC, Devorein commented on components/common/PageLayout/components/Header.tsx
> +  const trailsInfo = (trimTrails ? [pages[0], {
Done

2022-04-05 13:07 UTC, Devorein commented on components/common/PageLayout/components/Header.tsx
> +          <Fragment key={trailInfo.id}>
Yes I replaced it in the latest commit

2022-04-05 13:07 UTC, Devorein commented on components/common/PageLayout/components/Header.tsx
> +        const pageDeco = (
Makes sense. I've changed it in the latest commit

2022-04-05 13:09 UTC, Devorein commented
You are right about the algorithm to find the trail of parents of a page, I went overboard with that logic. Fixed it to be much much simpler in the latest commit.

2022-04-05 13:14 UTC, Devorein commented on hooks/usePages.tsx
> +  const linkedPages = useMemo(() => {
You are right about the algorithm to find the trail of parents of a page, I went overboard with that logic. Fixed it to be much much simpler in the latest commit.

2022-04-05 14:34 UTC, mattcasey commented on components/common/PageLayout/components/Header.tsx
> +              <span className='breadcrumb-slash'>/</span>
why did you need to add this? the "/" was being added by CSS already

2022-04-05 16:26 UTC, mattcasey commented on components/common/PageLayout/components/Header.tsx
> +        // Last item doesn't have any /
i originally just printed out the last item (the current page). i think that's cleaner than adding to the list here,there's no reason it should link to itself, have a breadcrumb slash, etc. can we keep it how it was?

2022-04-05 16:29 UTC, mattcasey commented on components/common/PageLayout/components/Header.tsx
> +  const { bounties } = useBounties();
there is'nt a need to get the bounties. we have the current page title already

2022-04-05 16:30 UTC, mattcasey commented on components/common/PageLayout/components/Header.tsx
> +            {router.route === '/[domain]/bounties/[bountyId]' ? <BountyBreadcrumbs /> : router.route === '/[domain]/[pageId]' ? <PageBreadcrumbs pages={currentPageChain} /> : null}
i prefered this inside a component like i originally had

2022-04-05 16:40 UTC, mattcasey commented on components/common/PageLayout/components/Header.tsx
> -import { usePageTitle } from 'hooks/usePageTitle';
we need to keep using this, it's used by settings and possible other pages

2022-04-05 19:42 UTC, closed without merging