Required member properties during onboarding
charmverse/app.charmverse.io pull request #3193
Opened 2023-11-28 15:10 UTC by Devorein

### WHAT

### WHY

[Card](https://app.charmverse.io/charmverse/onboarding-flow-for-required-member-properties-9749073104970365?domain=charmverse&pageId=page-9749073104970365)

2023-11-29 22:41 UTC, mattcasey commented on components/_app/components/OnboardingEmailForm.tsx
> +          <Button loading={isMutating} data-test='member-email-next' type='submit' disabled={!isValid}>
nice cleanup, dunno why i didn't use isValid before

2023-11-29 22:43 UTC, mattcasey commented on components/_app/components/UserOnboardingDialog.tsx
> +  if (!user || !space) {
not sure this check was really needed. useOnboarding works with an undefined spaceId too, we only need it when you close the popup. but it probably doesn't matter too much either

2023-11-29 22:45 UTC, mattcasey commented on components/_app/components/UserOnboardingDialog.tsx
> +  useEffect(() => {
thanks for wrapping this in useEffect

2023-11-29 22:48 UTC, mattcasey commented on components/members/hooks/useRequiredMemberProperties.ts
> +export function useRequiredMemberProperties({ userId }: { userId: string }) {
you have us pass in "userId" but then you retrieve spaceId from useCurrentSpace(). Please pick one or the other approach for getting the details... if it were me i would just call useUser() here, and not have to pass userId in at all

2023-11-29 22:51 UTC, mattcasey commented on components/members/hooks/useRequiredMemberProperties.ts
> +  const requiredPropertiesWithoutValue = useMemo(() => {
this value could just be a boolean - everywhere we use it we just check for .length

2023-11-29 22:56 UTC, mattcasey commented on components/members/hooks/useRequiredMemberProperties.ts
> +  const memberProperties = useMemo(
I don't think these useMemo's do anything and you should probably remove them. They can really complicate state - for example, in useThreads, the useMemo was causing values to be out of sync with ones that came from elsewhere, where because the value from useMemo is only calculated after the initial render.

2023-11-29 22:58 UTC, mattcasey commented on components/members/hooks/useRequiredMemberProperties.ts
> +    [memberPropertyValues, currentSpace?.id]
On line 14, memberPropertyValues is always being recreated as a new empty array if there's no value. You should change that so that it does not constantly retrigger useMemo here

2023-11-29 23:07 UTC, mattcasey commented on components/common/BoardEditor/focalboard/src/components/dialog.tsx
> -  ${({ theme }) => theme.breakpoints.up('md')} {
Please leave this here, other dialogs depend on the padding matching the normal page width. It looks like member onboarding uses a special "fluidSize" which is why the button no longer lines up. So I think Dialog could adjust the padding here based on  the fluidSize prop.

2023-11-29 23:13 UTC, mattcasey requested changes
- Please do not merge this with changes to name, until Alex/Chris I meet on Friday. If you can just undo those changes, and leave name as a regular property for now it would be better
- If we do go with a universal name it will probably be user.username. Why did you want to add it to UserDetails?

2023-11-29 23:13 UTC, mattcasey commented on components/_app/components/UserOnboardingDialog.tsx
> +          <Box mr={4.5}>
i mentioned elsewhere but the dialog component should just adjust its footer spacing when fluidSize is true

2023-11-29 23:16 UTC, mattcasey commented on components/members/hooks/useRequiredMemberProperties.ts
> +      propertiesWithoutValue = [...propertiesWithoutValue, 'timezone'];
why not just propertiesWithoutValue.push()? it's easier to read

2023-11-29 23:17 UTC, mattcasey commented on components/members/hooks/useRequiredMemberProperties.ts
> +    if (isTimezoneRequired && !userDetails?.timezone && !isLoading) {
seems like u could jsut check isLoading first and return early

2023-11-29 23:18 UTC, mattcasey commented on components/members/hooks/useRequiredMemberProperties.ts
> +        // Handled by oauth
these aren't actually handled by oauth yet?

2023-11-29 23:19 UTC, mattcasey commented on components/members/hooks/useRequiredMemberProperties.ts
> +    const isTimezoneRequired = requiredProperties.find((p) => p.type === 'timezone')?.required;
should use .some() instead of .find()

2023-11-29 23:21 UTC, mattcasey commented on components/members/hooks/useRequiredMemberProperties.ts
> +  const requiredProperties = useMemo(
requiredProperties might work better as a map, most of the time you're looking for certain types

2023-11-29 23:22 UTC, mattcasey commented on components/members/hooks/useRequiredMemberProperties.ts
> +  const memberProperties = useMemo(
another simplification could be to just wrap the whole response object with useMemo(). I did this in use useCharmRouter

2023-11-29 23:25 UTC, mattcasey commented on components/settings/profile/components/UserDetailsForm.tsx
> +    setForm({
Since this watches and resets the value whenever defaultUserDetails changes, is the 'userDetails' state even necessary? can you just use `defaultUserDetails` directly

2023-11-30 07:01 UTC, Devorein commented on components/_app/components/UserOnboardingDialog.tsx
> +  if (!user || !space) {
Yeah and we had a condition downward to return null if no space is present.

2023-11-30 07:06 UTC, Devorein commented on components/members/hooks/useRequiredMemberProperties.ts
> +export function useRequiredMemberProperties({ userId }: { userId: string }) {
The reason being `useMemberPropertyValues` requires an `userId` to be passed, using `useUser` will cause it to also take in `undefined` as a value.

2023-11-30 07:08 UTC, Devorein commented on components/members/hooks/useRequiredMemberProperties.ts
> +    [memberPropertyValues, currentSpace?.id]
Ow I didn't realize that. Thnx for pointing it out. Updated.

2023-11-30 07:14 UTC, Devorein commented on components/members/hooks/useRequiredMemberProperties.ts
> +  const requiredProperties = useMemo(
If we use the memberPropertyId as the key, the we would need to find the id of the member property that we want to check the required status first, which would require another loop, if we use the type there could be duplicates, having a key as the type and value as an array of properties would also be redundant if we want to check a specific property with specific id. We are checking the required status of mostly the user level properties i.e bio and timezone, so I can just return them from this hook.

2023-11-30 07:15 UTC, Devorein commented on components/members/hooks/useRequiredMemberProperties.ts
> +  const requiredPropertiesWithoutValue = useMemo(() => {
Agree. Updated.

2023-11-30 07:17 UTC, Devorein commented on components/members/hooks/useRequiredMemberProperties.ts
> +          !['bio', 'timezone'].includes(rp.type)
timezone and bio are user-level properties and they are handled in separate components and states where they are used. Consolidating the states is also quite difficult as they need to be sent to two different endpoints. While role and joined_at are not really editable by the member. I should've added a bit of comment on top of those to make it clearer.

2023-11-30 08:31 UTC, Devorein commented on components/members/hooks/useRequiredMemberProperties.ts
> +      propertiesWithoutValue = [...propertiesWithoutValue, 'timezone'];
That was causing issue for some reason. I spent almost half an hour trying to figure out why thats the case. ended up using this less formal method.

2023-11-30 08:32 UTC, Devorein commented on components/members/hooks/useRequiredMemberProperties.ts
> +        // Handled by oauth
Not yet but they will be in the near future, so I'm leaving these out from being required for now.

2023-11-30 08:36 UTC, Devorein commented on components/members/hooks/useRequiredMemberProperties.ts
> +  const memberProperties = useMemo(
Updated to make use of a single `useEffect`, in terms of the other deps, removed those as well and its working fine.

2023-11-30 08:47 UTC, Devorein commented on components/settings/profile/components/UserDetailsForm.tsx
> +    setForm({
`isInputValid` depends on the `userDetails` state, and that is kept upto date using the `setForm` fn. Otherwise `defaultUserDetails` would be a static value always.

2023-11-30 08:52 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/components/dialog.tsx
> -  ${({ theme }) => theme.breakpoints.up('md')} {
Ahh gotcha. I will fix it for `UserOnboardingDialog` then

2023-12-01 10:52 UTC, merged