Database table rows selection
charmverse/app.charmverse.io pull request #3254
Opened 2023-12-11 16:19 UTC by Devorein

### WHAT

### WHY

2023-12-11 16:25 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/components/table/calculation/calculationRow.scss
> +    background-color: rgba(var(--center-channel-color-rgb), 0.05);
This might now be the correct css variable but hovering hover the calculation cells in the footer should highlight them (notion)

2023-12-11 16:33 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/components/table/tableRow.scss
> -  &:hover {
Removed hover style on table rows (notion)

2023-12-11 16:34 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/components/viewHeader/viewHeader.scss
> +  @media (max-width: 768px) {
This shows the select property section about the view options in mobile view. Not sure how to do this in a better manner.
![image](https://github.com/charmverse/app.charmverse.io/assets/34683631/cd26107a-400c-4822-832f-04fe473cea4c)

2023-12-11 16:39 UTC, Devorein commented on charmClient/charmClient.ts
> +  createEvents({ payload, spaceId }: { spaceId: string; payload: CreateEventPayload[] }) {
Pluralized since it can create multiple events in one go now.

2023-12-11 16:39 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/components/calculations/calculation.tsx
> +      {value === Options.none.value && <ExpandMoreIcon fontSize='small' />}
Notion uses expand more.

2023-12-11 16:42 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/components/table/tableHeader.tsx
> +        backgroundColor: isOver ? 'var(--charmeditor-active)' : ''
This was stopping the hover effect to take place inside the table header cells (notion)

2023-12-11 16:43 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx
> +          background: 'rgba(35, 131, 226, 0.14)',
Taken from notion, maybe we should use our select color variable?

2023-12-12 05:58 UTC, mattcasey commented on pages/api/blocks/index.ts
> +  const blockIds = typeof queryBlockIds === 'string' ? [queryBlockIds] : queryBlockIds;
thx for fixing

2023-12-12 06:01 UTC, mattcasey commented on pages/api/spaces/[id]/event.ts
> +  const events = req.body as CreateEventPayload[];
you should check this is an array so that we don't break requests with the previous code

2023-12-12 10:25 UTC, Devorein commented on pages/api/spaces/[id]/event.ts
> +  const events = req.body as CreateEventPayload[];
Yes, it only affects notifications, and it's a lot more optimal. Otherwise, we will have to send M x N API requests where N is the number of persons selected and M being the number of cards updated

2023-12-12 15:35 UTC, mattcasey commented on charmClient/charmClient.ts
> +    const rootBlocks = await http.DELETE<Block[]>(`/api/blocks`, { blockIds });
nice catch

2023-12-13 09:50 UTC, msadura commented on components/common/BoardEditor/components/properties/TagSelect/TagSelect.tsx
> +  useEffect(() => {
if you want to keep state in parent then internal isOpened state for this compoennt does not make sense

2023-12-13 09:51 UTC, msadura commented on components/common/BoardEditor/components/properties/UserSelect.tsx
> +  open?: boolean;
in previous file there is `isOpen`, `isOpened` and here it is `open` - would be nice to stick to some convention

2023-12-13 09:52 UTC, msadura commented on components/common/BoardEditor/components/properties/UserSelect.tsx
> +  useEffect(() => {
same again - why making redundant states?

2023-12-13 10:01 UTC, msadura commented on components/common/BoardEditor/focalboard/src/components/table/table.tsx
> +  const selectionContextValue = useMemo(() => {
this const does not make sense here. You are wrapping things returned from a hook with additional layer of complexity, while you could do:
`const selectionContext = useAreaSelection({ readOnly, container: selectContainerRef });`

and you can use it the same way. If you need memoized value then `useAreaSelection` should do that

2023-12-15 10:32 UTC, msadura requested changes
just small polishes and will be ready to go

2023-12-16 11:12 UTC, Devorein commented on components/common/BoardEditor/components/properties/TagSelect/TagSelect.tsx
> +  useEffect(() => {
The open state is managed by the component itself, but isOpen is provided to initial value of the state. I will remove useEffect since its redundant.

2023-12-16 11:23 UTC, Devorein commented on components/common/BoardEditor/components/properties/UserSelect.tsx
> +  open?: boolean;
Converted everything to `opened` to indicate the initial state of the `isOpen` internal state

2023-12-16 11:25 UTC, Devorein commented on components/common/BoardEditor/components/properties/UserSelect.tsx
> +  useEffect(() => {
This is for the initial value of the internal state, remove the `useEffect`

2023-12-16 11:30 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/components/table/table.tsx
> +  const selectionContextValue = useMemo(() => {
Updated

2023-12-19 13:24 UTC, msadura approved these changes

2023-12-24 13:44 UTC, merged