Edit proposal reviewers from proposals table
charmverse/app.charmverse.io pull request #3333
Opened 2023-12-30 22:41 UTC by Devorein

### WHAT

### WHY

2023-12-31 19:26 UTC, mattcasey commented on charmClient/apis/proposalsApi.ts
> +  updateProposalEvaluation({ proposalId, ...payload }: UpdateEvaluationRequest) {
please do not add any more methods to charmClient. We already have `useUpdateProposalEvaluation` hook, please use that instead

2023-12-31 19:29 UTC, mattcasey commented on components/common/BoardEditor/components/properties/UserAndRoleSelect.tsx
> +  const showDeleteIcon = (disallowEmpty && value.length !== 1) || !disallowEmpty;
This is poor UX - it forces the user to add what they need before they can remove what they don't want. Instead, I think we should add a standard prop "required" and highlight it in red if it's empty, and then dont save it until there is a value

2023-12-31 19:31 UTC, mattcasey commented on components/common/BoardEditor/components/properties/UserAndRoleSelect.tsx
> +  disallowEmpty = false
we already have a 'required' field. please use that instead, and just don't save the update  if there are no values

2023-12-31 19:35 UTC, mattcasey commented on components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
> +            await charmClient.proposals.updateProposalEvaluation({
needs a try/catch in case it fails

2023-12-31 19:36 UTC, mattcasey commented on components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
> +          const evaluationId =
this line doesn't make any sense. `proposalWithEvaluation.currentEvaluationId` is already a string or undefined. Just do:
```
const evaluationId = proposalWithEvaluation.currentEvaluationId
```

2023-12-31 19:38 UTC, mattcasey commented on components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
> +            await mutate(`/api/spaces/${board.spaceId}/proposals`);
TODO: websockets for proposal list :)

2023-12-31 19:44 UTC, mattcasey commented on components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx
> +  proposal?: ProposalWithUsers;
this is going to rerender every row whenever you update proposals. Instead it looks like we only need to pass in proposalId and currentEvaluationId. Please update

2023-12-31 19:48 UTC, mattcasey commented on lib/focalboard/card.ts
> +  proposal?: ProposalWithUsers;
change this to proposalId and currentEvaluationId. These objects should be as simple as possible to avoid rerendering large tables

2023-12-31 19:51 UTC, mattcasey commented on components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalsBoardAdapter.ts
> +  const { proposals = [] } = useProposals();
its ususally better not to have a default. when you're workign with code its good to have to think about things loading

2023-12-31 19:53 UTC, mattcasey requested changes
left comments, primarily i don't think we should pass the entire proposal object around when we only need the ids

2023-12-31 20:00 UTC, mattcasey commented on lib/focalboard/card.ts
> +  proposal?: ProposalWithUsers;
In fact, I think you may only need to add currentEvaluationId, since PageMeta already includes the proposalId?

2024-01-01 07:15 UTC, Devorein commented on charmClient/apis/proposalsApi.ts
> +  updateProposalEvaluation({ proposalId, ...payload }: UpdateEvaluationRequest) {
Right, updated. I will use the hooks from now on.

2024-01-01 07:22 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
> +          const evaluationId =
Trimmed the proposal object to only have currentEvaluationId and id

2024-01-01 07:23 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/components/propertyValueElement.tsx
> +            await mutate(`/api/spaces/${board.spaceId}/proposals`);
Added a task card in backlog

2024-01-01 07:27 UTC, Devorein commented on lib/focalboard/card.ts
> +  proposal?: ProposalWithUsers;
Yep good idea, updated.

2024-01-03 19:39 UTC, mattcasey approved these changes

2024-01-03 20:20 UTC, merged

2024-01-03 22:45 UTC, mattcasey commented on lib/focalboard/card.ts
> +  proposal?: ProposalWithUsers;
@Devorein not sure you actually updated this, 'proposal' is still an object, so it will re-render all the time still. The problem is we're recreating the 'proposal' property every time proposals are updated

2024-01-03 22:46 UTC, mattcasey commented on lib/focalboard/card.ts
> +  proposal?: ProposalWithUsers;
I don't think the update really addresses what I meant, 'proposal' should not be an object we re-create all the time. but we're doing it for the card too... the useProposalsBoardAdapter hook is just not set up correctly