Clean search-domain API for faster loads
charmverse/app.charmverse.io pull request #3378
Opened 2024-01-05 11:44 UTC by valentinludu

Clean search-domain API for faster loads

2024-01-05 14:07 UTC, msadura approved these changes

2024-01-05 15:39 UTC, mattcasey requested changes
can the frontend be changed so that we dont mutate the state of another api request? this can be overridden

2024-01-08 13:29 UTC, valentinludu commented
Done!

> can the frontend be changed so that we dont mutate the state of another api request? this is not foolproof and can be overridden

2024-01-08 22:01 UTC, mattcasey requested changes
We still are kind of combining space and token gates into one object with i think will result in bugs. I would question if we even nee to return tokenGates in the spaces context anymore, and could get rid of the SpaceWithGates interface. This would highlight some other areas we need to address including these components that use `SpaceAccessGate: SpaceAccessGateWithSearch and RewardSignupButton. It seems like SpaceAccessGate ought to be able to just query token gates on its own?

2024-01-08 22:04 UTC, mattcasey commented on charmClient/hooks/tokenGates.ts
> +export function useGetTokenGates(spaceId: string, spaceDomain?: string) {
i dont see a need to also query by spacedomain, please remove this and only use spaceId

2024-01-08 22:07 UTC, mattcasey requested changes
I think there are other places where we get token gates, also please see if you can kill the SpaceWIthGates interface

2024-01-09 12:57 UTC, valentinludu commented
Killed it!
We did not need to load a space with gates anywhere.
The only place we need token gates list is the join page. Now, the search-domain and search-name responses are lighter and faster!

> I think there are other places where we get token gates, also please see if you can kill the SpaceWIthGates interface

2024-01-09 13:23 UTC, valentinludu commented on charmClient/hooks/tokenGates.ts
> +export function useGetTokenGates(spaceId: string, spaceDomain?: string) {
Done

2024-01-09 20:52 UTC, mattcasey approved these changes

2024-01-09 20:52 UTC, mattcasey reviewed
cleanup looks good

2024-01-10 09:08 UTC, merged