Token Gate Modal Storybook
charmverse/app.charmverse.io pull request #3394
Opened 2024-01-08 15:53 UTC by valentinludu

2024-01-08 17:58 UTC, mattcasey commented on components/common/TokenGateModal/components/TokenGateBlockchainSelect.tsx
> +        ref={ref}
why was adding this necessary?

2024-01-08 17:58 UTC, mattcasey approved these changes

2024-01-08 18:02 UTC, mattcasey requested changes
one request about storybook organization

2024-01-08 19:35 UTC, valentinludu commented on stories/TokenGate/TokenGate.stories.tsx
> +  title: 'tokengate/Token Gate',
Moved!

2024-01-08 19:39 UTC, valentinludu commented on components/common/TokenGateModal/components/TokenGateBlockchainSelect.tsx
> +        ref={ref}
MUI was always throwing errors inside TokenGateBlockchainSelect because I was wrapping an MUI component without a ref.

The error is: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

More info here:
Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

2024-01-08 19:39 UTC, valentinludu commented
> one request about storybook organization

Done

2024-01-10 15:39 UTC, mattcasey approved these changes

2024-01-11 08:35 UTC, merged