Notion import v4
charmverse/app.charmverse.io pull request #346
Opened 2022-04-11 15:18 UTC by Devorein

2022-04-11 21:03 UTC, mattcasey requested changes

2022-04-11 21:03 UTC, mattcasey commented on components/common/CharmEditor/components/ResizableIframe.tsx
> +import { extractEmbedLink } from 'lib/embed/extractEmbedLink';
atechnically i think we can leave any code inside CharmEditor, since Mo needs to import all the Charm plugins to be able to seriealize the JSON to markdown. But excluding all the focalboard will still be a win

2022-04-11 21:04 UTC, mattcasey commented
I think I addressed my points in this PR, but please check: https://github.com/charmverse/app.charmverse.io/pull/347

2022-04-12 11:03 UTC, Devorein commented on components/common/CharmEditor/components/ColumnBlock.tsx
> -  &:hover {
Notion doesn't have this style. Plus it overrides styles of some block so their background is not shown

2022-04-12 11:14 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/components/gallery/galleryCard.tsx
> +    let galleryImageUrl: null | string = card.fields.headerImage;
Thank you. I've notified him about it.

2022-04-12 11:15 UTC, Devorein commented on components/common/CharmEditor/components/ResizableIframe.tsx
> +import { extractEmbedLink } from 'lib/embed/extractEmbedLink';
I feel we can still do better. We only need the plugins and not any other stuff like functions and components, we can move the plugin factories inside the lib and maybe use those instead?

2022-04-12 11:17 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/components/sidebar/sidebarAddBoardMenu.tsx
> +    const board = createBoard(undefined, true)
I agree. Sorry for that. I will fix it asap

2022-04-12 11:28 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/components/cardDialog.tsx
> +                      router.push(`/${space.domain}/${pages[card.id]!.path}`)
Yes you are right about `router.query.domain`. I keep forgetting about that. And thank you I will use our common button component from now on.

2022-04-12 11:34 UTC, Devorein commented on components/common/PageLayout/components/PageNavigation.tsx
> -      roots.push(node);
I didn't understand the logic properly that's why I added unnecessary conditions. Thank you for the fix in the PR.

2022-04-12 16:53 UTC, Devorein commented on components/common/CharmEditor/components/ColumnBlock.tsx
> -  &:hover {
Its been reverted back in the latest commit

2022-04-12 18:40 UTC, mattcasey approved these changes

2022-04-13 13:53 UTC, merged