Support for strike and underline text formatting
charmverse/app.charmverse.io pull request #36
Opened 2022-01-30 12:06 UTC by Devorein

Strike and underline formats are now supported
![image](https://user-images.githubusercontent.com/34683631/151698891-2751c14b-b005-44eb-b51f-81d01daec80c.png)

Updated code styling to resemble that of notion
![image](https://user-images.githubusercontent.com/34683631/151698918-b80b54da-c9f7-4d50-bf2f-b9e5951307c3.png)

2022-01-30 23:38 UTC, mattcasey commented on theme/index.ts
> +        color: "#EB5757"
theres really no reason to add it to the palette here unless you're handling dark and light mode..

2022-01-30 23:39 UTC, mattcasey commented on components/editor/BangleEditor.tsx
> +    background-color: ${({ theme }) => theme.palette.mode === "dark" ? sidebarBackgroundColorDarkMode : sidebarBackgroundColor};
I believe this line can just be `({ theme }) => theme.palette.sidebar.background`

2022-01-30 23:41 UTC, mattcasey requested changes
i think this is mixing up a few ways to import colors, but i would recommend:
```
code: {
      background: mode === 'dark' ? darkBgColor : lightBgColor,
      foreground: mode === 'dark' ? darkColor : lightColor
}
 ```

2022-01-31 04:27 UTC, Devorein commented on theme/index.ts
> +        color: "#EB5757"
But then if we want to use this color at other places we would have to copy the same hex value, and more importantly what if we decide to change it in the future. I guess we can do a search and replace in VsCode but don't you think it's a bit better to keep it in a central place?

2022-01-31 04:29 UTC, Devorein commented on components/editor/BangleEditor.tsx
> +    background-color: ${({ theme }) => theme.palette.mode === "dark" ? sidebarBackgroundColorDarkMode : sidebarBackgroundColor};
This is actually handled in the #35 PR. I've attached two more properties to the `background` interface to handle a lighter and darker version of our base background color.

2022-01-31 05:09 UTC, mattcasey commented on components/editor/BangleEditor.tsx
> +    background-color: ${({ theme }) => theme.palette.mode === "dark" ? sidebarBackgroundColorDarkMode : sidebarBackgroundColor};
I like what you did in the other PR as well! that's what i was trying to get at, thanks

2022-01-31 05:10 UTC, mattcasey approved these changes

2022-01-31 05:34 UTC, merged