Remove Profile form from Settings modal
charmverse/app.charmverse.io pull request #3714
Opened 2024-02-27 09:21 UTC by Devorein

### WHAT

### WHY

[Card](https://app.charmverse.io/charmverse/remove-profile-form-from-settings-modal-006326267268503605)

2024-02-27 21:58 UTC, mattcasey commented on components/_app/GlobalComponents.tsx
> +      <EditMemberProfileDialogGlobal />
can you make this part of te same modal? when i toggle between them there is a flicker of the backdrop. it's the view/edit of the profile so doesnt seem like we need two modals

2024-02-27 21:58 UTC, mattcasey requested changes
can you make this part of the same modal as MemberProfile? when i toggle between them there is a flicker of the backdrop. it's the view/edit of the profile so doesnt seem like we need two modals

2024-02-27 21:59 UTC, mattcasey commented on components/common/PageLayout/components/Sidebar/components/SidebarSubmenu.tsx
> +        {user && (
why do we have to check if user exists?

2024-02-28 12:25 UTC, Devorein commented on components/common/PageLayout/components/Sidebar/components/SidebarSubmenu.tsx
> +        {user && (
Updated

2024-02-28 13:07 UTC, Devorein commented on components/members/components/MemberDirectoryGalleryView.tsx
> +    setIsOpen(true);
Good point, updated in the refactor

2024-02-28 13:36 UTC, merged