Rewards submissions public endpoint
charmverse/app.charmverse.io pull request #3793
Opened 2024-03-13 15:14 UTC by Devorein

### WHAT

### WHY

[Card](https://app.charmverse.io/charmverse/api-for-rewards-5303771278893195)

2024-03-14 03:52 UTC, mattcasey commented on pages/api/v1/rewards/submissions.ts
> +              application: null
we should still return the application that came w/the submission

2024-03-14 03:52 UTC, mattcasey commented on pages/api/v1/rewards/submissions.ts
> +      const isSubmission = submission.bounty.approveSubmitters ? submissionStatuses.includes(submission.status) : false;
where is this logic from? (application vs submission). is this also used in charmverse somewhere/could we have a standard method?

2024-03-14 04:05 UTC, mattcasey commented on pages/api/v1/rewards/submissions.ts
> +      const application = {
These 3 fields are actually metadata that apply to both application and submission, so i think they just belong at the top. But we're missing the content of applications and submissions which is important. What do you think about this  structure?
```
{
  id: string
  createdAt: string
  author
  status: ApplicationStatus
  submission?: { content: { text, markdown } }
  application?: { content: { text } }
}
```
- I'm open to just always returning an empty string for submission and application too. might be simpler to consume
- I think it makes sense to return 'status' but we probably need to clean the values up a bit, for instance "inProgress" should be mapped to "in_progress," and maybe "in_review" instead of just "review"

2024-03-14 04:07 UTC, mattcasey commented on pages/api/v1/rewards/submissions.ts
> +      const isSubmission = submission.bounty.approveSubmitters ? submissionStatuses.includes(submission.status) : false;
This was my first comment, after making the comment above, maybe we just always return application/submission but also include the status in case they want it.

2024-03-14 04:08 UTC, mattcasey commented on lib/public-api/getPageApi.ts
> +  author: UserProfile;
thanks for adding this too

2024-03-14 04:08 UTC, mattcasey requested changes
left comments

2024-03-15 06:51 UTC, Devorein commented on pages/api/v1/rewards/submissions.ts
> +      const isSubmission = submission.bounty.approveSubmitters ? submissionStatuses.includes(submission.status) : false;
Yeah that sounds good. Responding to the first comment we do have logic to differentiate between applications and submissions in this component `components/rewards/components/RewardApplications/RewardApplications.tsx#L136`

2024-03-15 06:53 UTC, Devorein commented on pages/api/v1/rewards/submissions.ts
> +      const application = {
Yeah that sounds good and agree with mapping `inProgress` to `in_progress` and same for review.

2024-03-19 03:26 UTC, mattcasey commented on pages/api/v1/rewards/submissions.ts
> +  status: Omit<ApplicationStatus, 'inProgress' | 'review'> | 'in_progress' | 'in_review';
please use Pick, not Omit

2024-03-19 03:30 UTC, mattcasey commented on pages/api/v1/rewards/submissions.ts
> +  if (!spaceId && !rewardId) {
we don't require a spaceId on the "Space API" if you look at most other endpoints. i think it's only required if you're using a partner key

2024-03-19 03:33 UTC, mattcasey commented on pages/api/v1/rewards/submissions.ts
> +      ...(spaceId ? { spaceId } : { bountyId: rewardId, spaceId: authorizedSpaceId }),
this is unsafe - we should only let you query by authorizedSpaceId

2024-03-19 03:40 UTC, mattcasey commented on pages/api/v1/rewards/submissions.ts
> +            .map((ceramicRecord: any) => {
where is this type actually? this type-casting seems very dangerous especially in our API

2024-03-19 03:45 UTC, mattcasey commented on pages/api/v1/rewards/submissions.ts
> + *          type: string
pretty sure chainId is a number type

2024-03-19 03:45 UTC, mattcasey commented on pages/api/v1/rewards/submissions.ts
> + *        issuedCredentialId:
rename to "id"

2024-03-19 03:47 UTC, mattcasey commented on pages/api/v1/rewards/submissions.ts
> + *        type:
"type" is confusing here; it could be both charmverse and on-chain, i'm not sure why we went with this enum. rename to "source" ?

2024-03-19 03:49 UTC, mattcasey commented on pages/api/v1/rewards/submissions.ts
> + *        timeCreated:
This should be "createdAt": "string"

2024-03-19 03:51 UTC, mattcasey commented on pages/api/v1/rewards/submissions.ts
> + *    EASAttestationFromApi:
this type wont make sense to non-charmverse people. i'm not even sure what "FromApi" means. whats a better name?

2024-03-19 09:10 UTC, Devorein commented on pages/api/v1/rewards/submissions.ts
> +  if (!spaceId && !rewardId) {
Good point, updated.

2024-03-19 09:10 UTC, Devorein commented on pages/api/v1/rewards/submissions.ts
> +      ...(spaceId ? { spaceId } : { bountyId: rewardId, spaceId: authorizedSpaceId }),
yep. Updated.

2024-03-19 09:11 UTC, Devorein commented on pages/api/v1/rewards/submissions.ts
> + *        timeCreated:
Updated

2024-03-19 09:11 UTC, Devorein commented on pages/api/v1/rewards/submissions.ts
> + *          type: string
Correct

2024-03-19 09:11 UTC, Devorein commented on pages/api/v1/rewards/submissions.ts
> + *        type:
done

2024-03-19 09:12 UTC, Devorein commented on pages/api/v1/rewards/submissions.ts
> + *        issuedCredentialId:
This will be removed since for charmverse sourced credentials issuedCredentialId is equal to id

2024-03-19 09:17 UTC, Devorein commented on pages/api/v1/rewards/submissions.ts
> + *    EASAttestationFromApi:
Get go with `EASCredential`

2024-03-19 09:17 UTC, Devorein commented on pages/api/v1/rewards/submissions.ts
> +            .map((ceramicRecord: any) => {
Updated

2024-03-19 10:25 UTC, merged