Fix rewards FE errors
charmverse/app.charmverse.io pull request #3960
Opened 2024-04-22 13:11 UTC by valentinludu

1st error: Rewards applicants returned a null value.
2nd error: Mapped Fragment without keys

2024-04-23 19:44 UTC, mattcasey commented on components/common/DatabaseEditor/components/properties/UserAndRoleSelect.tsx
> +          <Fragment key={option.id}>
thanks for catching

2024-04-23 19:44 UTC, mattcasey commented on components/common/DatabaseEditor/components/propertyValueElement.tsx
> +    propertyValueElement = <Box />;
this doesn't seem right, null is a valid value to pass in leiu of a JSX element

2024-04-23 19:45 UTC, mattcasey requested changes
see question

2024-04-24 09:50 UTC, valentinludu commented on components/common/DatabaseEditor/components/propertyValueElement.tsx
> +    propertyValueElement = <Box />;
At line 705 that `null` set at line 485 is logging an error.
I could verify that it's not a `REWARDS_APPLICANTS_BLOCK_ID` before showing the error.

2024-04-26 15:53 UTC, mattcasey approved these changes

2024-04-26 16:05 UTC, merged