Optional: Require reason for Fail on Pass/Fail steps
charmverse/app.charmverse.io pull request #4033
Opened 2024-05-07 13:12 UTC by Devorein

### WHAT

### WHY

[Card](https://app.charmverse.io/charmverse/optional-require-reason-for-fail-on-pass-fail-steps-8571563609916741)

2024-05-07 23:30 UTC, mattcasey commented on components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluation.tsx
> +      <ConfirmDeleteModal
this modal "ConfirmDeleteModal" should only be used for confirming delete. please use something else or rename it

2024-05-07 23:32 UTC, mattcasey commented on components/settings/proposals/components/EvaluationDialog.tsx
> +      <Autocomplete<string, true, true, true>
this input should line up with the other inputs:
![image](https://github.com/charmverse/app.charmverse.io/assets/305398/460e83eb-ff71-4c45-81f2-8e9c7647564d)

Also the UX is very vague. How do you add multiple ones? I think it woudl be better if we just had each reason on its own line, with a "Add reason" button below  the last input

2024-05-07 23:35 UTC, mattcasey commented on components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluation.tsx
> +            <Select
if i select a long option it gets cut off and is invisible:
![image](https://github.com/charmverse/app.charmverse.io/assets/305398/55020e0a-d45e-44e9-a9d8-6a409da58bd0)


The input should expand. i assumed we were only letting people select one option though

2024-05-07 23:36 UTC, mattcasey commented on components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluation.tsx
> +            {evaluation.failReasons.map((reason) => (
the chips should wrap and not be cut off:
![image](https://github.com/charmverse/app.charmverse.io/assets/305398/d8a2d838-a2aa-44fb-bc6b-1391c1c6bc54)

2024-05-07 23:43 UTC, mattcasey commented on components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluation.tsx
> +              multiple
users can only select only one reason at the moment

2024-05-07 23:44 UTC, mattcasey commented on components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluation.tsx
> +      <ConfirmDeleteModal
you could probably just use our common Modal directly. theres nothing special about this one and its name is confusing here

2024-05-07 23:45 UTC, mattcasey commented on components/settings/proposals/components/EvaluationContextMenu.tsx
> +    onEdit(evaluation);
thx for cleaning up the method name :)

2024-05-07 23:46 UTC, mattcasey requested changes
I think it would be smart to wait and do the other story first? For pass/fail we need to start storing responses for multiple people and i think that the failReasons on the evaluation itself would immediately no longer be used

2024-05-09 11:01 UTC, closed without merging

2024-05-09 11:39 UTC, Devorein commented on components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluation.tsx
> +            {evaluation.failReasons.map((reason) => (
Fixed

2024-05-09 11:40 UTC, Devorein commented on components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluation.tsx
> +      <ConfirmDeleteModal
Updated.

2024-05-09 11:40 UTC, Devorein commented on components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluation.tsx
> +            <Select
Nice catch. Updated.

2024-05-09 11:41 UTC, Devorein commented on components/proposals/ProposalPage/components/ProposalEvaluations/components/Review/components/PassFailEvaluation.tsx
> +              multiple
Updated.