Disable token chain and token inputs when using a reward template
charmverse/app.charmverse.io pull request #4034
Opened 2024-05-07 14:25 UTC by Devorein

### WHAT

### WHY

[Card](https://app.charmverse.io/charmverse/disable-token-chain-and-token-inputs-when-using-a-reward-template-8641440715535329)

2024-05-07 21:59 UTC, mattcasey commented on components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsForm.tsx
> +  const readOnlyType = readOnly || !!template?.rewardType;
admins are always supposed to be able to override template settings

2024-05-07 22:01 UTC, mattcasey commented on components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsForm.tsx
> +  const readOnlyChain = readOnly || !!template?.chainId;
i dont think we actually have a use case where only chain is set but token is optional ,so i dont think we should support it. if the token's read only, then chain is readonly

2024-05-07 22:09 UTC, mattcasey commented on components/proposals/ProposalPage/components/ProposalProperties/hooks/useProposalRewards.ts
> +    const rewardType = template ? template.rewardType : 'token';
thx for cleanup

2024-05-07 22:10 UTC, mattcasey requested changes
left some comments. blocking issue is that admins cannot override templates

2024-05-08 13:04 UTC, Devorein commented on components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsForm.tsx
> +  const readOnlyType = readOnly || !!template?.rewardType;
My bad I thought this restriction will be for every user (including admin). Added admin override.

2024-05-08 13:16 UTC, Devorein commented on components/proposals/ProposalPage/components/ProposalProperties/components/ProposalRewards/ProposalRewardsForm.tsx
> +  const readOnlyChain = readOnly || !!template?.chainId;
Sure lets go with that.

2024-05-08 13:50 UTC, merged