optimize form answer components
charmverse/app.charmverse.io pull request #4052
Opened 2024-05-10 05:49 UTC by mattcasey

### WHAT

### WHY

2024-05-10 10:07 UTC, valentinludu commented on components/common/form/FormFieldAnswers.tsx
> +          // await onSave([answer]);
Shouldn't this be available?

2024-05-10 10:08 UTC, valentinludu approved these changes

2024-05-10 10:25 UTC, Devorein requested changes
Please uncomment the `onSave` before merging.

2024-05-10 10:25 UTC, Devorein commented on components/common/form/FormFieldAnswers.tsx
> +          // await onSave([answer]);
This line should be uncommented? Its not saving the regular form field answers otherwise.

2024-05-10 10:25 UTC, Devorein commented on components/common/form/fields/FieldTypeRenderer.tsx
> +            value: typeof e?.target?.value === 'string' ? e.target.value : e
This is storing the number fields in string. We might need to cast the values based on the form field type.

2024-05-10 10:25 UTC, Devorein commented on components/common/form/fields/FieldTypeRenderer.tsx
> +        if (formFieldId && onChangeDebounced && !fieldProps.error) {
The error map is not up to date. It's always one step behind. So even with invalid values, we are sending requests, and ironically, when it's valid, it's not sending one (since the last one was invalid.)

2024-05-10 14:02 UTC, mattcasey commented on components/common/form/FormFieldAnswers.tsx
> +          // await onSave([answer]);
yes thanks! was commenting it out for testing

2024-05-20 09:47 UTC, Devorein commented on components/common/form/fields/FieldTypeRenderer.tsx
> +            value: typeof e?.target?.value === 'string' ? e.target.value : e
nvm currently we are storing it in string too.

2024-05-28 18:23 UTC, mattcasey commented
Requested changes were addressed

2024-05-28 18:40 UTC, merged