Fix: Cursor jumps out of box when adding rubric criteria
charmverse/app.charmverse.io pull request #4126
Opened 2024-06-03 10:29 UTC by valentinludu

Task:
https://app.charmverse.io/charmverse/each-time-i-start-typing-a-new-criteria-in-the-add-a-label-field-the-cursor-jumps-out-after-the-first-letter-or-two-8551001433787735

Fix:
- Added debounce so there aren't so many updates on the criteria fields

2024-06-04 05:45 UTC, mattcasey commented on components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/components/RubricCriteriaSettings.tsx
> +  const debouncedSetCriteriaProperty = debounce(setCriteriaProperty, 300);
debounced methods should be memoized, otherwise i dont think this is actually debouncing anything. but i dont think that was causing the problem

2024-06-04 06:00 UTC, mattcasey requested changes
The useEffect is necessary for a template feature where we copy rubric criteria from other templates. Without it, the criteria do not update. i'm open to other ideas to make it work:
<img width="407" alt="image" src="https://github.com/charmverse/app.charmverse.io/assets/305398/ea8791a4-e253-44c4-8ba1-c8ff0406d9e2">

2024-06-04 11:29 UTC, valentinludu commented on components/proposals/ProposalPage/components/ProposalEvaluations/components/Settings/components/RubricCriteriaSettings.tsx
> +  const debouncedSetCriteriaProperty = debounce(setCriteriaProperty, 300);
Done!

2024-06-04 11:31 UTC, valentinludu commented
I see...

I added it back but only when the length of the value changes so it doesn't affect the inner values that are changing.

> The useEffect is necessary for a template feature where we copy rubric criteria from other templates. Without it, the criteria do not update. i'm open to other ideas to make it work

2024-06-06 21:11 UTC, mattcasey approved these changes

2024-06-07 12:33 UTC, merged