Ai generator
charmverse/app.charmverse.io pull request #4132
Opened 2024-06-04 16:38 UTC by motechFR

### WHAT

Analyse developer activity on Github

### WHY

2024-06-04 18:19 UTC, mattcasey commented on pages/api/github/summarise-activity.ts
> +import type { NextApiRequest, NextApiResponse } from 'next';
this is an internal feature, right? I don't think we should include this in our client-facing webapp

2024-06-04 18:20 UTC, mattcasey commented on package.json
> +    "prisma:local": "rm -rf ./node_modules/.prisma && npm link @charmverse/core && npm run prisma:generate",
its not clear from the command what this script does

2024-06-04 18:23 UTC, mattcasey commented on lib/github/summariseDeveloperActivity.ts
> +    const summary = await summarisePullRequest({
could this be done in parallel?

2024-06-04 18:24 UTC, mattcasey commented on lib/github/summarisePullRequest.ts
> +      prNumber: params.prNumber,
we should just use JSON blobs for this data

2024-06-04 18:29 UTC, mattcasey commented on config/constants.ts
> +export const githubAccessToken = process.env.GITHUB_ACCESS_TOKEN as string;
can u add a comment what this access token is for and where it comes from? is it attached to our app id?

2024-06-04 18:31 UTC, mattcasey requested changes
left comments

2024-06-04 19:49 UTC, mattcasey approved these changes
after talking with @motechFR i learned that this endpoint is to be used by Google Docs. Suggestion: put it into the public api folder and add a big comment what it is used by

2024-06-06 17:12 UTC, motechFR commented on lib/github/summariseDeveloperActivity.ts
> +  const mostActiveRepo = pullRequests[0];
getPullRequestsByRepo ranks repos by number of found PRs, from most to least

2024-06-06 17:13 UTC, motechFR commented on lib/github/summariseDeveloperActivity.ts
> +  const filteredPullRequests = mostActiveRepo.pullRequests.filter((pr) => pr.additions + pr.deletions > 10);
Current filtering logic, minimum 10 LoC diff

2024-06-06 17:18 UTC, motechFR commented on lib/github/getPullRequestFileChanges.ts
> +const ignoredFiles = ['package-lock.json'];
@mattcasey This method handles filtering out files like package-lock.json so that we don't accidentally analyse an irrelevant file with lots of wasted tokens

2024-06-07 19:55 UTC, mattcasey commented on lib/github/getPullRequestFileChanges.ts
> +const ignoredFiles = ['package-lock.json'];
Thanks. this would be a good code comment

2024-06-10 14:29 UTC, merged