Farcaster member directory property and required login identity
charmverse/app.charmverse.io pull request #4183
Opened 2024-06-18 14:01 UTC by Devorein

### WHAT

### WHY

[Card](https://app.charmverse.io/charmverse/allow-space-admins-to-require-members-to-connect-farcaster-identity-4995024008006026)

2024-06-18 17:28 UTC, mattcasey commented on components/login/components/WarpcastLogin.tsx
> +export function useWarpcastLogin({ type }: { type: LoginType }) {
if this is a hook, it should be in a hook file

2024-06-18 17:30 UTC, mattcasey requested changes
this adds .02MB to the payload, looks like it is probably adding the warpcast SDK to our app. please use lazy loading like we are doing with LoginButton

2024-06-18 17:31 UTC, mattcasey commented on components/_app/components/ConnectedAccounts.tsx
> +import { useWarpcastLogin } from 'components/login/components/WarpcastLogin';
this should be lazy-loaded

2024-06-18 17:33 UTC, mattcasey commented on components/members/components/MemberDirectorySidebar/MemberPropertyItem.tsx
> +      <SvgIcon viewBox='0 0 20 20' fontSize='small'>
we should be using CSS to modify the SVG based on light mode. using JS is very hacky, but not a blocker

2024-06-18 17:35 UTC, mattcasey commented on lib/members/getSpaceMembers.ts
> +          farcasterUser: userData.farcasterUser || undefined
please map this to the fields you need. its a bad practice to just send the whole JSON forward, also requires type-casting

2024-06-18 17:35 UTC, mattcasey commented on lib/members/interfaces.ts
> +  farcasterUser?: FarcasterUser;
just pick the fields we need here

2024-06-18 17:36 UTC, mattcasey requested changes
Required changes requested:
- dont send the entire farcaster blob to the frontend
- lazy-load the auth kit

2024-06-20 13:18 UTC, Devorein commented on components/login/components/WarpcastLogin.tsx
> +export function useWarpcastLogin({ type }: { type: LoginType }) {
Updated

2024-06-20 13:24 UTC, Devorein commented on components/_app/components/ConnectedAccounts.tsx
> +import { useWarpcastLogin } from 'components/login/components/WarpcastLogin';
Updated

2024-06-20 13:48 UTC, Devorein commented on components/members/components/MemberDirectorySidebar/MemberPropertyItem.tsx
> +      <SvgIcon viewBox='0 0 20 20' fontSize='small'>
Removed the explicit fill value and it worked for both theme.

2024-06-20 14:00 UTC, Devorein commented on lib/members/interfaces.ts
> +  farcasterUser?: FarcasterUser;
Updated

2024-06-20 14:45 UTC, merged