Connect welcome
charmverse/app.charmverse.io pull request #4195
Opened 2024-06-21 07:41 UTC by valentinludu

2024-06-25 16:25 UTC, motechFR commented
Issues we need to fix

**UI**
- Modal for login not looking correct (might be missing Paper)

**Login** 
- Issue with one of dependencies making login callback not 100% reliable

2024-06-26 05:23 UTC, mattcasey commented on apps/connect/app/error.tsx
> +      <Button onClick={reset}>Try again</Button>
I don't think we need this. i see reset is a documented function, but none of the times we have shown this page in our regular app would have been retry-able. "Try again" is confusing IMO

https://nextjs.org/docs/app/api-reference/file-conventions/error#global-errorjs

2024-06-26 05:31 UTC, mattcasey commented on apps/connect/app/global-error.tsx
> +          <Button onClick={reset}>Try again</Button>
same comment - https://github.com/vercel/next.js/discussions/49935. on top of it, reset only re-renders components so if we have SRC, it will refresh that but it won't refresh anything that's pulled from the API. even more confusing.

2024-06-26 05:41 UTC, mattcasey commented on apps/connect/app/welcome/page.tsx
> +  if (user.data?.connectOnboarded) {
i think typescript knows user.data exists now

2024-06-26 05:42 UTC, mattcasey commented on apps/connect/components/common/Avatar.tsx
> +        backgroundColor: stringToColor(nameStr),
please keep 'initial' if avatar is provided. that way it is grey while the picture loads

2024-06-26 05:43 UTC, mattcasey commented on apps/connect/components/common/FarcasterCard.tsx
> +export function FarcasterCard({ username, pfpUrl, bio }: any) {
do not use abbreviations in props and var names - i don't know what "pfpUrl" is

2024-06-26 05:44 UTC, mattcasey commented on apps/connect/components/common/FarcasterCard.tsx
> +import Card from '@mui/material/Card';
it's better to use barrel imports from material so we don't have so many import lines: `import { Box, Card } from '@mui/material'`

2024-06-26 05:48 UTC, mattcasey commented on apps/connect/components/common/WarpcastLogin/components/WarpcastModal.tsx
> +      <Box px={3} pb={3}>
maybe u should be using DialogContent here?

2024-06-26 05:51 UTC, mattcasey commented on apps/connect/components/projects/ProjectItem.tsx
> +  const projectName = project.name || 'Untitled';
project name is required isn't it? i dn't think Untitled fallback is necessary

2024-06-26 05:52 UTC, mattcasey commented on apps/connect/components/projects/ProjectItem.tsx
> +          alignItems='start'
i didnt know about "start" :)

2024-06-26 05:54 UTC, mattcasey commented on apps/connect/components/projects/ProjectItem.tsx
> +                WebkitLineClamp: '2',
interesting css.. seems like it's supported by everyone but ie

2024-06-26 05:55 UTC, mattcasey commented on apps/connect/components/projects/ProjectItem.tsx
> +                avatar={member.user?.avatar || ''}
user should not be optional on team members

2024-06-26 05:56 UTC, mattcasey commented on apps/connect/components/welcome/ExtraDetails.tsx
> +import FormHelperText from '@mui/material/FormHelperText';
Please change these to be barrel import. this is a 'fresh' codebase and we should always use barrel imports

2024-06-26 05:58 UTC, mattcasey commented on apps/connect/components/welcome/ExtraDetails.tsx
> +            <TextField aria-labelledby='form-email' error={!!errors.email} {...field} sx={{ mb: 1 }} />
Since you're usig Controller please access errors for a field like so: `render={({ field, fieldState: { error } }) => ` this avoids having to watch the state in the parent scope, triggering re-renders on the entire form

2024-06-26 05:59 UTC, mattcasey commented on apps/connect/components/welcome/ExtraDetails.tsx
> +      <FormHelperText error={!!hasErrored}></FormHelperText>
Remove FormHelperText or add an error message inside

2024-06-26 06:01 UTC, mattcasey commented on apps/connect/components/welcome/utils/form.ts
> +export const schema = yup.object({
since this is used on the backend, and we prefer for lib/backend not to import from components, this schema belongs in the lib folder next to onboardingAction.ts

2024-06-26 06:03 UTC, mattcasey commented on apps/connect/lib/session/config.ts
> +export const sessionUserRelations = {
this is only used in one place, and it is dependent on the LoggedInUser type, so i don't think it belogns here. It should just sit in getUser which is also where LoggedInUser should be defined

2024-06-26 06:05 UTC, mattcasey commented on apps/connect/lib/profile/types.ts
> +import type {
we use "interfaces.ts" not "types.ts". That should not change. And you should be using 'type' instead of 'interface' below.

2024-06-26 06:05 UTC, mattcasey commented on apps/connect/lib/profile/types.ts
> +export interface LoggedInUser extends User {
this interface belongs in getUser since that's where it's actually created.

2024-06-26 06:05 UTC, mattcasey commented on apps/connect/lib/profile/types.ts
> +interface NestedMemberships {
i don't think this type's used?

2024-06-26 06:09 UTC, mattcasey commented on apps/connect/lib/session/types.ts
interfaces.ts

2024-06-26 06:10 UTC, mattcasey commented on apps/connect/next.config.js
> +    _config.resolve.alias.canvas = false;
do we actually still need this?

2024-06-26 06:11 UTC, mattcasey commented on apps/connect/package.json
> +    "@typeschema/yup": "^0.13.3",
this already exists at the top-level of our app. does not need to be defined locally here, does it?

2024-06-26 06:11 UTC, mattcasey commented on apps/connect/public/vercel.svg
thanks for cleanup

2024-06-26 06:12 UTC, mattcasey commented on lib/utils/async.ts
> +export async function delay(ms: number = 1000) {
suggestion; dont give people a default timeout. make them pick it. otherwise we'll never be able to change this again cuz it'll be too hard to know who's relying on 1 second

2024-06-26 06:19 UTC, mattcasey commented on apps/connect/lib/actions/onError.tsx
> +    throw new DataNotFoundError(`Data not found`);
this method is to handle thrown errors so it should not throw an error

2024-06-26 06:22 UTC, mattcasey commented on apps/connect/lib/actions/onError.tsx
> +  return err.message;
we should have a fallback message if err.message doesn't exist. and maybe add "string" as a return type in the function signature for this method?

2024-06-26 06:23 UTC, mattcasey commented on apps/connect/lib/profile/getUser.ts
this files should be called getUserProfile to match the exported function

2024-06-26 06:24 UTC, mattcasey requested changes
left comments.. some are more important than others. i dont think they all need to be addressed 100% but please check them out

2024-06-26 08:53 UTC, Devorein commented on apps/connect/components/projects/ProjectItem.tsx
> +                avatar={member.user?.avatar || ''}
Right there is guaranteed to be atleast a single member (team lead)

2024-06-26 12:44 UTC, valentinludu commented on apps/connect/components/common/FarcasterCard.tsx
> +export function FarcasterCard({ username, pfpUrl, bio }: any) {
Oh, missed it! Thanks

2024-06-26 12:46 UTC, valentinludu commented on apps/connect/components/common/WarpcastLogin/components/WarpcastModal.tsx
> +      <Box px={3} pb={3}>
Yep!

2024-06-26 12:47 UTC, valentinludu commented on apps/connect/components/projects/ProjectItem.tsx
> +  const projectName = project.name || 'Untitled';
I have seen empty string as a name in production

2024-06-26 12:54 UTC, valentinludu commented on apps/connect/components/welcome/ExtraDetails.tsx
> +import FormHelperText from '@mui/material/FormHelperText';
Done

2024-06-26 12:56 UTC, valentinludu commented on apps/connect/components/welcome/ExtraDetails.tsx
> +            <TextField aria-labelledby='form-email' error={!!errors.email} {...field} sx={{ mb: 1 }} />
Niiice. 

Done!

2024-06-26 12:56 UTC, valentinludu commented on apps/connect/components/welcome/ExtraDetails.tsx
> +      <FormHelperText error={!!hasErrored}></FormHelperText>
Updated!

2024-06-26 12:58 UTC, valentinludu commented on apps/connect/components/welcome/utils/form.ts
> +export const schema = yup.object({
Done!

2024-06-26 12:59 UTC, valentinludu commented on apps/connect/lib/session/config.ts
> +export const sessionUserRelations = {
Every session file was removed and uploaded from the main lib file so we keep in sync all session related activity.

2024-06-26 13:01 UTC, valentinludu commented on apps/connect/lib/profile/types.ts
> +export interface LoggedInUser extends User {
It was removed. See comment above.

2024-06-26 13:02 UTC, valentinludu commented on apps/connect/lib/session/types.ts
It was removed. I commented above.

2024-06-26 13:04 UTC, valentinludu commented on apps/connect/next.config.js
> +    _config.resolve.alias.canvas = false;
I will delete it and if the error resurfaces I will add it back.

I don't remember either where did we encounter this.

2024-06-26 13:06 UTC, valentinludu commented on lib/utils/async.ts
> +export async function delay(ms: number = 1000) {
Sure. I hope no one will use it. 
I created it just for debugging purposes.

e.g. Check the skeleton inside Suspense.

2024-06-26 13:08 UTC, valentinludu commented on apps/connect/lib/actions/onError.tsx
> +    throw new DataNotFoundError(`Data not found`);
yeah, today I handled the last remaining parts for error handling.

I updated some parts here!

2024-06-26 13:09 UTC, valentinludu commented on apps/connect/lib/actions/onError.tsx
> +  return err.message;
I updated this part with more comprehensive details and data

2024-06-26 13:09 UTC, valentinludu commented on apps/connect/lib/profile/getUser.ts
That file was just for testing. I deleted it since Mo handled the get user part.

2024-06-26 13:11 UTC, valentinludu commented on apps/connect/components/common/FarcasterCard.tsx
> +import Card from '@mui/material/Card';
Done

2024-06-26 13:14 UTC, valentinludu commented
> left comments.. some are more important than others. i dont think they all need to be addressed 100% but please check them out

Responded to all!

2024-06-26 13:25 UTC, valentinludu commented on apps/connect/app/error.tsx
> +      <Button onClick={reset}>Try again</Button>
I deleted this one since we have the global-error one

2024-06-26 13:27 UTC, valentinludu commented on apps/connect/app/global-error.tsx
> +          <Button onClick={reset}>Try again</Button>
In a real world situation probably reset won't do too much. I removed it

2024-06-26 14:50 UTC, mattcasey approved these changes

2024-06-26 15:38 UTC, merged

2024-06-26 15:48 UTC, valentinludu commented on apps/connect/components/projects/ProjectItem.tsx
> +                avatar={member.user?.avatar || ''}
The user can be null since it comes from the schema and we wanted to have a project even tho a user is deleted.