Connect app UI
charmverse/app.charmverse.io pull request #4254
Opened 2024-07-05 15:06 UTC by valentinludu

https://www.figma.com/design/uGO5TTywk0VE2yvHcbErdQ/Untitled?node-id=0-1&t=pCcTakt8btZZAG4Q-0

2024-07-08 15:35 UTC, valentinludu commented on apps/connect/lib/actions/revalidatePath.ts
> +export const actionRevalidatePath = actionClient.metadata({ actionName: 'revalidatePath' }).action<void>(async () => {
FYI. This just revalidates the main layout in client components.

2024-07-08 16:40 UTC, mattcasey commented on .eslintignore
> +apps/connect-api/src/routes.ts
Can we not do this? It feels really hacky to have to ignore a file in src, it's also being added twice. i think this particular file is auto-generated, but that's even more reason that i should pass linting.

In the worst case, add eslint ignore to the src file?

2024-07-08 16:43 UTC, mattcasey commented on apps/connect-api/src/scripts/generateRoutes.ts
> +/* eslint-disable import/no-extraneous-dependencies */
i think the comment needs to be the first line. if you were getting an eslint error, that may be why

2024-07-08 16:44 UTC, mattcasey commented on apps/connect/apiClient/apiClient.ts
> +  async logOut(): Promise<void> {
all lowercase to be consistent please: `logout()`

2024-07-08 16:45 UTC, mattcasey commented on apps/connect/app/layout.tsx
> +export default async function RootLayout({
why do you have to use async here?

2024-07-08 16:46 UTC, mattcasey commented on apps/connect/components/common/FarcasterCard.tsx
> +    <Card sx={{ border: 'none' }}>
This is fine, but do we even need a card component if there's no border?

2024-07-08 16:48 UTC, mattcasey commented on apps/connect/components/layout/Footer.tsx
> +export function Footer(props: BoxProps) {
Please remove props if we don't use it

2024-07-08 16:49 UTC, mattcasey commented on apps/connect/components/layout/Header.tsx
> +  const user = await getCurrentUser();
This is fine for now, but user should probably be passed into context or something. how do we avoid re-querying the user every time we need their information?

2024-07-08 16:50 UTC, mattcasey commented on apps/connect/components/layout/NavBar.tsx
> +import type { LoggedInUser } from 'models/User';
Let's stop using LoggedInUser for this app

2024-07-08 16:54 UTC, mattcasey commented on apps/connect/components/welcome/WelcomePage.tsx
> +  const farcasterDetails = user.farcasterUser?.account as Required<FarcasterBody>;
this is being cast as if it always exists but it's reading from an optional field

2024-07-08 16:54 UTC, mattcasey commented on apps/connect/lib/actions/revalidatePath.ts
> +export const actionRevalidatePath = actionClient.metadata({ actionName: 'revalidatePath' }).action<void>(async () => {
would be worth adding a comment above on why you would use it

2024-07-08 16:57 UTC, mattcasey requested changes
- clean up eslint or can we chat about it offline? i would like to unerstand the issue more
- everything else can be taken as a suggestion

2024-07-09 08:42 UTC, valentinludu commented on apps/connect/lib/actions/revalidatePath.ts
> +export const actionRevalidatePath = actionClient.metadata({ actionName: 'revalidatePath' }).action<void>(async () => {
Done

2024-07-09 08:43 UTC, valentinludu commented on apps/connect-api/src/scripts/generateRoutes.ts
> +/* eslint-disable import/no-extraneous-dependencies */
Done

2024-07-09 08:45 UTC, valentinludu commented on apps/connect/apiClient/apiClient.ts
> +  async logOut(): Promise<void> {
done

2024-07-09 08:46 UTC, valentinludu commented on apps/connect/components/layout/Footer.tsx
> +export function Footer(props: BoxProps) {
I used it but no I don't need it anymore so I removed the props.

2024-07-09 09:13 UTC, valentinludu commented on apps/connect/components/welcome/WelcomePage.tsx
> +  const farcasterDetails = user.farcasterUser?.account as Required<FarcasterBody>;
Added the `| undefined` in all the places to ensure we take care of undefined situations

2024-07-09 09:39 UTC, valentinludu commented on apps/connect/components/layout/NavBar.tsx
> +import type { LoggedInUser } from 'models/User';
I created another LoggedInUser just for this app

2024-07-09 09:48 UTC, valentinludu commented on apps/connect/components/common/FarcasterCard.tsx
> +    <Card sx={{ border: 'none' }}>
I saw the border in a few places. I need to circle back with Chris to see where it is needed and where not.

2024-07-09 10:11 UTC, valentinludu commented on apps/connect/components/layout/Header.tsx
> +  const user = await getCurrentUser();
I can think of a method to cache the response for server components. Let's discuss more in our daily.

2024-07-09 10:23 UTC, valentinludu commented on .eslintignore
> +apps/connect-api/src/routes.ts
The error is thrown only when we commit a new route.

I deleted the apps/connect-api/.eslintignore file.

I deleted this line and it will probably resurface on the next route we will create and commit.

2024-07-09 11:29 UTC, merged