Archive and permanently delete pages
charmverse/app.charmverse.io pull request #426
Opened 2022-05-01 16:42 UTC by Devorein

1. A simple modal view to show deleted pages sorted by their deleted date in descending order
2. Two buttons at the rightmost to allow restoring and permanently deleting a page
![image](https://user-images.githubusercontent.com/34683631/166155511-a6283edb-98e6-42d7-baf4-5012ebedb5a8.png)
3. When visiting a deleted page in the trash a banner is shown at the top to restore or permanently delete the page
![image](https://user-images.githubusercontent.com/34683631/166155525-de5fc630-5b54-4cae-b2cd-a6594176f517.png)
4. Permanently deleting a page would permanently delete all of its child pages, and the same goes for restoring a page
5. Deleted pages can't be publicly shared nor can they be publicly viewed (this is what Notion does)

**NOTE** Separately deleted card will be shown inside a deleted board, this is because we can't figure out if the card was deleted manually or was it deleted by the board

2022-05-03 19:58 UTC, mattcasey commented on charmClient.ts
> +    return http.DELETE<{deletedCount: number}>(`/api/pages/${pageId}?action=restore`);
this should not be a DELETE method. We should only use DELETE for actual deletPage

2022-05-03 20:05 UTC, mattcasey commented on components/[pageId]/DocumentPage/DocumentPage.tsx
> +  const comments = useAppSelector(getCardComments(card?.id));
i actually dont think this is very clean. you're putting the onus on getCardComments to handle someone calling it with undefined.

2022-05-03 20:11 UTC, mattcasey requested changes
- when deleting a page, we should no longer redirect you anywhere - the Deleted banner should just appear
- need to filter out deleted pages from /pages/[domain]/index.ts. right now it sends me to a deleted page every time i open my workspace, because it happens to be the first one

2022-05-03 20:14 UTC, mattcasey commented on components/[pageId]/DocumentPage/components/PageDeleteBanner.tsx
> +    await mutate(`pages/${space?.id}`);
why do we need to re-query all pages? remember this is pretty slow

2022-05-03 20:14 UTC, mattcasey commented on components/[pageId]/DocumentPage/components/PageDeleteBanner.tsx
> +    await mutate(`pages/${space?.id}`);
just use setPages instead

2022-05-03 20:20 UTC, mattcasey commented on components/[pageId]/DocumentPage/components/PageDeleteBanner.tsx
> +    await mutate(`pages/${space?.id}`);
originally i thought we didnt need to call mutate, now i remember there's children that might be affected. wo[uld it be hard to have restorePage return a list of pages to "restore"? that would be much faster, u could just loop over them and fix it with setPages..

2022-05-03 20:24 UTC, mattcasey commented on lib/pages/modifyChildPages.ts
> +export async function modifyChildPages (parentId: string, userId: string, action: ChildModificationAction) {
great candidate for tests

2022-05-04 13:51 UTC, Devorein commented on lib/pages/modifyChildPages.ts
> +export async function modifyChildPages (parentId: string, userId: string, action: ChildModificationAction) {
Absolutely agree with that. I will add some.

2022-05-05 15:52 UTC, Devorein commented on components/[pageId]/DocumentPage/components/PageDeleteBanner.tsx
> +    await mutate(`pages/${space?.id}`);
Its been implemented in the latest commit.

2022-05-05 16:10 UTC, Devorein commented on charmClient.ts
> +    return http.DELETE<{deletedCount: number}>(`/api/pages/${pageId}?action=restore`);
Good point. Went with `/api/pages/[id]/archive` endpoint to support archiving and restoring pages.

2022-05-05 16:36 UTC, Devorein commented on components/[pageId]/DocumentPage/DocumentPage.tsx
> +  const comments = useAppSelector(getCardComments(card?.id));
I reverted it back since it caused a nasty and really hard-to-find issue when I tried to restore an archived page.
`useAppSelector` is a hook, and we are conditionally calling the hook. This violates the rule of using hooks and leads to this error
`Uncaught Invariant Violation: Rendered more hooks than during the previous render`

2022-05-05 20:49 UTC, mattcasey commented
Looks good! I have one final suggestion:
![image](https://user-images.githubusercontent.com/305398/167023163-97c2883b-7208-43df-8206-e68c200fd045.png)


Replace "Page 1" placeholder with "Filter by page title..." and we don't need a description below. (Inspired by Notion)

2022-05-05 20:50 UTC, mattcasey approved these changes

2022-05-06 07:31 UTC, merged