Move logic from connect-api to connect
charmverse/app.charmverse.io pull request #4406
Opened 2024-08-12 10:49 UTC by valentinludu

2024-08-13 04:46 UTC, mattcasey commented on @connect-shared/components/common/MultiTextInputField.tsx
> +              value={_field.value || ''}
I think u can remove this - i believe i fixed it by providing defaultValue

2024-08-13 04:46 UTC, mattcasey commented on @connect-shared/lib/session/logoutAction.ts
> +export const logoutAction = authActionClient.metadata({ actionName: 'logout' }).action(async ({ ctx }) => {
thanks for fixing!

2024-08-13 04:47 UTC, mattcasey commented on apps/connect/app/api/aws/upload-token/route.ts
> +import { GetFederationTokenCommand, STSClient } from '@aws-sdk/client-sts';
Please dont duplicate code - we have this already written inside sunnyawards, so it should be put into connect-shared

2024-08-13 04:50 UTC, mattcasey commented on apps/connect/components/projects/components/ProjectForm.tsx
> +                  value={field.value || ''}
this looks like a hack, i am not sure what problem you are solving. maybe we need to be providing default values in the useForm or provide a defaultValue instead?

2024-08-13 04:52 UTC, mattcasey commented on apps/sunnyawards/components/common/Header/Header.tsx
> +      revalidatePathAction();
why should we not await? this function returns a promise?

2024-08-13 05:01 UTC, mattcasey requested changes
Sunny Awards and Connect should share code that is the same. When I created Connect, we said that it was not worth me going back and de-duping at the time, and agreed to do it as-we-go. Please at least remove the new duplicate code for uploading images. And ideally, now that we are only using server actions in both it would be easy to re-use some other components like SearchFarcasterUser.

2024-08-13 07:12 UTC, valentinludu commented on @connect-shared/components/common/MultiTextInputField.tsx
> +              value={_field.value || ''}
defaultValue makes a component to be uncontrolled and then, when the state changes it becomes controlled and the browser throws an error. Usually React recommends to create a component controlled or uncontrolled.

<img width="581" alt="Screenshot 2024-08-13 at 10 11 20" src="https://github.com/user-attachments/assets/8b309730-def0-42f3-a4b3-5b7f502ad689">

2024-08-13 07:13 UTC, valentinludu commented on @connect-shared/components/common/MultiTextInputField.tsx
> +              value={_field.value || ''}
Another way would be to set default values to useForm hook.

2024-08-13 07:54 UTC, valentinludu commented on apps/connect/app/api/aws/upload-token/route.ts
> +import { GetFederationTokenCommand, STSClient } from '@aws-sdk/client-sts';
Agree. Moved it in connect-shared folder!

2024-08-13 07:55 UTC, valentinludu commented on apps/connect/components/projects/components/ProjectForm.tsx
> +                  value={field.value || ''}
I commented above.

2024-08-13 07:58 UTC, valentinludu commented on apps/sunnyawards/components/common/Header/Header.tsx
> +      revalidatePathAction();
It makes the change of the page faster. We can discuss more in our call.

2024-08-14 04:07 UTC, mattcasey approved these changes

2024-08-14 11:58 UTC, merged