Setup waitlist frame
charmverse/app.charmverse.io pull request #4410
Opened 2024-08-12 16:18 UTC by motechFR

### WHAT

### WHY

2024-08-13 04:43 UTC, mattcasey commented on apps/connect/app/waitlist/[fid]/page.tsx
> +import WaitlistGif from 'public/images/waitlist/waitlist-intro.gif';
remember this should be hosted inside apps/farcaster, not connect

2024-08-13 04:45 UTC, mattcasey requested changes
All Farcaster-related features should live in apps/farcaster now

2024-08-14 04:05 UTC, mattcasey approved these changes

2024-08-14 14:30 UTC, valentinludu commented on apps/farcaster/app/api/waitlist/route.tsx
> +  prettyPrint({ validatedMessage });
I think you can delete this one and add a log.info.

2024-08-14 14:38 UTC, valentinludu commented on apps/farcaster/app/waitlist/[fid]/page.tsx
> +// async function inboundReq(input: any) {
You can delete comments if not needed.

2024-08-15 01:19 UTC, merged