Bugs/sunny patches
charmverse/app.charmverse.io pull request #4430
Opened 2024-08-14 23:42 UTC by motechFR

### WHAT

Change viem ENS RPC url to avoid throwing an error

Add error states in the form

### WHY

2024-08-15 02:48 UTC, mattcasey commented on @connect-shared/lib/projects/createOptimismProject.ts
>      const resolvedAddress = await resolveEnsAddress(input.mintingWalletAddress as string);
please delete/replace lib/blockchain resolveEnsAddress with our own: resolveENSName from lib/blockchain/getENSName. u can split out the file if you want, but i want to use the original one  everywhere

2024-08-15 02:48 UTC, mattcasey commented on connectors/chains.ts
> +    viem: { ...mainnet, rpcUrls: { default: { http: ['https://rpc.ankr.com/eth'] } } },
this will not change what wagmi/core does

2024-08-15 02:48 UTC, mattcasey requested changes
see comment

2024-08-15 02:53 UTC, mattcasey commented on apps/sunnyawards/components/projects/edit/EditProjectPage.tsx
> +      log.error(errorMessage || 'Something went wrong', err.error.serverError);
1. we already do logging on the backend (and the info is usually better), so this log is unecessary
2. Our log util expects an object in the second argument, and has special handling for  the "error" prop, so you should pass it like: `log.error(message, { error: })`

2024-08-15 02:54 UTC, mattcasey commented on apps/sunnyawards/components/projects/edit/EditProjectPage.tsx
> +              projectMembers: input.projectMembers.filter((m) => m.farcasterId !== user.farcasterUser?.fid)
the previous code was pulling out the team lead - are you sure we don't want to do that anymore?

2024-08-15 03:00 UTC, mattcasey commented on apps/sunnyawards/components/projects/new/CreateProjectPage.tsx
> +        ? concatenateStringValues(err.error.validationErrors.fieldErrors)
if we have multiple errors, they should be split out in paragraph tags. if u just use a comma-separated list, that is hard to read

2024-08-15 14:55 UTC, mattcasey approved these changes

2024-08-16 12:28 UTC, valentinludu commented on apps/sunnyawards/components/projects/edit/EditProjectPage.tsx
> +  const [errors, setErrors] = useState<string[] | null>(null);
Instead of creating a new state, you already have one called result.
And use that result in a constant if you want to transform it.

```
  const { execute, isExecuting, result } = useAction(editProjectAction, {
    onSuccess: () => {
      router.push(`/p/${project.path}`);
    },
    onError(err) {
      log.error(err.error.serverError?.message || 'Something went wrong', err.error.serverError);
    }
  });
  const formError = result.validationErrors?.formErrors;
```

2024-08-16 12:28 UTC, valentinludu commented on apps/sunnyawards/components/projects/new/CreateProjectPage.tsx
> +      const errorMessage = hasValidationErrors
Same comment as above

2024-08-16 12:30 UTC, valentinludu approved these changes
Left only 1 comment for handling errors

2024-08-16 13:27 UTC, motechFR commented on apps/sunnyawards/components/projects/edit/EditProjectPage.tsx
> +  const [errors, setErrors] = useState<string[] | null>(null);
Awesome thanks, I will cleanup in next PR

2024-08-16 13:28 UTC, merged