Manifest and favicon for waitlist, sg and comingsoon
charmverse/app.charmverse.io pull request #4576
Opened 2024-09-11 14:24 UTC by Devorein

### WHAT

### WHY

2024-09-11 16:19 UTC, mattcasey approved these changes

2024-09-12 04:45 UTC, mattcasey commented on apps/comingsoon/public/sw.js
it's odd there is a sw.js in coming soon at all, hm..

2024-09-12 04:46 UTC, mattcasey requested changes
i deployed to staging and it is still showing the old favicon, which i think is at apps/scoutgame/favicon.ico.

Next.js seems to want it at that location: https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons#image-files-ico-jpg-png

2024-09-12 12:23 UTC, Devorein commented on apps/comingsoon/public/sw.js
Good catch. We didn't add it in .gitignore.

2024-09-12 12:51 UTC, merged