Better @ mention UX
charmverse/app.charmverse.io pull request #467
Opened 2022-05-11 17:14 UTC by Devorein

1. Filter out the archived pages for `/link to page` and `@mention`
2. Replace inconsistent `@mention` UI with that of `/link to page`
3. Up/Down arrow to navigate between items
4. Press enter to select item

2022-05-11 18:34 UTC, motechFR commented on components/common/CharmEditor/components/nestedPage/components/NestedPagesList.tsx
> +      <PagesList onSelectPage={onSelectPage} />
Nice one Safwan, this is a good example of cleanup

2022-05-11 18:36 UTC, motechFR approved these changes
Hey @Devorein this PR works well. 

One issue I have, is the lack of filtering as I type out.

Could you double check with team to see if we can get this into the PR?

Otherwise, for UX-only aspect looks good

2022-05-12 09:31 UTC, Devorein commented on components/common/CharmEditor/components/nestedPage/components/NestedPagesList.tsx
> +      <PagesList onSelectPage={onSelectPage} />
Thank you. We were using pretty much the same component in two places so made the decision to refactor

2022-05-13 09:25 UTC, Devorein commented
I think you are right. I will try to get the text search feature on this pr. They are both related to good UX

2022-05-13 20:38 UTC, mattcasey requested changes
the page search should appear below my text, not above it
![image](https://user-images.githubusercontent.com/305398/168385938-adf3b434-45fd-42b3-bb85-95afe86c34d1.png)

2022-05-13 20:38 UTC, mattcasey commented on components/common/CharmEditor/components/inlinePalette/useEditorItems.tsx
> +              if (nestedPagePluginKey) {
This should be required, it doesn't look like we ever call useEditorItems withought it. I would prefer we actually just import it like we had before, since it's a static variable and not dynamic

2022-05-13 20:38 UTC, mattcasey commented on components/common/CharmEditor/CharmEditor.tsx
> +const nestedPagePluginKey = new PluginKey('nestedPage');
Since keys are being generated statically, I think they should just live next to the plugin/component. It doesn't make sense to pass them around as props unless we were builidng a 3rd party lib like bangle.dev

2022-05-14 10:19 UTC, Devorein commented on components/common/BoardEditor/focalboard/src/components/table/tableRow.tsx
> +    const {pages} = usePages()
Yes, thank you. I've removed it, now we are passing a prop for the content

2022-05-14 10:22 UTC, Devorein commented on components/common/CharmEditor/components/inlinePalette/useEditorItems.tsx
> +              if (nestedPagePluginKey) {
The plugin keys had to be created for each charmeditor and they have to be unique, I had to go this route when writing the inline charm editor as each editor instance had to have their own plugins. I just updated the `nestedPage` and `inlineComment` plugins to be separate for each charmeditor as there could be cases where we might have more than one charmeditor rendered on the screen.

2022-05-14 10:22 UTC, Devorein commented on components/common/CharmEditor/CharmEditor.tsx
> +const nestedPagePluginKey = new PluginKey('nestedPage');
The same response as above

2022-05-14 17:56 UTC, mattcasey approved these changes

2022-05-16 15:11 UTC, merged