SG login info modal
charmverse/app.charmverse.io pull request #4699
Opened 2024-09-30 19:55 UTC by valentinludu

[Card](https://app.charmverse.io/charmverse/better-sign-in-flow-when-clicking-something-that-takes-you-to-log-in-7484419506941695)

2024-10-01 03:08 UTC, mattcasey commented on apps/scoutgame/components/common/Header/Header.tsx
> +                <SiteNavigation topNav isAuthenticated={!!user} />
i like this choice of prop name, it's very clear

2024-10-01 03:14 UTC, mattcasey commented on apps/scoutgame/components/common/ScoutButton/ScoutButton.tsx
> +      <SignInModalMessage open={authPopup} onClose={() => setAuthPopup(false)} />
Suggestion, maybe for next time: I think it's even better when we just have a hook like "useSignInPrompt", similar to "useSnackbar", and having one global modal and state in globalcomponents. It's much easier to use and u don't have to worry about managing a new modal state every time

2024-10-01 03:21 UTC, mattcasey commented on apps/scoutgame/components/common/ScoutButton/ScoutButton.tsx
> +      <SignInModalMessage open={authPopup} onClose={() => setAuthPopup(false)} />
Maybe the hook could return a method that wraps a function, and calls it you are logged in:
```
const { requireLogin } = useRequireLogin();

return <>
   <Button onClick={requireLogin(showPurchaseModal)} />
    {/* when used on an anchor link, it just prevents the link from being triggered */}
   <Link href='/profile' onMouseDown={requireLogin} />
</>

```

2024-10-01 04:03 UTC, mattcasey requested changes
Look good but one request to change: the redirect after login should actually go to the page you're trying to get to. For example, if you click on Notifications, i should drop you into notifications after login. In the onClick handler on an anchor, it could use the href instead of window.location.pathname

2024-10-01 20:34 UTC, valentinludu commented
> Look good but one request to change: the redirect after login should actually go to the page you're trying to get to. For example, if you click on Notifications, i should drop you into notifications after login. Right now it just takes me back to home. In the onClick handler on an anchor, it could use the href instead of window.location.pathname

Just pushed an improvement rn.

2024-10-01 20:34 UTC, valentinludu commented on apps/scoutgame/components/common/ScoutButton/ScoutButton.tsx
> +      <SignInModalMessage open={authPopup} onClose={() => setAuthPopup(false)} />
Yes. We can discuss tomorrow improvements for the whole app.

2024-10-02 02:26 UTC, mattcasey approved these changes

2024-10-02 02:57 UTC, merged