SG: Added mixpanel events tracking
charmverse/app.charmverse.io pull request #4754
Opened 2024-10-07 11:12 UTC by Devorein

### WHAT

### WHY

2024-10-07 18:20 UTC, mattcasey commented on packages/mixpanel/package.json
new package - nice :)

2024-10-07 18:22 UTC, mattcasey commented on packages/scoutgame/src/builderNfts/mintNFT.ts
> +    builderId: builderNft.builderId,
you need to pass in a userId here for it to connect to a profile. i'd also like to see what types u think are needed... 'tokenId' is kind of meaningless for Mixpanel. Really we probably just need the builder's name as an attribute of the nft u bought.

2024-10-07 18:24 UTC, mattcasey commented on apps/scoutgame/lib/users/findOrCreateUser.ts
> +    userId: newScout.id,
why is userId stored on the profile object? isnt it already the distinct id?

2024-10-07 18:30 UTC, mattcasey requested changes
- Left some comments about specific fields to include/exclude.

- For updating the user profiles, can we just set up a cron job that runs once a day for now? Then we don't have to worry about calling updateUserProfile in various places. We don't even need to run a script to update existing people.

Less important:
- I think adding types for the user profile and event meta we are tracking would be helpful. right now u could pass anything into 'updateUserProfile' for instance. I am fine if the mixpanel package is opinionated about scoutgame - we can always refactor later when we want to shaer the code wth other apps. but we may actually be putting this all in its own repo eventually anyway

2024-10-08 11:29 UTC, Devorein commented on packages/scoutgame/src/builderNfts/mintNFT.ts
> +    builderId: builderNft.builderId,
yeah I think so, we can also track the amount purchased to see if people are buying in bulk also whether its paid in points or not.

2024-10-08 11:31 UTC, Devorein commented on apps/scoutgame/lib/users/findOrCreateUser.ts
> +    userId: newScout.id,
ahh right

2024-10-08 11:32 UTC, Devorein commented on apps/scoutgamecron/src/scripts/createScoutMixpanelProfiles.ts
> +      userId: scout.id,
I don't see the point of adding onboarded and agreed to TOS since these will always be true. Unless we programmatically create the scouts and they still haven't logged in to scoutgame

2024-10-10 15:37 UTC, mattcasey approved these changes

2024-10-10 16:29 UTC, merged