Snoozing gnosis safe transactions
charmverse/app.charmverse.io pull request #481
Opened 2022-05-17 21:03 UTC by Devorein

2022-05-17 22:42 UTC, mattcasey commented on charmClient.ts
> +    return http.PUT('/api/profile/snoozeTransactions', payload);
can you put this under api/profile/gnosis-safes/snoozeTransactions?

2022-05-17 22:45 UTC, mattcasey commented on components/profile/tasks/GnosisTasksList.tsx
> +  const filteredSnoozedUsers: UserWithGnosisSafeState[] = [];
Why not put this on `GnosisTransactionPopulated`? I designed it so that we do all the data joining in one place on the backend. I'll need this info for email notifications as well, which won't be importing this React component

2022-05-17 22:48 UTC, mattcasey commented on components/profile/tasks/GnosisTasksList.tsx
> +      <Box display='flex' justifyContent='space-between'>
i think this Box element is unecessary since it has one child only

2022-05-17 22:50 UTC, mattcasey commented on components/profile/tasks/GnosisTasksList.tsx
> +              <Box px={3} height={rowHeight} display='flex' alignItems='center' gap={1}>
this 'gap' rule doesn't seem to affect the layout?

2022-05-17 22:51 UTC, mattcasey commented on components/profile/tasks/GnosisTasksList.tsx
> +    <Box sx={{ float: 'right' }}>
<Box float='right'>. sx properties are much slower than normal props. not a big deal, but if you're gonna use Box you might as well use the built-in props

2022-05-17 22:52 UTC, mattcasey commented on lib/users/getUser.ts
> +      userGnosisSafeState: true
i dont think this belongs on the user profile. it's hard to maintain that we update the profile everywhere. it could jsut be part of the gnosis tasks query

2022-05-17 22:53 UTC, mattcasey commented on prisma/schema.prisma
> +  userGnosisSafeState       UserGnosisSafeState?
this could be called "gnosisSafeState"

2022-05-17 22:57 UTC, mattcasey requested changes
please put the logic to know who snoozed into gnosis.tasks, or i'll have to rewrite it later. other than that, some style comments that aren't blocking

2022-05-18 09:45 UTC, Devorein commented on charmClient.ts
> +    return http.PUT('/api/profile/snoozeTransactions', payload);
I agree I thought of doing that. Let me do that asap.

2022-05-18 09:55 UTC, Devorein commented on components/profile/tasks/GnosisTasksList.tsx
> +      <Box display='flex' justifyContent='space-between'>
Thank you for catching that. I initially placed the snooze button there but after removing it I forgot to delete the `Box`

2022-05-18 09:57 UTC, Devorein commented on components/profile/tasks/GnosisTasksList.tsx
> +              <Box px={3} height={rowHeight} display='flex' alignItems='center' gap={1}>
Yep, same mistake as above. I placed the snooze icon beside the nonce as we thought of showing it for each task, but forgot to remove it. Also since we aren't using any special `Typography` specific stuff over where I removed that as well (`Typography` for showing nonce value)

2022-05-18 09:57 UTC, Devorein commented on prisma/schema.prisma
> +  userGnosisSafeState       UserGnosisSafeState?
oops, you're right. I updated the casing but totally forgot to remove the redundant user prefix

2022-05-18 10:20 UTC, Devorein commented on components/profile/tasks/GnosisTasksList.tsx
> +  const filteredSnoozedUsers: UserWithGnosisSafeState[] = [];
I thought we would be duplicating information then since it's not a per-transaction level snoozing. But considering your use case I've moved it inside `GnosisTransactionPopulated`

2022-05-18 11:04 UTC, Devorein commented on lib/users/getUser.ts
> +      userGnosisSafeState: true
Yeah, we talked about that during the meeting but I wasn't sure how to do so. Maybe a separate endpoint as Mo mentioned that returns the user's gnosis-safe state is different from the one we use for `/profile`, but for now, I've just added `user` field when retrieving the tasks just as you mentioned above.

2022-05-18 13:19 UTC, merged