Use a global provider for optimistic purchases
charmverse/app.charmverse.io pull request #4868
Opened 2024-10-22 14:18 UTC by valentinludu

### WHAT
After purchase, show the success view and send the user a message when the transaction succeeded on the blockchain.
Update server components with import 'server-only'

### WHY
We needed a way to optimistically update a user purchase

2024-10-25 16:26 UTC, mattcasey commented on .env.test.local.example
> +REACT_APP_BUILDER_NFT_CONTRACT_ADDRESS=0x2cba9c6e0c14da826b0ec689cabf02a6f6b9808e
this is not necessary right? we're not calling a real contract?

2024-10-25 16:27 UTC, mattcasey approved these changes

2024-10-27 03:29 UTC, mattcasey commented on apps/scoutgame/playwright.config.ts
> +  timeout: 10 * 10000,
100 seconds is too long

2024-10-27 03:29 UTC, mattcasey requested changes
please clean up the test config

2024-10-27 08:22 UTC, valentinludu commented on apps/scoutgame/playwright.config.ts
> +  timeout: 10 * 10000,
I reverted everything from this file

2024-10-27 08:23 UTC, valentinludu commented on .env.test.local.example
> +REACT_APP_BUILDER_NFT_CONTRACT_ADDRESS=0x2cba9c6e0c14da826b0ec689cabf02a6f6b9808e
I reverted!

2024-10-28 11:58 UTC, merged