Profile details section
charmverse/app.charmverse.io pull request #492
Opened 2022-05-20 20:37 UTC by AndreiMitrea

2022-05-24 16:17 UTC, Devorein requested changes

2022-05-24 16:17 UTC, Devorein commented on components/profile/public/components/IdentityModal.tsx
> +  const useIntegration = (type: IntegrationType) => {
I assume this is WIP

2022-05-24 16:17 UTC, Devorein commented on components/profile/public/components/SocialModal.tsx
> +  discordUsername: yup.string().notRequired().ensure(),
I like that we are validating these URLs but should we add one for discord as well? Every valid discord id must have the # (hash) and 4 digits with it

2022-05-24 16:17 UTC, Devorein commented on components/profile/public/components/SocialModal.tsx
> +    <Modal open={isOpen} onClose={() => {}} size='large'>
Maybe call `close` over there to close the modal when clicked away?

2022-05-24 16:17 UTC, Devorein commented on components/profile/public/components/SocialModal.tsx
> +              <SvgIcon viewBox='0 -10 70 70' sx={{ color: '#000000', height: '22px' }}>
`fill`: `inherit` might be better as the icons are quite difficult to see in dark mode. But if that doesn't work we might have to use `theme.palette.mode === "dark" ? '#fff' : '#000'`

2022-05-24 16:17 UTC, Devorein commented on components/profile/public/components/SocialModal.tsx
> +              <GitHubIcon style={{ color: '#000000', height: '22px' }} />
Same issue as below

2022-05-24 18:54 UTC, AndreiMitrea commented on components/profile/public/components/SocialModal.tsx
> +              <SvgIcon viewBox='0 -10 70 70' sx={{ color: '#000000', height: '22px' }}>
This is no longer needed, made other updates.

2022-05-25 01:58 UTC, Devorein approved these changes

2022-05-25 04:51 UTC, mattcasey commented on prisma/migrations/20220520130853_added_user_details/migration.sql
> +-- CreateTable
You'll need to re-create this migration file since new migrations have been added to main branch

2022-05-25 04:55 UTC, mattcasey commented on pages/profile/public.tsx
> +  setTitle('');
please add this back. we should always have a page title

2022-05-25 05:02 UTC, mattcasey commented on components/profile/public/components/DescriptionModal.tsx
> +            <StyledButton type='submit'>
please use the standard "components/common/Button". if we change border-radius of buttons, it should be across the app

2022-05-25 05:03 UTC, mattcasey commented on components/profile/public/components/DescriptionModal.tsx
> +          <Box justifyContent='end' mt={3} sx={{ display: 'flex' }}>
with Box you can just write: "display='flex'"

2022-05-25 05:07 UTC, mattcasey commented on components/profile/public/enums/index.ts
> +export * from './IntegrationType';
Please note: we don't really use enums. It's usually better to have an actual array and grab types from that instead:
```
  const INTEGRATION_TYPES = ['Metamask', 'Discord', 'Telegram'] as const;
  type IntegrationType = typeof INTEGRATION_TYPES[number[;
```

2022-05-25 05:11 UTC, mattcasey commented on components/profile/public/types/Social.ts
> +export type Social = {
you should just put types and enums in a standanrd 'interfaces.ts' file. i think splitting up types so much would be a hard pattern to follow everywhere

2022-05-25 05:16 UTC, mattcasey commented on components/profile/public/enums/IntegrationType.ts
> +export enum IntegrationType {
Please note: we should default to use type unions vs enums. It's usually better to have an actual array and grab types from that instead, so consumers can use it as they want (you might want to loop through the options for example):
```
  const INTEGRATION_TYPES = ['Metamask', 'Discord', 'Telegram'] as const;
  type IntegrationType = typeof INTEGRATION_TYPES[number[;
```

2022-05-25 05:18 UTC, mattcasey commented on components/profile/public/components/UserDetails.tsx
> +  const [isDescriptionModalOpen, setIsDescriptionModalOpen] = useState(false);
check out some examples in our code using `material-ui-popup-state`. This version is fine, but I've found the library saves me a couple lines and is easier to read.

2022-05-25 05:21 UTC, mattcasey commented on components/profile/public/components/UserDetails.tsx
> +  const { userDetails, setUserDetails } = useUserDetails();
i would have just called charmClient here with useSWR:
```
const { data: userDetails, mutate } = useSWR('userDetails', () => charmClient.getUserDetails());
```
You can call mutate() to refresh the data. I usually wouldn't write a hook unless there was more logic around the satte or I needed it elsewhere

2022-05-25 05:23 UTC, mattcasey commented on components/profile/public/components/UserDetails.tsx
> +    cursor: pointer;
is this style necessary? the edit svg's are wrapped with IconButton which makes the cursor a pointer already

2022-05-25 05:26 UTC, mattcasey commented on components/profile/public/components/SocialModal.tsx
> +  discordUsername: yup.string().notRequired().ensure()
i'm not sure why, but if i just open the modal and click "Save", discord username is the only one that throws an error when the input is empty.
<img width="644" alt="image" src="https://user-images.githubusercontent.com/305398/170186408-33ef2801-2d5e-46ee-ab8f-e0c2ca547e97.png">

2022-05-25 05:30 UTC, mattcasey requested changes
needs a new migration file, and some style requests otherwise looks good!

2022-05-25 08:24 UTC, AndreiMitrea commented
> needs a new migration file, and some style requests otherwise looks good!

Made the changes. In the new migration file this was also generated:
https://github.com/charmverse/app.charmverse.io/pull/492/files#diff-da24d60257ebf85b963fceedc503d6a6340de7fd9a3024ad69e1ad3946eb5ba8R2

2022-05-25 16:17 UTC, merged