SG: Wallet signin support
charmverse/app.charmverse.io pull request #4929
Opened 2024-10-30 20:11 UTC by Devorein

### WHAT

### WHY

[Card](https://app.charmverse.io/charmverse/add-wallet-sign-in-10943231655417174)

2024-10-30 21:02 UTC, mattcasey requested changes

2024-10-30 21:02 UTC, mattcasey commented on apps/scoutgame/lib/users/queries.ts
> +  farcasterUsername: true
This is not a field that should be on a global type. we do not need your farcaster name for the list of hot builders, builder activities or scouts, etc. we only need farcastername in one place: for your profile. so i only think you need to add it to the return type of getUserByPath, and maybe the SessionUser type

2024-10-30 21:02 UTC, mattcasey commented on apps/scoutgame/lib/users/interfaces.ts
> +  farcasterUsername?: string | null;
this is not "minimal" info

2024-10-30 21:04 UTC, mattcasey commented on apps/scoutgame/lib/utils/generateRandomAvatar.ts
the SVG should be loaded asyncronously really. there's no reason to put this much into the typescript

2024-10-30 21:07 UTC, mattcasey commented on apps/scoutgame/lib/users/findOrCreateUser.ts
> +  farcasterName?: string;
remove farcasterUsername

2024-10-30 21:08 UTC, mattcasey commented on apps/scoutgame/lib/blockchain/config.ts
> +export const loginWithWalletSchema = yup.object({
Not a big deal but we should rename this file. its not a general blockchain config, its just a schema that belongs to the verifyWallet method.

2024-10-30 21:09 UTC, mattcasey commented on apps/scoutgame/lib/users/generateUserPath.ts
> +export async function generateUserPath(displayName: string) {
this should go into the package for scoutgame as it will be needed for scoutgameadmin

2024-10-30 21:11 UTC, mattcasey commented on apps/scoutgame/lib/users/generateUserPath.ts
> +  const path = displayName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
we should make sure the path doesn't end or start with a hyphen, and it would be ideal if you checked for 2+ hyphens

2024-10-30 21:12 UTC, mattcasey commented on apps/scoutgame/lib/users/findOrCreateUser.ts
> +        contentType: 'image/svg+xml'
dont use SVG for these. we should convert to PNG

2024-10-30 21:22 UTC, mattcasey commented on apps/scoutgame/lib/builders/setupBuilderProfile.ts
> +  if (inviteCode !== null && isProdEnv) {
this should work for dev and staging env also

2024-10-31 13:32 UTC, Devorein commented on apps/scoutgame/lib/users/queries.ts
> +  farcasterUsername: true
good point. Updated

2024-10-31 14:43 UTC, mattcasey approved these changes

2024-10-31 15:37 UTC, merged