Nexus tasks page layout
charmverse/app.charmverse.io pull request #493
Opened 2022-05-21 04:35 UTC by Devorein

2022-05-23 16:03 UTC, Devorein commented on components/profile/tasks/IntegrationCard.tsx
> +          <VerticalDivider />
Good catch I wasn't sure whether MUI provided a vertical divider or not but it looks like they do 🤦🏼

2022-05-26 16:49 UTC, mattcasey commented on components/profile/components/ProfileLayout.tsx
> +        <Box py={3} sx={{ px: { xs: '20px', sm: '40px' } }}>
please keep the original margins which are what we use on other pages

2022-05-26 16:49 UTC, mattcasey commented on components/profile/components/ProfileLayout.tsx
> +        <Box py={3} sx={{ px: { xs: '20px', sm: '40px' } }}>
please keep the original margins which are what we use on other pages

2022-05-26 16:52 UTC, mattcasey commented on components/profile/components/ProfileLayout.tsx
> +    <PageLayout hideDrawerOnSmallScreen drawerWidth={55} sidebar={ProfileSidebar}>
drawer  and sidebar are the same thing. Change props names to "hideSidebarOnSmallScreen" and "sidebarWidth".

2022-05-26 16:52 UTC, mattcasey commented on components/profile/components/ProfileLayout.tsx
> +    <PageLayout hideDrawerOnSmallScreen drawerWidth={55} sidebar={ProfileSidebar}>
drawer  and sidebar are the same thing. Change props names to "hideSidebarOnSmallScreen" and "sidebarWidth".

2022-05-26 16:53 UTC, mattcasey commented on components/common/PageLayout/PageLayout.tsx
> +          <Drawer className='Drawer' drawerWidth={drawerWidth} variant='permanent' open={open}>
just use MUI's drawer class, or use a more specific class like "sidebar-drawer". Use hyphenated lowercase for CSS classes

2022-05-26 16:53 UTC, mattcasey commented on components/common/PageLayout/PageLayout.tsx
> +          <Drawer className='Drawer' drawerWidth={drawerWidth} variant='permanent' open={open}>
just use MUI's drawer class, or use a more specific class like "sidebar-drawer". Use hyphenated lowercase for CSS classes

2022-05-26 16:55 UTC, mattcasey commented on components/common/PageLayout/PageLayout.tsx
> +  ${({ theme, hideDrawerOnSmallScreen }) => hideDrawerOnSmallScreen && `
i think it would be better if you just made a style component for Drawer

2022-05-26 16:55 UTC, mattcasey commented on components/common/PageLayout/PageLayout.tsx
> +  ${({ theme, hideDrawerOnSmallScreen }) => hideDrawerOnSmallScreen && `
i think it would be better if you just made a style component for Drawer

2022-05-26 16:57 UTC, mattcasey commented on components/profile/tasks/TasksPage.tsx
> +const TasksPageContainer = styled.div`
these rules should just be applied to ProfileLayout

2022-05-26 16:58 UTC, mattcasey commented on components/profile/tasks/TasksPage.tsx
> +        sx={{
This is a lot of custom styling - should be turned into a styled component instead of inline

2022-05-26 16:58 UTC, mattcasey commented on components/profile/tasks/TasksPage.tsx
> +        sx={{
This is a lot of custom styling - should be turned into a styled component instead of inline

2022-05-26 16:59 UTC, mattcasey commented on components/profile/tasks/TasksPage.tsx
> +          '&': {
pretty sure you don't need "&" you can just apply minHeight at the top level here

2022-05-26 16:59 UTC, mattcasey commented on components/profile/tasks/TasksPage.tsx
> +          '&': {
pretty sure you don't need "&" you can just apply minHeight at the top level here

2022-05-26 16:59 UTC, mattcasey commented on components/profile/tasks/TasksPage.tsx
> +        {(['multisig', 'bounty', 'proposal', 'discussion'] as const).map(tab => (
this list should be defined outside the component at the top of the file

2022-05-26 16:59 UTC, mattcasey commented on components/profile/tasks/TasksPage.tsx
> +        {(['multisig', 'bounty', 'proposal', 'discussion'] as const).map(tab => (
this list should be defined outside the component at the top of the file

2022-05-26 17:04 UTC, mattcasey commented on components/profile/tasks/IntegrationCard.tsx
> +  const mdScreenMediaQuery = theme.breakpoints.down('md');
when we do responsive CSS, the default should always be mobile-first. Please change this so that the rule updates the width at screens > 'md'. And I think using Grid components would be better, 200px is a very arbitrary width and 'my public profile' doesnt even fit on one line

2022-05-26 17:04 UTC, mattcasey commented on components/profile/tasks/IntegrationCard.tsx
> +  const mdScreenMediaQuery = theme.breakpoints.down('md');
when we do responsive CSS, the default should always be mobile-first. Please change this so that the rule updates the width at screens > 'md'. And I think using Grid components would be better, 200px is a very arbitrary width and 'my public profile' doesnt even fit on one line

2022-05-26 17:06 UTC, mattcasey commented on components/profile/tasks/IntegrationCard.tsx
> +            >My Public Profile
make 'my public profile' te same font style/size as the other labels. i dont think this needs a hard-coded width, ideally it should just sit on one line

2022-05-26 17:06 UTC, mattcasey commented on components/profile/tasks/IntegrationCard.tsx
> +            >My Public Profile
make 'my public profile' te same font style/size as the other labels. i dont think this needs a hard-coded width, ideally it should just sit on one line

2022-05-26 17:11 UTC, mattcasey commented on components/profile/tasks/IntegrationCard.tsx
> +          <ExpandCircleDownIcon
replace this with IconButton > ArrowForwardIosIcon. The fact this style doesn't change on hover bothers me, and it doesnt really match what we use elsewhere.

2022-05-26 17:11 UTC, mattcasey commented on components/profile/tasks/IntegrationCard.tsx
> +          <ExpandCircleDownIcon
replace this with IconButton > ArrowForwardIosIcon. The fact this style doesn't change on hover bothers me, and it doesnt really match what we use elsewhere.

2022-05-26 17:13 UTC, mattcasey commented on components/profile/tasks/IntegrationCard.tsx
> +                src={telegramConnected ? '/images/telegram-logo-colored.png' : '/images/telegram-logo-greyscale.png'}
the telegram logo should not have a gradient:

![image](https://user-images.githubusercontent.com/305398/170539883-0b4791a0-4e26-4f0e-b11e-74784fd2d2f1.png)

2022-05-26 17:13 UTC, mattcasey commented on components/profile/tasks/IntegrationCard.tsx
> +                src={telegramConnected ? '/images/telegram-logo-colored.png' : '/images/telegram-logo-greyscale.png'}
the telegram logo should not have a gradient:

![image](https://user-images.githubusercontent.com/305398/170539883-0b4791a0-4e26-4f0e-b11e-74784fd2d2f1.png)

2022-05-26 17:17 UTC, mattcasey commented on components/profile/tasks/IntegrationCard.tsx
> +            [mdScreenMediaQuery]: {
the proper way to define this in MUI is:
```
sx={{ width: { md: '100%' } }} 

```

2022-05-26 17:26 UTC, mattcasey commented on components/profile/tasks/IntegrationCard.tsx
> +                src={telegramConnected ? '/images/telegram-logo-colored.png' : '/images/telegram-logo-greyscale.png'}
Update: I committed a change to the telegram logo so it's flat gray. I think we need to keep the 'shading' on the grey metamask logo, though, otherwise i can't tell what it is.

2022-05-26 17:26 UTC, mattcasey commented on components/profile/tasks/IntegrationCard.tsx
> +                src={telegramConnected ? '/images/telegram-logo-colored.png' : '/images/telegram-logo-greyscale.png'}
Update: I committed a change to the telegram logo so it's flat gray. I think we need to keep the 'shading' on the grey metamask logo, though, otherwise i can't tell what it is.

2022-05-26 17:26 UTC, mattcasey requested changes
see comments

2022-05-26 22:46 UTC, merged