Quests for both apps
charmverse/app.charmverse.io pull request #5099
Opened 2024-12-04 13:46 UTC by valentinludu

2024-12-06 13:45 UTC, Devorein requested changes
Great everything seems to be working like before. A few small design changes are required.

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/770190fc-8cfb-4874-90c9-6c8945343289">
1. The typography color seems to be using primary color rather than white
2. The width of the Quests section should be narrower according to the mockup
3. Clicking on quests when logged out should show a different modal like claim page
4. Scrollbar even when its not required

2024-12-06 13:50 UTC, Devorein commented on apps/scoutgametelegram/lib/session/getSession.ts
> +  return getSessionBase({ sameSite: 'none', secure: true, domain: 'ngrok.app' });
oops a leftover from dev

2024-12-06 13:58 UTC, valentinludu commented on apps/scoutgametelegram/lib/session/getSession.ts
> +  return getSessionBase({ sameSite: 'none', secure: true, domain: 'ngrok.app' });
Reverted!

2024-12-06 21:21 UTC, mattcasey approved these changes
nice!

2024-12-08 15:28 UTC, Devorein approved these changes

2024-12-09 10:53 UTC, merged