Fix for incorrect page ordering
charmverse/app.charmverse.io pull request #574
Opened 2022-06-06 22:07 UTC by AndreiMitrea

Fix for incorrect page ordering on drag and drop.

2022-06-07 07:20 UTC, Devorein commented
@AndreiMitrea Do you face this issue when you drag and drop on a page? [Here](https://www.loom.com/share/21db8e5e26694908bde1e3f143d67fdd) is a loom recording
![image](https://user-images.githubusercontent.com/34683631/172319414-92523525-6097-4f63-be7a-dfc631fa09e6.png)

2022-06-07 07:25 UTC, Devorein commented
Another issue. [Here](https://www.loom.com/share/15bc01b8b32546aa946d73fb72963c3f) is a loom recording. I dragged Page 2.1 and dropped it above Page 3, but it got re-ordered to be underneath it.

2022-06-07 09:33 UTC, AndreiMitrea commented
> @AndreiMitrea Do you face this issue when you drag and drop on a page? [Here](https://www.loom.com/share/21db8e5e26694908bde1e3f143d67fdd) is a loom recording ![image](https://user-images.githubusercontent.com/34683631/172319414-92523525-6097-4f63-be7a-dfc631fa09e6.png)

Yes, ran into that error too. Will look into it. Thank you!

2022-06-08 20:40 UTC, mattcasey requested changes
please provide a better explanation of the bug so we can reproduce. I tested this PR but it seems to make drag/drop never work.. the page always jumps to the t

Not sure if the error @Devorein is posting is related, necessarily. I see that error sometimes even though the drag-and-drop worked... but it would be good to have an explanation at least

2022-06-09 15:28 UTC, mattcasey approved these changes

2022-06-09 15:42 UTC, merged