Remember last visited workspace pages and non-workspace page
charmverse/app.charmverse.io pull request #695
Opened 2022-07-13 19:38 UTC by AndreiMitrea

When accessing workspace, go to its last visited page. Go to last visited non-workspace page when accessing base url.

2022-07-17 04:52 UTC, mattcasey commented on pages/[domain]/index.tsx
> +    if (defaultPage && space && defaultPage.startsWith(`/${space.domain}/`)) {
why do we need to check that space exists or that defaultPage starts with the domain? shouldn't we be able to rely on line 14 to handle those cases?

2022-07-17 04:54 UTC, mattcasey commented on pages/[domain]/index.tsx
> +    if (defaultPage && space && defaultPage.startsWith(`/${space.domain}/`)) {
we should make sure the defaultPage exists in the pages, it's possible the pages have not yet loaded for this space as well, if you're switching between spaces. we may need to either save the pageId instead of the path, or parse the path an compare the paths on each page.

2022-07-17 04:59 UTC, mattcasey commented on components/common/RouteGuard.tsx
> +    const firstSegment: string = pathSegments[0];
I'm curious what's the reason you assert the types when defining variables? For me, it  makes the line longer and harder to read. It also doesn't mirror the style we normally follow

2022-07-17 05:05 UTC, mattcasey commented on components/common/RouteGuard.tsx
> +    const pathSegments: string[] = router.asPath.split('?')[0].split('/').filter(segment => !!segment);
can you extract this logic and add some tests on it?

2022-07-17 05:06 UTC, mattcasey commented on components/common/RouteGuard.tsx
> +      localStorage.setItem(defaultWorkspaceKey, workspaceDomain);
I think it would be more efficient to store the whole router.asPath, so we don't redirect the user twice

2022-07-17 05:11 UTC, mattcasey commented on lib/spaces/index.ts
> +  return domain && !DOMAIN_BLACKLIST.includes(domain) && !domain.includes('?');
This was a great find, but I am sure we either had bugs before or will introduce new bugs with this change. Whenever we've used this method, I guarantee we just didn't consider the string might have a querystring at the end. I suggest we just strip out the querystring part in this method rather than just returning false, otherwise we should strip it out wherever this method is called.

2022-07-17 05:17 UTC, mattcasey commented on components/common/RouteGuard.tsx
> +    const defaultPage = defaultPageKey ? localStorage.getItem(defaultPageKey) : null;
It doesn't seem like you need to retrieve defaultPage or defaultWorkspace. You're retrieving it just to see if we don't need to set it again, which I think defeats the purpose of optimization. It would also reduce the complexity of this code block

2022-07-17 05:19 UTC, mattcasey requested changes
see comments

2022-07-18 11:44 UTC, AndreiMitrea commented on pages/[domain]/index.tsx
> +    if (defaultPage && space && defaultPage.startsWith(`/${space.domain}/`)) {
> why do we need to check that space exists or that defaultPage starts with the domain? shouldn't we be able to rely on line 14 to handle those conditions?

Not really

2022-07-18 11:46 UTC, AndreiMitrea commented on components/common/RouteGuard.tsx
> +    const firstSegment: string = pathSegments[0];
I am not consistent with this but I am used to seeing types when declaring variables. Probably from other programming languages where the types are not inferred.

2022-07-18 16:47 UTC, mattcasey commented on components/common/RouteGuard.tsx
> +    const firstSegment: string = pathSegments[0];
ah ok. i'm coming at it from the other way :) I think it doesn't hurt to be explicit, at least the types are usually colored in an IDE, and I can't imagine working on our codebase w/o one.

2022-07-18 16:48 UTC, mattcasey approved these changes

2022-07-18 19:04 UTC, merged