Fixed comment marks being removed replying
charmverse/app.charmverse.io pull request #707
Opened 2022-07-17 12:39 UTC by Devorein

[ x ] Relocated findChildrenByMark from `prosemirror-utils` to `lib/prosemirror`
[ x ] Added view and threads/votes as a dependency for finding inline action counter

**NOTE**: Please test it out on your end as part of the review

2022-07-18 06:03 UTC, mattcasey commented on lib/prosemirror/findChildrenByMark.ts
> +import { MarkType, Node } from '@bangle.dev/pm';
Please leave a comment with reference to the source code when copy/pasting code

2022-07-18 06:04 UTC, mattcasey requested changes
We should figure out the reason why simply copying code from the library is a fix. This introduces the same method twice in our codebase, since prosemirror-utils is still a dependency, and we also lose any future improvements from the dependency.  It sounds like there is something else going on, since the functions are idempotent and you didn't have to change anything.

2022-07-18 09:32 UTC, Devorein commented
Yes please, that would be really helpful. I'm totally bamboozled as to why the copied version is working and not the original one.

2022-07-18 09:32 UTC, Devorein commented on lib/prosemirror/findChildrenByMark.ts
> +import { MarkType, Node } from '@bangle.dev/pm';
Thank you. I completely missed that. Adding that part.

2022-07-20 16:51 UTC, mattcasey commented
Closing this, it's been fixed in https://github.com/charmverse/app.charmverse.io/pull/712

2022-07-20 16:51 UTC, closed without merging