Cascade board permissions down to the cards
charmverse/app.charmverse.io pull request #711
Opened 2022-07-18 19:33 UTC by motechFR

This PR ensures that whenever we update permissions for a board, they get cascaded downwards

2022-07-19 18:58 UTC, mattcasey commented on .vscode/settings.json
> +  "editor.tabSize": 2,
this doesn't actually do anything right? since we aren't using tabs for spacing?

2022-07-19 18:59 UTC, mattcasey commented on pages/api/permissions/index.ts
> +  }) as Page;
you should handle the case if page comes back null, or else the deconstruction will throw an error

2022-07-19 19:00 UTC, mattcasey commented on pages/api/permissions/index.ts
> +    // TODO - This could be an async job, but there is a risk of the UI being out of sync
this doesn't look like a TODO. it is, technically async, and it's safer to wait for all async ops to complete before returning a response

2022-07-19 19:01 UTC, mattcasey commented on pages/api/permissions/index.ts
> +  // Old behaviour where we setup permissions after a page permission is added
this isn't technically 'old' behavior right?

2022-07-19 19:03 UTC, mattcasey commented on lib/permissions/pages/triggers/board-page-permission-updated.ts
> +export async function boardPagePermissionUpdated ({ boardId, permissionId }: BoardPagePermissionUpdated):
this seems like a good candidate for a test or two

2022-07-19 19:04 UTC, mattcasey commented on pages/api/permissions/index.ts
> +    ].filter(a => a !== null) as PrismaPromise<any>[]);
you can use `isTruthy` from lib/utilities/react and i don't think you'll need to add a type assertion here

2022-07-19 19:10 UTC, mattcasey commented on lib/permissions/pages/triggers/board-page-permission-updated.ts
> +import { PagePermission, Prisma } from '@prisma/client';
filenames should be camelcase. It looks like the permissions folder has a mix of hyphen and camelCase. Same principle as our UI: please try to be consistent

2022-07-19 19:16 UTC, mattcasey requested changes
See my comments... I mostly care about cleaning up comments and the destructuring on the result from a db query

2022-07-20 14:14 UTC, motechFR commented on .vscode/settings.json
> +  "editor.tabSize": 2,
I'm personally using tabs for spacing. Our codebase has a natural tab=2, but my VSCode was acting a bit weird since I reinstalled it.

I plugged this in for code consistency. It won't change anything, only ensuring that tabs still continue to look like what we have so far.

2022-07-20 14:15 UTC, motechFR commented on pages/api/permissions/index.ts
> +    // TODO - This could be an async job, but there is a risk of the UI being out of sync
Agreed, at the time I made a note here as I wasn't sure how long permission cascading would take.

Since we are working on eliminating race conditions, and a more performant assignment process, this TODO is now irrelevant

2022-07-20 14:19 UTC, motechFR commented on pages/api/permissions/index.ts
> +  // Old behaviour where we setup permissions after a page permission is added
You're right, this is an inaccurate statement. Will update accordingly

2022-07-20 14:22 UTC, motechFR commented on lib/permissions/pages/triggers/board-page-permission-updated.ts
> +  // // Find inheritance references to drop
Good spot, thanks, deleted

2022-07-20 14:27 UTC, motechFR commented on pages/api/permissions/index.ts
> +  }) as Page;
Good spot, thanks! All sorted

2022-07-20 14:44 UTC, mattcasey approved these changes

2022-07-20 15:32 UTC, merged