Multi token gates
charmverse/app.charmverse.io pull request #737
Opened 2022-07-26 16:24 UTC by motechFR

- Allow users to select which token gate they will authenticate with

- Simplify token gate logic so that it takes a spaceDomain instead of also containing that form

2022-07-27 01:19 UTC, mattcasey commented on components/common/TokenGate/TokenGateForm.tsx
> +import Grid from '@mui/material/Grid';
Please structure this folder:
TokenGateForm/
TokenGateForm/index.tsx // exports TokenGateForm.tsx
TokenGateForm/TokenGateForm.tsx
TokenGateForm/TokenGateOptions.tsx // this could also be put inside a components folder, but just one or two children can be an exception

2022-07-27 01:23 UTC, mattcasey commented on components/common/TokenGate/TokenGateForm.tsx
> +export default function JoinSpacePage ({ onSubmit: _onSubmit, spaceDomain }: Props) {
rename to "TokenGateForm"

2022-07-27 01:28 UTC, mattcasey commented on pages/join.tsx
> +          isTruthy(spaceInfo) && (
FYI isTruthy is not really needed here - Typescript knows that spaceInfo is not null and will strip it out in the following code for you. I only added that utility for when we map arrays, because Typescript isn't smart enough to strip the null/falsey values of union types on its own:
```
const maybes = [true, false] as const;
// doesn't compile:
const truths: true[] = maybes.filter(Boolean);
// compiles:
const truthsOk: true[] = maybes.filter(isTruthy);
```
const

2022-07-27 01:56 UTC, mattcasey commented on components/common/TokenGate/TokenGateOption.tsx
> +  select: (tokenGate: TokenGateWithRoles) => void,
I think calling this `onSelect` would make it a little more obvious that it's an event handler

2022-07-27 02:07 UTC, mattcasey requested changes
Code looks good, just a few requests! But after reading this, I realize you made it so that the user selects which token gate they want. I was thinking we would simply verify all token gates and apply all applicable roles at once, but this is definitely an improvement. We can check with Alex if it's good for now.

My only concern with the current approach is the green check mark looks like a verification, and it's not obvious that I have to click a gate to select it. At first, I was going to suggest we use a RadioGroup but MUI has another component that looks even better called ToggleButton: https://mui.com/material-ui/react-toggle-button/. What do you think?

Also, we could update the instructions when there's more than one gate: "To join, please select the condition which you want to verify"

2022-07-27 11:58 UTC, motechFR commented on components/common/TokenGate/TokenGateForm.tsx
> +import Grid from '@mui/material/Grid';
Gotcha, makes sense as it allows for flat export hierarchy from components/common even if a specific component has a few sub-components.

2022-07-27 12:08 UTC, motechFR commented on pages/join.tsx
> +          isTruthy(spaceInfo) && (
Understood, sounds like I went a bit overboard on isTruthy usage, will remember that specific use case for next times (so objects don't need it)

2022-07-27 12:13 UTC, motechFR commented on components/common/TokenGate/TokenGateOption.tsx
> +  select: (tokenGate: TokenGateWithRoles) => void,
Done, can we add this to our UI design principles doc under a code styling header?

2022-07-29 03:38 UTC, mattcasey approved these changes

2022-07-29 03:38 UTC, mattcasey commented on components/common/TokenGateForm/TokenGateForm.tsx
> +    window.localStorage.removeItem('lit-auth-signature');
I would like to remove this... it's only to protect if the lit js sdk breaks its compatibility with the current authSig right? I can't see that happening any time soon, at least until we update our lit js sdk. And we don't have the same defensive logic for admins when they create token gates or test them.

2022-07-29 06:01 UTC, mattcasey commented on components/common/TokenGate/TokenGateOption.tsx
> +  select: (tokenGate: TokenGateWithRoles) => void,
we can. but i think this is so small, its weird to sit on its own. if you look at any event handlers in JS, they all start with the word "on". i dont expect someone to be looking this up in our docs

2022-07-29 11:55 UTC, merged