Bounty actions inside card options menu
charmverse/app.charmverse.io pull request #757
Opened 2022-08-01 12:32 UTC by Devorein

2022-08-02 14:27 UTC, mattcasey requested changes
something got messed up with the merge conflicts:
![image](https://user-images.githubusercontent.com/305398/182399203-42a8ddea-4480-4962-92c4-f3d37d4550be.png)

2022-08-03 02:52 UTC, mattcasey commented on components/[pageId]/DocumentPage/components/BountyProperties.tsx
> +  const isSharedPage = router.pathname.startsWith('/share');
this logic exists in DocumentPage already, you should just pass it in as a prop

2022-08-03 02:55 UTC, mattcasey commented on components/[pageId]/DocumentPage/components/BountyProperties.tsx
> +            <Stack gap={1} mb={1} width='100%'>
i feel like <Divider /> and no <Stack /> would be simpler to do here. then just add some vertical margin using `sx`

2022-08-03 03:01 UTC, mattcasey commented on components/bounties/components/ApplicationEditorForm.tsx
> +import { yupResolver } from '@hookform/resolvers/yup';
We already have a copy of this as a sub-component inside components/bounties/components/BountyApplicantForm. (I wanted to try nesting some of these because there are too many components in one folder)

2022-08-03 03:07 UTC, mattcasey commented on components/bounties/components/BountiesKanbanView.tsx
> +  const [selectedBounty, setSelectedBounty] = useState<BountyWithDetails | null>(null);
I was going to make a point that you should use the same adjective (whether it's "active" or "selected") for both Page and Bounty vars here, but they actually should be stored in the same state. Doesn't seem like there's a need to de-couple them. I think it would be more clear this way, to show that they should be set together:
```
const [activePage, setActivePage] = useState<{ page: Page, bounty: BountyWithDetails } | null>(null);

```

2022-08-03 03:13 UTC, mattcasey requested changes
see comments

2022-08-03 03:29 UTC, mattcasey commented on components/bounties/components/BountiesKanbanView.tsx
> +          <List dense>
1) no need to optionally pass in toolsMenu. We always want the menu to exist when viewing a page.
2) please reuse the same component from cardDialog.tsx (or possibly even better, have cardDialog import it from PageDialog.. I could see PageDialog become a defacto global page modal)

2022-08-03 09:32 UTC, Devorein commented on components/[pageId]/DocumentPage/components/BountyProperties.tsx
> +  const isSharedPage = router.pathname.startsWith('/share');
Ow good catch. Changing it rn.

2022-08-03 09:34 UTC, Devorein commented on components/bounties/components/ApplicationEditorForm.tsx
> +import { yupResolver } from '@hookform/resolvers/yup';
Ok got another duplicated component `SubmissionEditorForm`. Removed that one as well.

2022-08-03 09:42 UTC, Devorein commented on components/bounties/components/BountiesKanbanView.tsx
> +  const [selectedBounty, setSelectedBounty] = useState<BountyWithDetails | null>(null);
Updated. I agree they both are used in a similar way and when one gets set the other one does as well so no real need to decouple them. Replaced state with activePage as well

2022-08-03 10:24 UTC, Devorein commented on components/bounties/components/BountiesKanbanView.tsx
> +          <List dense>
Gotcha. One reason I made `toolsMenu` options is because when you are creating a bounty for the first time no tools menu is shown on the page dialog. And I refactored the code a bit to do exactly as you said, `cardDialog` now uses `PageDialog` a defacto global page modal component

2022-08-03 14:59 UTC, mattcasey approved these changes

2022-08-03 15:23 UTC, merged