Inline proposal votes
charmverse/app.charmverse.io pull request #765
Opened 2022-08-02 18:46 UTC by motechFR

This PR extends the vote model to provide context on whether this vote is inline or proposal level

It also provides visual differentiation for proposal level votes and inline votes

2022-08-02 19:35 UTC, mattcasey commented on components/nexus/VoteTasksList.tsx
> +  const { pages } = usePages();
looks like you can remove this?

2022-08-02 19:39 UTC, mattcasey commented on components/votes/VotesPage.tsx
> +      <VotesTable votes={sortedVotes} mutateVotes={mutateVotes} />
we should pass in 'undefined' until there is data, so that it shows it is loading. that, or add an 'isLoading' prop?

2022-08-02 20:06 UTC, mattcasey commented on prisma/schema.prisma
> +  context     VoteContext?   @default(inline)
i think you can change this to mandatory since it has a default

2022-08-02 20:07 UTC, mattcasey commented on components/votes/components/VoteIcon.tsx
> +  const proposalIconColor = status === 'InProgress' ? 'primary' : 'secondary';
for now i recommend not coloring the icons, since status is already visible. or maybe have a prop to trigger the color on hover for the sidebar of pages, and it should work for all statuses and types

2022-08-02 20:09 UTC, mattcasey commented on components/votes/VotesPage.tsx
> +      <VotesTable votes={sortedVotes} mutateVotes={mutateVotes} />
I was going to also ask can we check that pages are loaded before showing the votes? It jumps for me since pages load after the votes (this was probably happening before as well).
It looks like we need to export a new 'isLoading' prop from usePages, but that could be useful elsewhere. I can take care of that in another PR if you want

2022-08-02 20:10 UTC, mattcasey requested changes
Few minor requests, overall works well!

2022-08-03 14:51 UTC, mattcasey approved these changes

2022-08-03 16:05 UTC, motechFR commented on components/nexus/VoteTasksList.tsx
> +  const { pages } = usePages();
Thanks, done!

2022-08-03 16:24 UTC, motechFR commented on components/votes/VotesPage.tsx
> +      <VotesTable votes={sortedVotes} mutateVotes={mutateVotes} />
Hey @mattcasey I handled that in this [commit](https://github.com/charmverse/app.charmverse.io/pull/765/commits/8ad4842641ad897d2c6438cc8fa38e89e5f42115)

Pretty simple approach for now, but should avoid the initial flashing. (I considered Object.keys(pages).length === 0 to be a sign that the pages are loading.

2022-08-03 16:27 UTC, motechFR commented on prisma/schema.prisma
> +  context     VoteContext?   @default(inline)
Done 👍

2022-08-03 16:39 UTC, merged