Disabled state for batch bounty payment button
charmverse/app.charmverse.io pull request #771
Opened 2022-08-03 16:34 UTC by Devorein

2022-08-03 18:04 UTC, mattcasey commented on components/bounties/components/MultiPaymentModal.tsx
> +      {!isDisabled && (
is there a reason you added this here? I think it's better to just have the Modal in place rather than add/remove it to the DOM whenever this state changes

2022-08-03 18:14 UTC, mattcasey commented on components/bounties/components/BountySubmissionsTable.tsx
> -      {permissions.userPermissions.review && (
i added this condition because there's no reason someone should need to see application count unless they are also viewing more than just their application

2022-08-03 18:26 UTC, mattcasey commented on components/bounties/components/BountySubmissionsTable.tsx
> -      {permissions.userPermissions.review && (
Also it doesn't really matter, since we'll be completely hiding the table when Mo makes his update :)

2022-08-03 18:28 UTC, mattcasey commented on components/bounties/components/MultiPaymentModal.tsx
> +      <Tooltip arrow placement='top' title={isDisabled ? 'Please ensure that your wallet is connected and on the right chain.' : ''}>
`Batch payment requires at least one Completed bounty on the ${getChainById(gnosisSafeChainId)?.chainName} network`

2022-08-03 18:28 UTC, mattcasey requested changes
please change the tooltip on the button, other stuff is not as important

2022-08-04 13:06 UTC, Devorein commented on components/bounties/components/MultiPaymentModal.tsx
> +      {!isDisabled && (
Yeah correct its unnecessary optimization

2022-08-04 13:08 UTC, Devorein commented on components/bounties/components/MultiPaymentModal.tsx
> +      <Tooltip arrow placement='top' title={isDisabled ? 'Please ensure that your wallet is connected and on the right chain.' : ''}>
Updated. Thank you.

2022-08-04 13:10 UTC, Devorein commented on components/bounties/components/BountySubmissionsTable.tsx
> -      {permissions.userPermissions.review && (
Right, but I asked Alex about this and he said that it should always be visible.

2022-08-04 15:07 UTC, mattcasey approved these changes

2022-08-04 15:37 UTC, merged