Add inline database component
charmverse/app.charmverse.io pull request #791
Opened 2022-08-10 04:51 UTC by mattcasey

**Data model** 
I'm thinking we will add a new Prosemirror type "inlineDatabase" which will need to store a `pageId` and a `source` attribute. `source` would be things like "page", "space_contributors", "google_docs", etc. Open to suggestions for the attribute names or JSON structure (that is something that is hard to change).

**Tasks**
- [x] add inline database component boilerplate
- [ ] add a way to select which board you want to view
- [ ] reuse/refactor the CenterPanel component from focalboard and load the required blocks and pages

**Data Flow**
[1] To start, I'm thinking that the Prosemirror component we build will just query the data it needs based on attributes in the doc. For passing that data into the Focalboard components, I found a couple options and am open to suggestions:
1) According to the docs, it looks like we can just pass in a special context. I have not tested this, but it seems like the least amount of effort: https://react-redux.js.org/using-react-redux/accessing-store#providing-custom-context
2) Replacing Redux with Context inside of CenterPanel. I looked around and this definitely seems doable, but it's hard to estimate just reading the code. At least, long-term the work won't be wasted since we are using Context everywhere else.

Things we might do in the future/separate PR:
- [ ] add more options in the "/" menu to add a gallery view, table, board, etc. like Notion has
- [ ] add a way to create a new database (which could be a new page with type = 'inline_board')?

2022-08-12 12:06 UTC, Devorein commented
Can't seem to create a new board from the left sidebar. This is the error that is shown
![image](https://user-images.githubusercontent.com/34683631/184350515-4c283243-9f2d-4c63-8557-eab6151c703f.png)

2022-08-12 12:20 UTC, Devorein requested changes
Looks really good and is almost fully functional apart from the bug mentioned above

2022-08-12 21:37 UTC, mattcasey commented
@Devorein i just moved ReactDNDProvider to the _app. I believe it's always attaching a listener to window anyway. This fixed drag and drop for kanban boards and table columns for me. I couldn't reproduce your error but maybe it is fixed as well.

2022-08-15 09:25 UTC, Devorein approved these changes

2022-08-26 13:23 UTC, merged