Resolve threads from removed document text
charmverse/app.charmverse.io pull request #792
Opened 2022-08-10 06:08 UTC by Devorein

2022-08-11 17:34 UTC, mattcasey commented on charmClient.ts
> +  resolveMultipleThreads (payload: ResolveMultipleThreads) {
please put this next to the other calls to api/threads

2022-08-11 17:37 UTC, mattcasey commented on components/common/CharmEditor/CharmEditor.tsx
> +  const onContentChangeDebounced = onContentChange ? debounce((view: EditorView, prevDoc?: Node<any>) => {
isn't prevDoc always there?

2022-08-11 17:39 UTC, mattcasey commented on components/common/CharmEditor/CharmEditor.tsx
> +      onContentChange?: (view: EditorView, prevDoc: Node<any>) => void,
I think `EditorState['doc']` would be a slightly more accurate/informative type to use instead of `Node<any>`

2022-08-11 18:02 UTC, mattcasey commented on components/common/CharmEditor/CharmEditor.tsx
> +        charmClient.resolveMultipleThreads({
it would be good to add a .catch() here and log the error

2022-08-11 18:04 UTC, mattcasey commented on components/common/CharmEditor/CharmEditor.tsx
> +  }, 1000) : undefined;
we should keep this at 100 please. i don't think we should extend the delay for calling onContentChange

2022-08-11 18:11 UTC, mattcasey commented on lib/inline-comments/extractDeletedThreadIds.ts
> +export function extractDeletedThreadIds (schema: Schema, curDoc: Node, prevDoc: Node) {
good candidate for a test or two

2022-08-11 18:12 UTC, mattcasey commented on pages/api/threads/resolve.ts
> +  const { threadIds, pageId } = req.body as {
should be `as ResolveMultipleThreads`?

2022-08-11 18:13 UTC, mattcasey commented on lib/threads/interfaces.ts
> +export interface ResolveMultipleThreads {
ResolveMultipleThreads sounds like an action.. i think a better name for interface could be `MultipleThreadsInput`

2022-08-11 18:17 UTC, mattcasey requested changes
This is a good size PR and I just had a few comments. When testing, I noticed that the comments' state doesn't update in the sidebar until I refresh the page or collapse and then hide comment sidebar. That should be fixed before we go to production

2022-08-12 05:40 UTC, Devorein commented on charmClient.ts
> +  resolveMultipleThreads (payload: ResolveMultipleThreads) {
Updated in the latest commit

2022-08-12 05:43 UTC, Devorein commented on components/common/CharmEditor/CharmEditor.tsx
> +  const onContentChangeDebounced = onContentChange ? debounce((view: EditorView, prevDoc?: Node<any>) => {
Yes it's provided but we are calling `onContentChangeDebounced` when we have stopped resizing (for example image or video), by calling `onResizeStop`. So I decided not to pass the `prevDoc` there and which would bypass auto thread resolving

2022-08-12 05:44 UTC, Devorein commented on components/common/CharmEditor/CharmEditor.tsx
> +      onContentChange?: (view: EditorView, prevDoc: Node<any>) => void,
Updated and yeah good point. I usually hover over types and then just copy paste but this is a bit more abstract.

2022-08-12 05:47 UTC, Devorein commented on components/common/CharmEditor/CharmEditor.tsx
> +        charmClient.resolveMultipleThreads({
Nice catch, I've updated it to log the error

2022-08-12 05:59 UTC, Devorein commented on components/common/CharmEditor/CharmEditor.tsx
> +  }, 1000) : undefined;
Oh I think I first added 1000 ms to test it out then completely forgot to remove it. 1000 ms delay is very noticeable. Sorry for that. I've reverted back the 1000ms delay for content change to 100ms and added a 1000ms denounced call to resolve the threads

2022-08-12 06:00 UTC, Devorein commented on lib/inline-comments/extractDeletedThreadIds.ts
> +export function extractDeletedThreadIds (schema: Schema, curDoc: Node, prevDoc: Node) {
Yep gonna write them right now

2022-08-12 06:30 UTC, Devorein commented on lib/inline-comments/extractDeletedThreadIds.ts
> +export function extractDeletedThreadIds (schema: Schema, curDoc: Node, prevDoc: Node) {
Done. The most difficult part of the setup but this is a good step towards writing tests for our prosemirror stuffs

2022-08-12 06:33 UTC, Devorein commented on pages/api/threads/resolve.ts
> +  const { threadIds, pageId } = req.body as {
Correct. Wrote it over there first, then realized its gonna be needed in a lot of other places so might as well write the type for it, but forgot to replace it back when destructuring the payload

2022-08-12 06:37 UTC, Devorein commented on lib/threads/interfaces.ts
> +export interface ResolveMultipleThreads {
Should we come up with a convention on how to write payload types? Maybe `ResolveMultipleThreadsPayload` or `ResolveMultipleThreadsInput`? Because I can see that we are writing the payload types very close to the function name in quite a few other places.

2022-08-12 08:06 UTC, mattcasey commented on lib/threads/interfaces.ts
> +export interface ResolveMultipleThreads {
either of those would be good. Since this is so coupled to the request i think it belongs in the api folder, honestly

2022-08-12 08:23 UTC, mattcasey approved these changes

2022-08-12 11:03 UTC, merged