Feat/avatar nft
charmverse/app.charmverse.io pull request #794
Opened 2022-08-11 16:06 UTC by msadura

- picking default NFT avatar while creating new user
- loading user's NFTs 
- showing nft gallery where user can pick one as avatar
- a bit of refactor in a few places

https://user-images.githubusercontent.com/5198394/184178830-e0e45d45-babf-485c-aa84-8938901ec862.mp4

2022-08-11 18:22 UTC, mattcasey commented on prisma/schema.prisma
> +  avatarTokenChain  Int?
Hm, this could also be `avatarContractChain`. What about `avatarNetwork` or `avatarBlockchain`? or change `avatarContract` to `avatarTokenContract` so we're consistent.

2022-08-11 18:25 UTC, mattcasey commented on pages/api/profile/avatar.ts
> +    res.status(400).json({ error: 'Invalid avatar data' });
we're in the process of replacing this pattern with throwing exceptions. Can you change this to:

```
import { InvalidInputError } from 'lib/utilities/errors';
...
throw new InvalidInputError(`Invalid avatar data`);
```

2022-08-11 18:34 UTC, mattcasey commented on components/common/HexagonalAvatarMask.tsx
> +        <clipPath clipPathUnits='objectBoundingBox' id='hexagon-avatar' transform='scale(0.005 0.005319148936170213)'>
at first i was going to warn about the 'id' prop and that it needs to be unique, but i saw we just need one instance of this to reference. 'id' could be a prop that gets passed in?

2022-08-11 18:38 UTC, mattcasey commented on components/profile/PublicProfile.tsx
> +import UserDetails, { UserDetailsProps } from './components/UserDetails/UserDetails';
a pattern we usually implement is to add an `index.tsx` file that re-exports the default component and optionally the other exports as well. This makes the imports look cleaner:
```
import UserDetails from './UserDetails';
export default UserDetails;
export * from './UserDetails';
```

2022-08-11 18:42 UTC, mattcasey commented on components/profile/components/NftAvatarGallery/NftAvatarGallery.tsx
> +import Dialog from '@mui/material/Dialog';
FYI we have a transformation step from Next that maps  `import { Dialog } from '@mui/material'` to the tree-shaking-friendly format. I find it's easier to add/remove components this way, also IDE's will automatically create the imports this way.

2022-08-11 18:44 UTC, mattcasey commented on components/profile/components/NftAvatarGallery/NftAvatarGallery.tsx
> +import { NftGalleryItem } from 'components/profile/components/NftAvatarGallery/NftGalleryItem';
this should be a relative import:
`import NftGalleryItem from './NftGalleryItem';`

And each component file/folder should export the component by default.

2022-08-11 18:47 UTC, mattcasey commented on components/profile/components/NftAvatarGallery/NftAvatarGallery.tsx
> +        <Box sx={{ position: 'absolute', top: 0, right: 0, left: 0, bottom: 0, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
this would be a good candidate for styled components

2022-08-11 18:48 UTC, mattcasey commented on components/profile/components/NftAvatarGallery/NftAvatarGallery.tsx
> +            )) : <Box sx={{ p: 4, textAlign: 'center' }}><Typography>You do not own any NFTs</Typography></Box>}
I think you could make more use of MUI's props (sx is slightly slower for rendering than props, apparently):
```
<Box p={4}><Typography align='center'>...</Typography></Box>
```

2022-08-11 18:48 UTC, mattcasey commented on components/profile/components/NftAvatarGallery/NftAvatarGallery.tsx
> +            {nfts?.length ? nfts?.map(nft => (
i think it's unecessary to check for length when mapping or looping over arrays because it's basically a no-op, and one less if/else condition to read

2022-08-11 18:54 UTC, mattcasey commented on components/profile/components/NftAvatarGallery/NftGalleryItem.tsx
> +      onMouseEnter={() => setIsHovered(true)}
i like the attention to detail :)

2022-08-11 19:09 UTC, mattcasey commented on components/profile/components/UserDetails/userDetails.hook.ts
> +import { useState } from 'react';
For organization, please create a folder 'hooks' and put useUserDetails as a file inside the folder

2022-08-11 19:12 UTC, mattcasey commented on components/profile/components/UserDetails/UserDetails.tsx
> +  const { handleUserUpdate, handleNftAvatarUpdate, isSaving } = useUserDetails({ readOnly, user, updateUser });
ya i think this is a good cleanup

2022-08-11 19:19 UTC, mattcasey commented on components/settings/workspace/LargeAvatar.tsx
> +  const onUploadClick = () => {
`function onUploadClick() { }` is our preferred format to define functions

2022-08-11 19:24 UTC, mattcasey commented on components/settings/workspace/LargeAvatar.tsx
> +      {canSetNft && (
this almost feels like it should just be a new component, say `NFTAvatar` that wraps LargeAvatar. I'm ok with this for now though

2022-08-11 19:29 UTC, mattcasey commented on hooks/useMyNfts.ts
> +  const { data, error: serverError } = useSWR('/nfts/list', () => charmClient.nft.list(user?.addresses || []));
I think it would be better to just use the addresses on the server-side session. We don't need to expose a free API service for checking anyone's NFTs. Also, I'm not sure there's an actual bug but if we call this before the user is loaded, we'd never see your NFT's because '/nfts/list' is a static key. you would want to do something like `useSWR(user ? '/nfts/list' : null, ...)` or `useSWR(`/nfts/list/{user?.id}`, ...)`

2022-08-11 19:32 UTC, mattcasey commented on lib/blockchain/provider/alchemy.ts
> +export const alchemyApi = { getNfts, getNft, getOwners };
i'd prefer we just use, as needed:
```
import * as alchemyApi from 'lib/blockhain/provider/alchemy
```

2022-08-11 19:34 UTC, mattcasey commented on lib/blockchain/provider/types.ts
> +type NftMedia = {
please use 'interfaces.ts' instead of 'types.ts', again just for consistency sake

2022-08-11 19:36 UTC, mattcasey commented on lib/blockchain/provider/types.ts
> +  thumbnail: string
we've been adding semi-colons to end of each line for types and interfaces. It bugs me that TS allows comma, semi-colon, nothing... i wonder if we could add a lint rule for this?

2022-08-11 19:39 UTC, mattcasey commented on lib/users/createUser.ts
> +    const avatar = await getDefaultAvatar(address, userId);
please add a try/catch around this. i realize you added one for the call to S3 but not the call to alchemy, i think it's best to put it here since creating a user profile is high priority. (you could say the same about getENSName, but at least it does gracefully handle the error already)

2022-08-11 19:40 UTC, mattcasey commented on lib/users/getDefaultAvatar.ts
> +      log.debug('Failed to upload default NFT avatar', e);
log.warn would be better

2022-08-11 19:42 UTC, mattcasey commented on lib/users/interfaces.ts
> +   avatarTokenChain: number | null
extra whitespace, and missing semi-colon

2022-08-11 19:42 UTC, mattcasey commented on lib/users/interfaces.ts
> +   avatarTokenChain: number | null
btw i like that you added a ffile here. We have some stuff in `models` folder that i'd like to get rid of, since most of our models now come from Prisma, and we've started the practice of putting interfaces inside of `lib`

2022-08-11 19:43 UTC, mattcasey commented on components/common/HexagonalAvatarMask.tsx
> +export function HexagonalAvatarMask () {
please make it a default export

2022-08-11 19:46 UTC, mattcasey commented on pages/api/nft/list.ts
> +export default withSessionRoute(handler);
you only need to wrap a handler with withSessionRoute() if you access `res.session`. i left another comment that we could use this to check `res.session.user.addresses` instead of passing it from the front-end

2022-08-11 19:48 UTC, mattcasey commented on pages/api/profile/avatar.ts
> +  .put(updateAvatar);
please add `requireUser` whenever accessing req.session.user. There's lots of examples

2022-08-12 01:19 UTC, mattcasey requested changes
see comments

2022-08-12 05:37 UTC, msadura commented on prisma/schema.prisma
> +  avatarTokenChain  Int?
lets go with `avatarChain` to keep it short

2022-08-12 05:38 UTC, msadura commented on pages/api/profile/avatar.ts
> +    res.status(400).json({ error: 'Invalid avatar data' });
yup, I really like it 👍

2022-08-12 06:03 UTC, msadura commented on components/profile/components/NftAvatarGallery/NftAvatarGallery.tsx
> +import Dialog from '@mui/material/Dialog';
oh this is actually great! Yeah makes imports much cleaner

2022-08-12 06:21 UTC, msadura commented on components/profile/components/NftAvatarGallery/NftAvatarGallery.tsx
> +            )) : <Box sx={{ p: 4, textAlign: 'center' }}><Typography>You do not own any NFTs</Typography></Box>}
kk, I left Box to properly center text, but used styled props

2022-08-12 06:26 UTC, msadura commented on components/settings/workspace/LargeAvatar.tsx
> +  const onUploadClick = () => {
ok good to know. Personally I prefer arrow functions because they look also cleaner when you wrap them in hooks like useMemo / useCallback

2022-08-12 06:28 UTC, msadura commented on components/settings/workspace/LargeAvatar.tsx
> +      {canSetNft && (
yeah, probably a good idea, especially that orginal "LargeAvatar" is placed in workspace while NFT avatar will be used for user profile

2022-08-12 06:47 UTC, msadura commented on hooks/useMyNfts.ts
> +  const { data, error: serverError } = useSWR('/nfts/list', () => charmClient.nft.list(user?.addresses || []));
good call, I updated it to `useSWR(user && `/nfts/list/${user.id}` so it should fetch unly when there is an user + refetch when it change

2022-08-12 06:51 UTC, msadura commented on lib/blockchain/provider/types.ts
> +  thumbnail: string
I believe that if you use `;` for line endings in code then we should keep them for types / interfaces as well for consistency. I am pretty sure there is lint rule for that, I wil lcheck it out

2022-08-12 07:34 UTC, msadura commented on pages/api/nft/list.ts
> +export default withSessionRoute(handler);
Thx for the explanation, it is all clear now :)

Initially I did not use `session.user.addresses` due to note in user session interface:

```
  interface IronSessionData {
    // this data is only useful for authentication - it is not kept up-to-date!
    user: { id: string, addresses: string[] };
  }
 ```

but I guess user addresses is not something that changes often so I added them to type. Let me know if that will be fine.

2022-08-12 07:52 UTC, msadura commented
I think I was able to address all of the mentioned comments. Thank you for such detailed insights and explanations.

A couple of notes:
- you mentioned formatting types / interfaces - there is eslint rule for that: https://typescript-eslint.io/rules/member-delimiter-style/ and according to it:
> Semicolon style (default, preferred in TypeScript).

I tried to add it but it generated ~1k errors. Ofc lint can easily fix them for us, but I do not want to mix it with this pr to avoid massive conflicts. I think it would be the best to gather a few ideas related to linting / formatting code, add rules (and possibly prettier) and re-format everything at once :)

- I added default exports to components, but this is something to reconsider - default exports are rather considered to be a bad practise, example article: https://blog.piotrnalepa.pl/2020/06/26/default-exports-vs-named-exports/
TLDR:
- with "named" imports you cannot mess names so it is easier to understand what function / component you are looking at
- better support for IDE imports

2022-08-12 16:09 UTC, mattcasey commented on pages/api/nft/list.ts
> +export default withSessionRoute(handler);
oh, this just made me remember that we don't keep the user object updated very well on the session, sorry about that. I'd like to change this to just capture userId, just haven't had time to QA. we can easily use the user id to retrieve the profile, though

2022-08-12 16:10 UTC, mattcasey commented on pages/api/nft/list.ts
> +export default withSessionRoute(handler);
This works for now.

2022-08-12 16:24 UTC, mattcasey commented
You made some good points about named exports. I'd like to keep consistent for now but am open to revisiting this as well.

2022-08-12 16:57 UTC, mattcasey approved these changes

2022-08-12 17:07 UTC, merged