Use hexagonal avatar
charmverse/app.charmverse.io pull request #795
Opened 2022-08-11 16:11 UTC by msadura

- updated avatar usage, to properly indicate nft avatart
- removed unused file

2022-08-11 17:01 UTC, mattcasey requested changes
Looks good. Just a couple small code formatting requests.

Not for this PR, but I also see some room for future clean-up in our code: the only time we should be dealing with `User` type vs `Contributor` in the front-end is for the logged-in user. So I think in any generic component, we shouldn't be needing to import the method `hasNftAvatar`, it would be easier to just require the caller to pass in the computed value.

2022-08-11 19:55 UTC, msadura commented on components/common/UserDisplay.tsx
> +  isNft?: boolean
This is how prettier turns off my attention 😅

2022-08-11 19:57 UTC, msadura commented on components/[pageId]/DocumentPage/components/BountyProperties/components/BountyReviewers.tsx
> +type ReviewersData = {
> Looks good. Just a couple small code formatting requests.
> 
> Not for this PR, but I also see some room for future clean-up in our code: the only time we should be dealing with `User` type vs `Contributor` in the front-end is for the logged-in user. So I think in any generic component, we shouldn't be needing to import the method `hasNftAvatar`, it would be easier to just require the caller to pass in the computed value.

thx for explaining model ideas. In such case we should indeed relay on value from api

2022-08-12 15:59 UTC, mattcasey approved these changes

2022-08-12 16:00 UTC, mattcasey approved these changes

2022-08-12 16:39 UTC, merged