Auto-upload the embedded image
charmverse/app.charmverse.io pull request #813
Opened 2022-08-18 19:19 UTC by motechFR

Converts embedded base64 images to S3 uploads

2022-08-18 20:07 UTC, motechFR commented
Testing complete. This approach will detect existing base64 images and upload them to S3

2022-08-19 09:29 UTC, Devorein requested changes

2022-08-19 09:29 UTC, Devorein commented on components/common/CharmEditor/components/ResizableImage.tsx
> +        node.attrs.src = url;
We need to update the attribute by calling `updateAttrs` and passing in the new src value

2022-08-19 09:36 UTC, Devorein commented
I just tried to copy and paste a large base64 encoded image and the app froze😶
Actually just as you said its happening locally only but not on staging environment

2022-08-19 10:12 UTC, Devorein approved these changes

2022-08-19 12:08 UTC, merged