Initialise playwright config
charmverse/app.charmverse.io pull request #837
Opened 2022-08-24 19:46 UTC by motechFR

Note: Currently having issues installing dependencies

https://github.com/microsoft/playwright/issues/11122

2022-08-30 07:47 UTC, mattcasey commented on package.json
> +    "test:browser:e2e": "dotenv -e .env.test.local -- npx playwright test __e2e__/public-page.spec.ts --timeout=60000",
The command grammar is <action>:<test_suite>:<env>. Also, this tests more than just the browser  - the server too! In this case, I think we should just come up with an alternative to "browser" like "test:e2e"

2022-08-30 07:48 UTC, mattcasey commented on package.json
> +    "debug:playwright": "dotenv -e .env.test.local -- npx playwright test __e2e__/public-page.spec.ts --headed --timeout=0",
maybe "debug:e2e"?

2022-08-30 07:50 UTC, mattcasey commented on tests-examples/demo-todo-app.spec.ts
> +import { test, expect, type Page } from '@playwright/test';
was it intentional to leave this file here? I think it would be better to link to the API docs, and usually our own tests will become better examples.

2022-08-30 07:55 UTC, mattcasey commented on components/common/Page/PageDialog.tsx
> +          <div data-test='page-dialog'>
We should try not to add extra HTML elements for data-test attribute, it can mess with the CSS of surrounding code. Can you move this to the Dialog or DocumentPage component instead?

2022-08-30 07:58 UTC, mattcasey commented on __e2e__/public-page.spec.ts
> +  const publicContext = await browser.newContext({});
a new user should be a separate test

2022-08-30 08:02 UTC, mattcasey commented on __e2e__/public-page.spec.ts
> +  await expect(page.locator('data-test=kanban-card').first()).toBeVisible();
this expectation seems too specific for a test about public pages

2022-08-30 08:02 UTC, mattcasey commented on __e2e__/public-page.spec.ts
> +  await page.goto(`${baseUrl}`);
this goto() seems unecessary based on line 28

2022-08-30 08:07 UTC, mattcasey commented on __e2e__/record-custom.spec.ts
> +import { chromium } from '@playwright/test';
please use camelCase for files

2022-08-30 08:08 UTC, mattcasey commented on __e2e__/public-page.spec.ts
> +import { Browser, chromium, expect, test } from '@playwright/test';
use camelCase for file names

2022-08-30 08:20 UTC, mattcasey commented on testing/playwright.ts
> +  return browserPage.request.post(`${baseUrl}/api/spaces`, {
Did you try using our standard test fixtures from testing/setupDatabase.ts instead of calling the api? Calling the API thru the browser is unnecessary overhead. We don't need to test that the API can be called, and if we wanted to test that it works then we should have tests on the API itself.

2022-08-30 08:23 UTC, mattcasey commented on testing/playwright.ts
> +import { Space } from '@prisma/client';
this file could just go into __e2e__ since that's the only place it will get used, and i would rename it to e2eUtils or something. At first i assumed it was some playwright config

2022-08-30 08:30 UTC, mattcasey requested changes
i added "M:" (for "Must") to the beginning of my comments where i'd like a response at least. The idea is a suggestion from that article about using Must/Could/Should/Would.

2022-08-30 18:39 UTC, motechFR commented on package.json
> +    "test:browser:e2e": "dotenv -e .env.test.local -- npx playwright test __e2e__/public-page.spec.ts --timeout=60000",
Gotcha,

Updated local test to test:e2e, and the ci version to test:e2e:ci

2022-08-30 18:40 UTC, motechFR commented on package.json
> +    "debug:playwright": "dotenv -e .env.test.local -- npx playwright test __e2e__/public-page.spec.ts --headed --timeout=0",
Agreed, let's keep our script names library agnostic

2022-08-30 18:40 UTC, motechFR commented on tests-examples/demo-todo-app.spec.ts
> +import { test, expect, type Page } from '@playwright/test';
Thanks for the spot, we definitely don't need this folder.

We have a working example that uses our own product now

2022-08-30 19:29 UTC, motechFR commented on components/common/Page/PageDialog.tsx
> +          <div data-test='page-dialog'>
@mattcasey Just finished re-testing with alternative approach.

If you see the images below, you can see the selector was dropped. Not sure why this is.

![image](https://user-images.githubusercontent.com/18669748/187519948-486f98f2-dae4-4447-8adf-874fd7d16a5f.png)
![image](https://user-images.githubusercontent.com/18669748/187521877-a18e9b5e-d48a-4901-b325-644d2d44d21e.png)


--

I agree with you, we don't want to have to edit production code just to implement the test.

As a solution, I've updated the dialog selector to rely on the .Dialog classname of the dialog div

2022-08-30 20:16 UTC, motechFR commented on __e2e__/public-page.spec.ts
> +  const publicContext = await browser.newContext({});
Thanks for the push for us to find an even better way!

The key question to achieve this is, how can we run the tests serially, so previous tests can setup data for latter tests?

I found this specific method we can use to define a serially executed test suite (without losing the benefit of parallel execution of all test suites)
https://playwright.dev/docs/api/class-test#test-describe-serial

The tests are now split in 2

2022-08-30 20:23 UTC, motechFR commented on __e2e__/public-page.spec.ts
> +  await expect(page.locator('data-test=kanban-card').first()).toBeVisible();
I was running into an issue where the modal would collapse before it could get interacted with properly.

My solution was to wait for the page's board to finish rendering, and only then interact with the share modal

2022-08-30 20:34 UTC, motechFR commented on __e2e__/record-custom.spec.ts
> +import { chromium } from '@playwright/test';
I've added some documentation inline about this page's purpose.

It allows us to spin up a logged in space and start recording our interactions, generating various playwright code assertions we can copy paste into a test.

2022-08-30 20:42 UTC, motechFR commented on testing/playwright.ts
> +  return browserPage.request.post(`${baseUrl}/api/spaces`, {
There are 2 aspects that led to this approach of passing calls through the browser:

1. Our setupDatabase imports prisma. Using these methods in the browser causes a compilation error

2. I did go with direct API calls, but then had to handle the returned cookies. With the current approach, the browser calls create user endpoint, and handles the setting of the returned cookie.

2022-08-30 20:45 UTC, motechFR commented on testing/playwright.ts
> +import { Space } from '@prisma/client';
Makes sense, I've relocated the page

2022-08-30 21:03 UTC, motechFR commented
@mattcasey Thanks for all the feedback. All implemented and works in CI too.

For running the tests, you should be able to use **npm run test:e2e** and it'll run automagically.

You can copy the command content and add "--headed" option so you actually see what's going on in the browser

2022-08-31 18:58 UTC, mattcasey approved these changes
works now, nice job

2022-09-02 13:48 UTC, merged