Hide user nft in nexus profile
charmverse/app.charmverse.io pull request #852
Opened 2022-08-28 16:43 UTC by Devorein

2022-08-28 20:14 UTC, msadura requested changes

2022-08-28 20:14 UTC, msadura commented on components/profile/components/ManageProfileItemModal.tsx
> +  const handleHideProfileItem = (profileItemId: string) => {
Honestly, logic in this component looks a bit nasty.

1) On each update you run a lot of logic which feel unnecessary.
2) For some reason you keep visible / hidden items as separate arrays, just to merge them into single array
3) 2-step updates of hide / show look kinda weird

I think issue in this logic feel like wrong data model. Why do you keep visible / hidden items in 2 separate arrays insteal of 1 with some sort of  `isHidden: boolean` flag?

2022-08-28 20:14 UTC, msadura commented on components/profile/components/ManageProfileItemModal.tsx
> +  const shownProfileItems = shownProfileItemIds.map(profileItemId => profileItemsRecord[profileItemId]);
Honestly `i think this logic needs a bit of rethinking / different data modeling. There is so many maps / merges over the same data that is feels not really optimal.

2022-08-28 20:14 UTC, msadura commented on pages/api/nft/list/[userId].ts
> +  res.status(200).json({
Honestly I do not think this sort of data structure makes sense.
1) You add quite a lot of logic to split hidden/ visible items  on the server
2) Then on client you add even more logic to merge or handle this data on the frontend.

Once again, I believe this data structure is not optimal and it would be better to rethink it a bit to properly fit the purpose of use. I am not sure how do you handle this sor of issues as a team - any brainstorm sessions? CC: @mattcasey

2022-08-28 20:14 UTC, msadura commented on lib/nft/getNfts.ts
> +export async function getNFTs (addresses: string[]) {
THis logic is copied from `pages/api/nft/list/[userId].ts` - can you reuse it there instead of just copying?

2022-08-28 20:14 UTC, msadura commented on pages/api/nft/list/[userId].ts
> +  const nfts = await alchemyApi.getNfts(['0x155b6485305ccab44ef7da58ac886c62ce105cf9'], chainId);
looks like hardcoded temp data for tests

2022-08-28 20:36 UTC, mattcasey commented on components/profile/components/ManageProfileItemModal.tsx
> +const TabPanel = styled(Box)`
Agreed, and he could just use the width attribute: `<Box width='100%' py={2} />`

2022-08-28 20:37 UTC, mattcasey commented on lib/charmClient/interface.ts
> +export interface GetNftsResponse {
i don't think we need yet another interface file, this would also get huge quickly since it's not namespaced. we should just put the interface in the nftAPi file.

2022-08-28 20:41 UTC, mattcasey commented on lib/profileItem/interfaces.ts
> +export interface UpdateProfileItemRequest {
this should go inside the api endpoint file

2022-08-28 20:48 UTC, mattcasey commented on components/profile/components/NftAvatarGallery/NftAvatarGallery.tsx
> -            {nfts?.length ? nfts?.map(nft => (
there's no need to check for a length before mapping. its just more to read, we dont really save any performance

2022-08-28 20:49 UTC, mattcasey commented on pages/api/nft/list/[userId].ts
> +  const hiddenNftIds: Array<string> = (await prisma.profileItem.findMany({
dont use Array<> notation

2022-08-28 21:28 UTC, mattcasey commented on pages/api/nft/list/[userId].ts
> +  res.status(200).json({
In response to your point, I agree we should try to have logic in one place if at all possible. I generally like to put as much logic as possible in the backend, until it has to start handling different logic for more than one 'view'. And there is one big exception: when it's to merge data sources, since the client always has context like users, workspace, info, etc and it allows us to have one source of truth.

Regarding brainstorm sessions, we don't have a standard format, but we do talk a lot ad hoc. I think Safwan and Mo pair fairly often, and sometimes we go through our code at the end of the daily standup (leading sometimes to an hour-long meeting but no one is required to stay for deep dives). A quick 5 minutes call between you too might also be sufficient. When using Discord, default to having discussions in a public channel (usually #team) so that everyone benefits and is aware of any decisions (so try not to use DM so much).

One final note @msadura: when giving feedback I like to keep this article in mind: https://allthecode.co/blog/post/how-to-get-better-at-code-reviews. We don't use the "S/W/C/M:" prefixes they suggest (maybe we should!) but I'll make sure to point out when something is so bad I think it *must* be fixed before merging. Non-optimal code usually falls under "Should" for me, because I want us to prioritize speed over perfection, and our code changes often.

2022-08-28 21:30 UTC, mattcasey commented on scripts/updateUserPoap.ts
> +  const poaps = await prisma.poap.findMany({});
this was not part of the required scope but thanks for taking care of it now

2022-08-28 21:40 UTC, mattcasey commented on components/profile/PublicProfile.tsx
> +      <UserCollectives user={props.user} mutatePoaps={mutatePoaps} poapData={poapData} mutateNfts={mutateNfts} nftData={nftData} />
I agree, in fact i'd say we only need to call the endpoint when the user opens the modal

2022-08-28 21:47 UTC, mattcasey commented on pages/api/profile/items.ts
> +  return res.status(200).json({});
just use .end() instead of json({}), an empty object gives the appearance something is being returned or could be

2022-08-28 21:48 UTC, mattcasey commented on pages/api/profile/items.ts
> +      log.error('Error updating profile items', err);
why is this try/catch necessary? if it's actually an error, then it should bubble up otherwise you should be using log.warn

2022-08-28 21:49 UTC, mattcasey commented on pages/api/profile/items.ts
> +async function updateUserProfileItems (req: NextApiRequest, res: NextApiResponse<any | {error: string}>) {
this whole flow is an anti-pattern right now: why are we not just saving the user actions as they click to hide/show an individual item? but i know it was like that before, so it's a bit beyond scope. i will make a task to remove the "save button"

2022-08-29 08:58 UTC, msadura commented on pages/api/nft/list/[userId].ts
> +  res.status(200).json({
Actually what I want to point here is not that this code must be fixed, but from long-term perspective we can improve our approach for some problems to actually speed things up. From what I see in visible / hidden items processing here is adding complexity, where it does not feel needed. 
Current flow iterates over data on the server side to split them, and then they are merged back on the frontend to be processed + update loop in multiple setState's feel overcomplicated.

> Non-optimal code usually falls under "Should" for me, because I want us to prioritize speed over perfection, and our code changes often.

I totally agree with that, but I think lesson can be still learned for the future. Actually I am not talking about making code perfect, but talking about speed and potential code changes:
- having more logic needs more time to actually write the code
- having more complex code takes more time to understand and review
- talking about code changes - complex data structures are actually harder to change. For example - what if you would like to add some sort of filtering or grouping items by different category that visible / hidden - it would be hardly possible without rewriting solution proposed here.

TLDR: My key point here is not to make code perfect, but rather make it simple. For me also means actually better speed and maintainability so this is somehow aligned with overall team goals :) I still need to learn alot about CV codebase, but I will be happy to help with solving this sort of issues as simple  and fast as possible 👍

2022-08-29 09:37 UTC, Devorein commented on components/profile/PublicProfile.tsx
> +      <UserCollectives user={props.user} mutatePoaps={mutatePoaps} poapData={poapData} mutateNfts={mutateNfts} nftData={nftData} />
I believe we either wanted to make `PublicProfile` the central component to fetch all the data related to that individual user, or other components did make use of the poaps and nfts before. Either way, since it's not being used by any other components I will transfer the code to fetch the nfts and poaps inside `UserCollectives`  (also rename the component to ProfileItem)

2022-08-29 09:48 UTC, Devorein commented on components/profile/components/ManageProfileItemModal.tsx
> +const TabPanel = styled(Box)`
Turns out we didn't even need the styled component, removing `width=100%` didn't change anything. I replaced all `TabPanels` with regular MUI `Box`

2022-08-29 09:52 UTC, Devorein commented on components/profile/components/ManageProfileItemModal.tsx
> +function ProfileItemsTab ({ profileItems, onClick, tab }: { tab: 'visible' | 'hidden', onClick: (profileItemId: string) => void, profileItems: Pick<ProfileItem, 'id' | 'metadata' | 'type'>[]}) {
I'm not sure whether we are following that approach everywhere. We do have a lot of cases where we have multiple components defined inside a single file, maybe have a discussion on when to have a single component inside a file

2022-08-29 10:17 UTC, Devorein commented on components/profile/components/ManageProfileItemModal.tsx
> +  const shownProfileItems = shownProfileItemIds.map(profileItemId => profileItemsRecord[profileItemId]);
I agree that its a bit complex, but the lack of comments doesn't help either. The previous logic was actually a lot harder to follow (even with just poaps). I think we need to update the data that is being send from the backend first before refactoring on the frontend

2022-08-29 10:19 UTC, Devorein commented on lib/nft/getNfts.ts
> +export async function getNFTs (addresses: string[]) {
Yes absolutely. Thank you for catching that 😬

2022-08-29 10:20 UTC, Devorein commented on pages/api/nft/list/[userId].ts
> +  const nfts = await alchemyApi.getNfts(['0x155b6485305ccab44ef7da58ac886c62ce105cf9'], chainId);
Removed thanks 🙏🏼

2022-08-29 10:25 UTC, Devorein commented on lib/charmClient/interface.ts
> +export interface GetNftsResponse {
Yes, I agree. I've relocated it inside `lib/nft/interfaces`

2022-08-29 10:33 UTC, Devorein commented on components/profile/components/NftAvatarGallery/NftAvatarGallery.tsx
> -            {nfts?.length ? nfts?.map(nft => (
The check for length is to handle the case when there is no nfts since its a ternary operator

2022-08-29 10:37 UTC, Devorein commented on pages/api/profile/items.ts
> +  return res.status(200).json({});
Good point. I've updated another place where we are using `.json({})` to just `.end()`

2022-08-29 10:39 UTC, Devorein commented on pages/api/profile/items.ts
> +      log.error('Error updating profile items', err);
Updated

2022-08-29 10:41 UTC, Devorein commented on pages/api/profile/items.ts
> +async function updateUserProfileItems (req: NextApiRequest, res: NextApiResponse<any | {error: string}>) {
Yeah I can create another PR off of this branch to handle that use case, the whole code related to hiding/showing nft/poaps can get a lot more readable if we just use the row-based action pattern and get rid of grouped nfts/poaps (by using a isHidden field)

2022-08-29 17:06 UTC, Devorein commented on components/profile/components/ManageProfileItemModal.tsx
> +  const handleHideProfileItem = (profileItemId: string) => {
This component has been completely removed. We decided on showing a visibility toggle icon beside each dao/nft/poap row to make the code a lot easier to maintain, and frankly for a better UX

2022-08-30 05:32 UTC, mattcasey commented on components/profile/components/ManageProfileItemModal.tsx
> +function ProfileItemsTab ({ profileItems, onClick, tab }: { tab: 'visible' | 'hidden', onClick: (profileItemId: string) => void, profileItems: Pick<ProfileItem, 'id' | 'metadata' | 'type'>[]}) {
We don't have a hard requirement to have a file per component, but it is a good idea to split out children if they are very complicated

2022-08-30 05:38 UTC, mattcasey commented on pages/api/nft/list/[userId].ts
> +  res.status(200).json({
> My key point here is not to make code perfect, but rather make it simple. For me also means actually better speed and maintainability so this is somehow aligned with overall team goals
I agree with that too, and I prefer to let the reviewee make the ultimate judgement call when possible, as it's also an opportunity to learn.

I also like that you mention 'lessons to learn for the future.' Even if the reviewee doesn't make the change now, they can at least keep the feedback in mind for next time or if they revisit this code.

2022-08-30 05:40 UTC, mattcasey commented on components/profile/components/NftAvatarGallery/NftAvatarGallery.tsx
> +            {allNfts.length ? allNfts.map(nft => (
please change this to:
```
  {allNfts.map(nft => (
```

The check for length is unecessary, i'm not sure we can add a lint for something like that

2022-08-30 05:45 UTC, mattcasey commented on lib/profileItem/interfaces.ts
> +export interface UpdateProfileItemRequest {
> Moving it inside the API endpoint file would cause us to unintentionally import client code.
You mean for the client code to import backend code? Because it is a type, you can just use `import type`. Having the interfaces close to the function is more important than build errors.

2022-08-30 06:01 UTC, mattcasey commented on lib/profileItem/interfaces.ts
> +export interface UpdateProfileItemRequest {
I added a "Types" section to our coding style guide: https://app.charmverse.io/charmverse/page-4558717445075624.

2022-08-30 06:04 UTC, mattcasey commented on components/profile/components/NftAvatarGallery/NftAvatarGallery.tsx
> +            {allNfts.length ? allNfts.map(nft => (
sorry, my mistake!

2022-08-30 06:32 UTC, Devorein commented on components/profile/components/NftAvatarGallery/NftAvatarGallery.tsx
> +            {allNfts.length ? allNfts.map(nft => (
Since we are using a ternary operator and handling empty state, we need to check the nft length first

2022-08-30 06:42 UTC, msadura commented on components/profile/components/ManageProfileItemModal.tsx
> +function ProfileItemsTab ({ profileItems, onClick, tab }: { tab: 'visible' | 'hidden', onClick: (profileItemId: string) => void, profileItems: Pick<ProfileItem, 'id' | 'metadata' | 'type'>[]}) {
Yeah I agree that sometimes you can have more than one "internal" component if needed. In this case we are talking about really large file (300+ lines) so it would be much easier to read and follow.

2022-08-30 06:46 UTC, msadura approved these changes
Thx for all the updates! I am approving to not block this, but lets give final voice to @mattcasey :)

2022-08-30 07:41 UTC, mattcasey approved these changes
Approved with two UI requests:
- make the eye icon on the far right, vertically centered (same area as the community rows). we always put actions at the end of the row, and it makes it easier to disable multiple rows quickly
- make the fade-out even more dramatic, like 0.25 opacity
- suggestion: pass in a simple function like "toggleVisibility" callback to the ProfileItems component, so that the logic to mutate state is all handled in PublicPage. See how simple CommunityRow is, we just call updateDaoProfileItem(community) (that function actually toggles visibility, maybe we could re-use it)

2022-08-30 16:19 UTC, merged