Create and configure proposal reviewers and authors
charmverse/app.charmverse.io pull request #861
Opened 2022-08-30 17:33 UTC by Devorein

2022-08-31 01:50 UTC, mattcasey commented on components/[pageId]/DocumentPage/DocumentPage.tsx
> +import { ProposalProperties } from './components/ProposalProperties/ProposalProperties';
needs an index.tsx file so you don't have to import the nested component

2022-08-31 01:52 UTC, mattcasey commented on prisma/schema.prisma
> +  proposalAuthors   ProposalAuthor[]
authoredProposals?

2022-08-31 01:53 UTC, mattcasey commented on prisma/schema.prisma
> +  proposalReviewers ProposalReviewer[]
authoredReviewers? (note: on User model, all the 'reviewers' are THIS user so i think the focus should be on the proposals that are being linked)

2022-08-31 01:55 UTC, mattcasey commented on prisma/schema.prisma
> +  spaceId   String             @db.Uuid
i think this should cascade delete if the space is deleted

2022-08-31 02:14 UTC, mattcasey commented on components/[pageId]/DocumentPage/components/ProposalProperties/ProposalProperties.tsx
> +        <div
always use Box for inline styles. all the ones you'er using are actually props:
`<Box display='flex' height='fit-content' flexGrow={1} />`

2022-08-31 02:18 UTC, mattcasey commented on pages/api/pages/index.ts
> +      createProposal({
at the moment, i think we should just be calling prisma.proposal.create. unless there's extra business logic required, etc. it's more confusing in this example because we use prisma.page directly above.

2022-08-31 09:11 UTC, Devorein commented on components/[pageId]/DocumentPage/DocumentPage.tsx
> +import { ProposalProperties } from './components/ProposalProperties/ProposalProperties';
Updated

2022-08-31 09:14 UTC, Devorein commented on prisma/schema.prisma
> +  proposalAuthors   ProposalAuthor[]
That's a lot better term. Thanks.

2022-08-31 09:17 UTC, Devorein commented on prisma/schema.prisma
> +  proposalReviewers ProposalReviewer[]
Updated

2022-08-31 09:18 UTC, Devorein commented on prisma/schema.prisma
> +  spaceId   String             @db.Uuid
Thats right. I also forgot to add a relation with the space model. Updated.

2022-08-31 09:19 UTC, Devorein commented on components/[pageId]/DocumentPage/components/ProposalProperties/ProposalProperties.tsx
> +        <div
I actually copied pretty much the whole component from our `BountyProperties.tsx` component. I will make the updates in both places.

2022-08-31 09:27 UTC, Devorein commented on pages/api/pages/index.ts
> +      createProposal({
Yes good point. I just transferred all the logic to create a page along with the proposal inside the lib function. It will be easier to test it out

2022-08-31 19:33 UTC, mattcasey commented on lib/proposal/interface.ts
> +export interface UpdateProposalRequest {
this is only used in charmClient, it could just go in that file

2022-08-31 19:33 UTC, mattcasey commented on lib/proposal/interface.ts
> +export type ProposalWithUsers = Proposal & {authors: ProposalAuthor[], reviewers: ProposalReviewer[]}
you could still use interface here with `interface ProposalWithUsers extends Proposal { ... } `

2022-08-31 19:42 UTC, mattcasey commented on prisma/schema.prisma
> +  reviewers ProposalReviewer[]
@Devorein i thoguht during our call today we agreed to break this out into tables for reviewerUsers and reviewerRoles? can you explain here why you decided to keep them in the same table

2022-08-31 19:43 UTC, mattcasey commented on prisma/schema.prisma
> +  group      ProposalReviewerGroup
if this is a discriminator, please name it to 'type'

2022-08-31 19:47 UTC, mattcasey commented on pages/api/pages/index.ts
> +    }) as PageWithProposal;
Please remove this type assertion and handle the 'null' case instead. It actually looks like the types for createProposal may be wrong?

2022-08-31 19:48 UTC, mattcasey commented on pages/api/pages/[id]/index.ts
> +      proposal: {
is this JOIN really necessary?

2022-08-31 19:50 UTC, mattcasey commented on lib/pages/interfaces.ts
> +  proposal?: ProposalWithUsers | null
we need to be passing around less info, not more, in our pages hook. please just query the proposal data you need when looking at a page, sa we do with bounties

2022-08-31 20:11 UTC, mattcasey requested changes
I know this may be painful, but we shouldn't attach the proposal to the global collection of pages. Loading all the content into usePages is already very slow right now and we know we need to reduce it, this moves us in the wrong direction. The data should be loaded when you load a page, similar to how we load the bounties, or we could have a global 'useProposals' hook as well

2022-08-31 20:15 UTC, mattcasey commented on lib/pages/server/getAccessiblePages.ts
> +          authors: true,
remember this data actually can be joined on the frontend, or else be explicit about which user fields you need so we dont pull in private data

2022-08-31 20:34 UTC, mattcasey reviewed
Changes:
1) the usePages hook should only be returning metadata and not content, and this moves us further away from that goal. None of the proposal content is needed in a global sense from what i can tell. Eventually we should just have DocumentPage or ProposalsPage load the extra content they need. You might consider a global useProposals() hook, as @motechFR recommended. But if it's global, it still means we're loading data we don't need, so I'm not sure that will make the job any easier.
2) use user data from the front-end, or be explicit about which fields you need when querying for reviewers and authors so that we don't expose user wallet addressess

2022-09-01 08:17 UTC, Devorein commented on lib/proposal/interface.ts
> +export interface UpdateProposalRequest {
Relocated the type from `lib/proposals/interface.ts` to be inside `charmClient/apis/proposalApis.ts`. Also updated the `updateProposal` lib method to make use of the interface

2022-09-01 08:20 UTC, Devorein commented on lib/proposal/interface.ts
> +export type ProposalWithUsers = Proposal & {authors: ProposalAuthor[], reviewers: ProposalReviewer[]}
Right. I've gotten used to writing `type` everywhere. Updated.

2022-09-01 08:27 UTC, Devorein commented on pages/api/pages/index.ts
> +    }) as PageWithProposal;
Thank you. I just saw it (the types were wrong indeed). Updated.

2022-09-01 08:29 UTC, Devorein commented on lib/pages/server/getAccessiblePages.ts
> +          authors: true,
This itself doesn't pull in private data, just the `userId` and the `proposalId`, no other information as we are not joining with the `user` table

2022-09-01 14:54 UTC, Devorein commented on lib/pages/interfaces.ts
> +  proposal?: ProposalWithUsers | null
Yes, you are right. I've updated to not retrieve the proposal from the page. There is a separate endpoint to fetch an individual proposal and used that

2022-09-01 14:56 UTC, Devorein commented on pages/api/pages/[id]/index.ts
> +      proposal: {
Correct. I've updated the code to fetch only a single proposal rather than join the proposal with the page.

2022-09-01 14:58 UTC, Devorein commented on prisma/schema.prisma
> +  reviewers ProposalReviewer[]
We have decided to go with the current approach and use two optional columns to store the id of the reviewer

2022-09-01 15:03 UTC, Devorein commented on prisma/schema.prisma
> +  group      ProposalReviewerGroup
We have decided to remove the discriminator and do the validation that only either userId or roleId is set in a single record.

2022-09-01 15:59 UTC, mattcasey commented on prisma/schema.prisma
> +  group      ProposalReviewerGroup
@Devorein please remove this field

2022-09-01 16:00 UTC, mattcasey approved these changes

2022-09-01 17:13 UTC, Devorein commented on prisma/schema.prisma
> +  group      ProposalReviewerGroup
Yes updated. It was unfortunately tangled in a lot of places so had to do a lot of QA to make sure nothing was broken

2022-09-01 18:59 UTC, merged