Show status for proposals in table
charmverse/app.charmverse.io pull request #879
Opened 2022-09-05 10:45 UTC by Devorein

2022-09-05 19:59 UTC, mattcasey commented on components/proposals/components/ProposalsTable.tsx
> +import { ProposalStatusChip } from '../../../components/[pageId]/DocumentPage/components/ProposalProperties/ProposalStatusBadge';
It would be better to put shared components inside the components/proposals folder (so move ProposalStatusBadge to here)

2022-09-05 20:05 UTC, mattcasey commented on components/proposals/components/ProposalsTable.tsx
> +        <PageDialog
replace with `usePageDialog`

2022-09-05 20:19 UTC, mattcasey commented on lib/proposal/getProposalsBySpace.ts
> +    include: {
this should be joined with contributors on the frontend

2022-09-05 20:20 UTC, mattcasey commented on pages/[domain]/proposals/index.tsx
> +export default function VotesPage () {
fix "VotesPage"

2022-09-05 20:22 UTC, mattcasey commented on components/proposals/ProposalsPage.tsx
> +    fallbackData: undefined
i don't think this does anything since you're passing in undefined?

2022-09-05 20:23 UTC, mattcasey commented on components/proposals/ProposalsPage.tsx
> +  const { data, mutate: mutateProposals } = useSWR(() => `proposals/${currentSpace?.id}`, () => currentSpace ? charmClient.proposals.getProposalsBySpace(currentSpace.id) : [], {
it's better to return `null` in the first input to useSWR, until currentSpace exists, so that the 2nd function doesn't even get called

2022-09-05 20:24 UTC, mattcasey requested changes
Before this PR is merged, please remove the aggregated user data from ProposalWithUsers - u may want to get rid of this interface completely. we should just be using the hook 'useContributors' to retrieve user data

2022-09-06 06:14 UTC, Devorein commented on components/proposals/components/ProposalsTable.tsx
> +      await charmClient.archivePage(page.id);
Updated.

2022-09-06 06:20 UTC, Devorein commented on components/proposals/components/ProposalsTable.tsx
> +        <PageDialog
Wow. Its so much easier now 🤯 Updated 🥳

2022-09-06 06:23 UTC, Devorein commented on pages/[domain]/proposals/index.tsx
> +export default function VotesPage () {
Oops. Thank you for that. Updated.

2022-09-06 06:24 UTC, Devorein commented on components/proposals/ProposalsPage.tsx
> +  // For now, consider that empty pages list means we are loading pages
The comment was actually there before this PR 👀

2022-09-06 06:27 UTC, Devorein commented on components/proposals/ProposalsPage.tsx
> +    fallbackData: undefined
I copied most of the code from the `VotesPage` component, it was also used there. Removed it from both places as swr by default returns `undefined`

2022-09-06 06:29 UTC, Devorein commented on components/proposals/ProposalsPage.tsx
> +  const { data, mutate: mutateProposals } = useSWR(() => `proposals/${currentSpace?.id}`, () => currentSpace ? charmClient.proposals.getProposalsBySpace(currentSpace.id) : [], {
Updated both in `VotesPage` and `ProposalsPage`

2022-09-06 06:48 UTC, Devorein commented
Right now we are just fetching the `userId` (which is a must) and the `proposalId` for authors and additional `roleId` for reviewers. No data about the author and reviewer is being fetched other than that and we join the data on the frontend using the id.

2022-09-06 06:52 UTC, Devorein commented on lib/proposal/getProposalsBySpace.ts
> +    include: {
It is joined on the frontend with the contributors based on the userId and roleId, we are not getting any other user data (apart from the id) when joining on the backend

2022-09-06 11:15 UTC, Devorein commented
I've added back the filter and sort options for the proposals table. Completely forgot I removed it when copying code from the Votes table. For the sort only Created at is added as an option (we could add more new options later so kept it for now) and as for the filter options its all the available status of the proposal along with 'all' to include proposals of any status

2022-09-06 15:43 UTC, mattcasey approved these changes

2022-09-06 16:07 UTC, merged