Open vote for reviewed proposal
charmverse/app.charmverse.io pull request #888
Opened 2022-09-07 13:19 UTC by Devorein

2022-09-07 20:08 UTC, mattcasey commented on components/[pageId]/DocumentPage/components/ProposalProperties/ProposalProperties.tsx
> +  page: IPageWithPermissions
since page is a requirement i'd probably just grab proposalId from it instead of passing in separately

2022-09-07 20:14 UTC, mattcasey commented on components/common/PageLayout/components/Header/components/Snapshot/PublishToSnapshot.tsx
> +export default function PublishToSnapshot ({ page, disabled = false, button = true }: {button?: boolean, disabled?: boolean, page: Page}) {
Please simplify this:
- the component already uses 'usePages()' hook. This means we can just pass a pageId instead, will also simplify the props for ProposalPropeties (just pass a pageId in instead of the whole page. This will help us when we want to stop passing entire page content around).
- instead of passing in a 'button' prop to determine how to wrap the element, just wrap the element at the call sites in Header.tsx and ProposalProperties with the correct component.

2022-09-07 20:30 UTC, mattcasey commented on components/common/PageLayout/components/Header/components/Snapshot/PublishToSnapshot.tsx
> +      <ListItemButton disabled={disabled}>
actually the link needs to wrap the ListItem or else you can't click the sides of the component. perhaps you could pass in ListItemButton or MenuItem as a 'component' prop?

2022-09-07 20:30 UTC, mattcasey requested changes
can't click the sides of the 'publish to snapshot' menu item anymore because the link is not completely wrapping  the element

2022-09-09 09:31 UTC, Devorein commented on components/[pageId]/DocumentPage/components/ProposalProperties/ProposalProperties.tsx
> +  page: IPageWithPermissions
Good point. Updated.

2022-09-09 09:57 UTC, Devorein commented on components/common/PageLayout/components/Header/components/Snapshot/PublishToSnapshot.tsx
> +export default function PublishToSnapshot ({ page, disabled = false, button = true }: {button?: boolean, disabled?: boolean, page: Page}) {
Updated. Thanks.

2022-09-09 10:21 UTC, Devorein commented on components/common/PageLayout/components/Header/components/Snapshot/PublishToSnapshot.tsx
> +      <ListItemButton disabled={disabled}>
The only prop PublishToSnapshot now takes is the `pageId`. I've wrapped the component with the appropriate components where it's used. It seems like it's not working on production as well.
Updates: I've tried to pass in the component to use as wrapper, but now the modal can't be closed :( I've added a card to handle this, as its getting quite frustrating trying to fix this stupid bug

2022-09-09 12:37 UTC, motechFR commented
Tested with Safwan, this is good to go!

2022-09-09 12:37 UTC, merged