Support multiple chains for Personal NFT
charmverse/app.charmverse.io pull request #916
Opened 2022-09-14 10:12 UTC by Devorein

2022-09-14 15:41 UTC, mattcasey commented on pages/api/profile/avatar.ts
> +    const owners = await alchemyApi.getOwners(avatarContract, avatarTokenId, avatarChain as alchemyApi.SupportedChainId);
The type of avatarChain should be defined on UserAvatar, and we shouldn't need to typecast here since we do it on line 24

2022-09-14 15:44 UTC, mattcasey requested changes
make sure we are not supporting any testnet networks

2022-09-15 11:33 UTC, Devorein commented on pages/api/profile/avatar.ts
> +    const owners = await alchemyApi.getOwners(avatarContract, avatarTokenId, avatarChain as alchemyApi.SupportedChainId);
With that I had to change the type in a lot of function parameters in `lib/blockchain/nfts`, but now they are more strictly typed

2022-09-15 11:41 UTC, Devorein commented on pages/api/nft/list/[userId].ts
> +    RPCList.filter(rpc => SupportedChainIds.includes(rpc.chainId as any)).map(rpc => getNFTs(addresses, rpc.chainId as SupportedChainId))
yep went with a constant array of supported mainnet chain ids.

2022-09-15 13:59 UTC, mattcasey approved these changes

2022-09-15 14:00 UTC, merged