[WIP] Feat/mixpanel
charmverse/app.charmverse.io pull request #942
Opened 2022-09-20 09:22 UTC by msadura

Draft of mixpanel implementation.  I wrapped raw mixpanel instance with our own `track` method which has string event typing - it will guard events and their payload.
Additionally I tried to split event types by category / feature to avoid one gigantic file with all the events.

I still need to handle mixpanel user handling, but let me know what you guys think about this approach / code organisation. @motechFR @mattcasey @Devorein

2022-09-20 14:23 UTC, motechFR commented on lib/analytics/mixpanel/interfaces/ProposalEvents.ts
> +
Alternative style suggestion

_Btw I think as a team we prefer interfaces (let's discuss), but go for type if you need it_

Also for readability of the object typings, newlining and proper indentation are appreciated

Reasons for below:
- It's nicer to know what the actual shape of the event is

```typescript
export interface ProposalCreatedEvent  {
  id: string; 
 workspaceId: string;
 userId: string;
}

export interface ProposalStageChangedEvent {
  id: string;
  workspaceId: string;
  userId: string;
  stageName: string
}

export interface ProposalEvents {
 proposalCreated: ProposalCreatedEvent
 proposalStageChanged: ProposalStageChangedEvent
}

/* Ensures definition of Proposal event names happens locally here*/

export type ProposalEventType = keyof ProposalEvents

```

2022-09-20 14:25 UTC, motechFR commented on lib/analytics/mixpanel/server.ts
> +};
Why are we exporting an obj with a single prop? Why not the function directly?

2022-09-20 14:25 UTC, motechFR commented on lib/users/createUser.ts
> +    mixpanel.track('userCreated', { userId: newUser.id, isWallet: true, isDiscord: false });
Awesome

2022-09-26 08:43 UTC, msadura commented
This pr should be ready to re-review :)

Types for event are updated, introduced a few base types to reuse.

Added events related to user and proposals

2022-09-27 19:57 UTC, mattcasey commented on lib/metrics/mixpanel/interfaces/UserEvents.ts
> +  UserCreated: UserCreatedEvent;
I think these should be user_created, etc.

2022-09-27 19:59 UTC, mattcasey commented on lib/token-gates/applyTokenGates.ts
> +    updateTrackUserProfileById(userId);
Can you make sure to handle possible exceptions? either here using .catch() or internally in the method

2022-09-27 20:00 UTC, mattcasey commented on lib/metrics/mixpanel/server.ts
> +  mixpanelInstance?.track(eventName, mixpanelTrackParams);
we probably need to handle any exceptions here right? i would suggest using async/await for this method, even tho we don't await on it on the call sites. it's good to expose promises as high as possible imo

2022-09-27 20:14 UTC, mattcasey requested changes
looks good, just want to change the event names to match what's in the doc: https://app.charmverse.io/charmverse/page-516372129559042 (UserCreated -> Sign up, for example)

2022-09-28 05:44 UTC, msadura commented on lib/token-gates/applyTokenGates.ts
> +    updateTrackUserProfileById(userId);
good call with exceptions!

2022-09-30 07:26 UTC, msadura commented on lib/metrics/mixpanel/interfaces/UserEvents.ts
> +  UserCreated: UserCreatedEvent;
event names in code will be `event_name` and they will be converted to `Event Name` when send to mixpanel

2022-09-30 07:50 UTC, msadura commented
@motechFR @mattcasey pr udpated:
- changes event names
- added try / catch in mixpanel methods - might not be needed, but will take care of unhandled rejections

2022-10-04 10:32 UTC, msadura commented
Additional updated:
- event data props will also be human readable
- updated logic to verify if user connected via wallet
- updated logic of joining space via public bounty to reflect that in event

2022-10-05 16:12 UTC, mattcasey commented on lib/metrics/mixpanel/server.ts
> +import { capitalize } from 'lodash';
i think mixpanel.ts would be a better filename... we are not planning on having a browser implementation at all

2022-10-05 16:13 UTC, mattcasey commented on lib/metrics/mixpanel/server.ts
> +    'Workspaces Joined': user.spaceRoles.map(sr => sr.spaceId)
use workspace name?

2022-10-05 16:15 UTC, mattcasey commented on lib/metrics/mixpanel/server.ts
> +if (process.env.MIXPANEL_API_KEY && isDev) {
i dont think we need to check 'isDev' here. it should be enough to just use the api key if it's set

2022-10-05 16:17 UTC, mattcasey commented on lib/metrics/mixpanel/trackPageAction.ts
> +export async function trackPageAction (eventName: PageEventNames, userId: string, pageId: string) {
please use object notation, at least for the attributes. i could see someone easily mixing userId and pageId since the'yre both strings

2022-10-05 16:18 UTC, mattcasey commented on lib/metrics/mixpanel/updateTrackUserProfileById.ts
> +    // Failed to update tracking profile
Always log something in the error path, log.warn would be good to use here because it won't trigger alerts but we can use  it for debugging

2022-10-05 16:20 UTC, mattcasey commented on lib/users/createUser.ts
> +    trackUserAction('sign_up', { userId: newUser.id, identityType: 'Wallet' });
Do we need to wait for the user profile to be added before sending a user event?

2022-10-05 16:21 UTC, mattcasey commented on lib/votes/castVote.ts
> +    trackUserAction('new_vote_created', { userId, resourceId: voteId, spaceId: vote.spaceId, platform: 'charmverse' });
i don't think this was chris's intention, "userVote" in our data model is just a user casting their choice on a poll or proposal. i think he meant to track new polls. i asked on the doc

2022-10-05 16:25 UTC, mattcasey commented on pages/api/session/login.ts
> +  updateTrackUserProfile(user);
why do we need to update user profile on sign in? (what properties could have changed?)

2022-10-05 16:31 UTC, mattcasey commented on lib/metrics/mixpanel/interfaces/index.ts
> +export type MixpanelEvent = UserEvents & ProposalEvents & PageEvents
to keep consistent naming convention, 'MixpanelEvent'  should be 'MixpanelEvents'. I think "MixPanelEventMap" would be a bit better

2022-10-05 16:34 UTC, mattcasey commented on lib/metrics/mixpanel/interfaces/PageEvents.ts
> +import type { ResourceEvent, SpaceEvent } from 'lib/metrics/mixpanel/interfaces';
this "works" but it's a recursive dependency. Please fix... 'interfaces/index' imports PageEvents, but PageEvents imports index.ts. Looks like ResourceEvent and SpaceEvent should be their own file

2022-10-05 16:35 UTC, mattcasey commented on lib/metrics/mixpanel/interfaces/ProposalEvents.ts
> +import type { SpaceEvent } from 'lib/metrics/mixpanel/interfaces';
same comment as PageEvents... keep dependencies single-direction. I think it's very confusing to follow even if it works in typescript

2022-10-05 16:57 UTC, mattcasey commented on .ebextensions/00_env_vars.config
> +        MIXPANEL_API_KEY: "{{pull:secretsmanager:/io.cv.app/stg/mixpanel:SecretString:mixpanel_api_key}}"
@msadura i added mixpanel api key and updated your branch with main. We now have an api key for staging (the previous one) and one for production that hasn't been used yet

2022-10-05 19:17 UTC, mattcasey commented
@msadura i know this story's been going on for a while but seems like it's worth adding groups from the git-go: that way we dont need to send 'workspaceName' as part of the event, we can probably just use the workspace id as the group key: https://developer.mixpanel.com/docs/nodejs#sending-group-identifiers-with-events

2022-10-05 19:43 UTC, msadura commented on lib/users/createUser.ts
> +    trackUserAction('sign_up', { userId: newUser.id, identityType: 'Wallet' });
We do not need to wait and we actually don't wait - both actions are async and to not wait for each other

2022-10-05 19:44 UTC, msadura commented on pages/api/session/login.ts
> +  updateTrackUserProfile(user);
It was in case user profile was not existing yet. But if we will migrate all users to mixpanel we can skip this `updateTrackUserProfile` call

2022-10-05 20:11 UTC, msadura commented on pages/api/pages/[id]/details.ts
> +  trackPageAction('page_load', userId, pageId);
it should be loaded for the first time you open a page and then cached so it should not spam this more. I will double check it tho. If this logic will not be sufficient then we will need `/track` endpoint and simply call it when user navigates to as page.

2022-10-05 21:29 UTC, msadura commented
@mattcasey I adressed you comments, thx for review!

spaceId will be send as group indentifier to all mixpanel events (except for login / signup events, because we basically do not have space information there).

2 things to do (I will let you judge if in this PR or separate):
- I need to verify if mixpanel will accept `Space Id[]` in user profile to connect it to proepr groups (docs mention having multiple groups per user is possible)
- I need to add updating group profile - group profile will contain space information (I think name for starters?), so I need a logic to create / update group profile when new space is created / updated

2022-10-06 14:15 UTC, mattcasey approved these changes
really nice work!

2022-10-06 20:03 UTC, merged