Lasting proposals & marking proposals in nexus
charmverse/app.charmverse.io pull request #946
Opened 2022-09-21 16:12 UTC by Devorein

2022-09-21 16:15 UTC, mattcasey commented on background/tasks/sendNotifications/sendNotifications.ts
> +            ...workspaceEvents.map(workspaceEvent => `${workspaceEvent.id}.${user.id}`)
do we have the same issue with votes?

2022-09-21 16:18 UTC, mattcasey commented on components/nexus/ProposalTasksList.tsx
> +  }, [tasks, user]);
we only want to run this if user.id changes

2022-09-21 16:24 UTC, mattcasey commented on lib/proposal/getProposalTasks.ts
> +      if (workspaceEvent && !userNotificationIds.has(`${workspaceEvent.id}.${userId}`)) {
as mentioned above... the formatting of the id should really only be handled in one place, or in a utility function. that would allow us to see where it gets used at least, and we make sure it's all consistent

2022-09-21 16:26 UTC, mattcasey commented on lib/proposal/getProposalTasksFromWorkspaceEvents.ts
> +        id: `${workspaceEvent.id}.${userId}`,
+1 can we do this inside getProposalTasks as well?

2022-09-21 16:28 UTC, mattcasey requested changes
TL;DR: can you reduce the amount of places we format the unique id for proposal tasks. But Also, isn't this an issue for votes? And did you consider just fixing the constraint on the db?

2022-09-21 17:26 UTC, Devorein commented on background/tasks/sendNotifications/sendNotifications.ts
> +            ...workspaceEvents.map(workspaceEvent => `${workspaceEvent.id}.${user.id}`)
I've removed the userId when creating the workspace event id, it turns out we had two unique directives for our UserNotification prisma schema. Removing that fixed the issue.

2022-09-21 17:28 UTC, Devorein commented on lib/proposal/getProposalTasks.ts
> +        id: workspaceEvent?.id ?? proposal.id,
Updated code to use a uuid, rather than relying on proposal if when workspace event doesn't exist. Normally workspace event does exist (unless its a newly created proposal), but now we will create a new workspace event anytime a proposal is created.

2022-09-21 17:48 UTC, Devorein commented on lib/proposal/getProposalTasksFromWorkspaceEvents.ts
> +        id: `${workspaceEvent.id}.${userId}`,
Removed userId when generating proposalTask id

2022-09-22 03:35 UTC, Devorein commented on prisma/schema.prisma
> +  proposal_create
Yep I will remove the migration and update the code dependant upon it.

2022-09-22 03:58 UTC, mattcasey approved these changes

2022-09-22 05:36 UTC, merged